import { createTagUtils } from "./utils";

export const tags = {
  "zh-CN": {
    tag: "zh-CN",
    name: "Zjednodušená čínština",
    nativeName: "简体中文",
    primary: true,
  },
  "zh-TW": {
    tag: "zh-TW",
    name: "Tradiční čínština (Tchaj-wan)",
    nativeName: "繁體中文(臺灣)",
    primary: false,
  },
  "zh-HK": {
    tag: "zh-HK",
    name: "Tradiční čínština (Hongkong)",
    nativeName: "繁體中文(香港),",
    primary: false,
  },
  "zh-SG": {
    tag: "zh-SG",
    name: "Zjednodušená čínština (Singapur)",
    nativeName: "简体中文(新加坡)",
    primary: false,
  },
  "zh-MO": {
    tag: "zh-MO",
    name: "Tradiční čínština (Macao)",
    nativeName: "繁體中文(澳門)",
    primary: false,
  },
  "zh-CHS": {
    tag: "zh-CHS",
    name: "Zjednodušená čínština",
    nativeName: "简体中文,",
    primary: false,
  },
  "zh-CHT": {
    tag: "zh-CHT",
    name: "Tradiční čínština",
    nativeName: "繁體中文,",
    primary: false,
  },
  "en-US": {
    tag: "en-US",
    name: "Angličtina (Spojené státy)",
    nativeName: "English (United States)",
    primary: true,
  },
  "en-GB": {
    tag: "en-GB",
    name: "Angličtina (Spojené království)",
    nativeName: "English (United Kingdom)",
    primary: false,
  },
  "en-IN": {
    tag: "en-IN",
    name: "Angličtina (Indie)",
    nativeName: "English (India)",
    primary: false,
  },
  "en-CA": {
    tag: "en-CA",
    name: "Angličtina (Kanada)",
    nativeName: "English (Canada)",
    primary: false,
  },
  "en-AU": {
    tag: "en-AU",
    name: "Angličtina (Austrálie)",
    nativeName: "English (Australia)",
    primary: false,
  },
  "en-ZA": {
    tag: "en-ZA",
    name: "Angličtina (Jižní Afrika)",
    nativeName: "English (South Africa)",
    primary: false,
  },
  "en-NZ": {
    tag: "en-NZ",
    name: "Angličtina (Nový Zéland)",
    nativeName: "English (New Zealand)",
    primary: false,
  },
  "en-IE": {
    tag: "en-IE",
    name: "Angličtina (Irsko)",
    nativeName: "English (Ireland)",
    primary: false,
  },
  "en-PH": {
    tag: "en-PH",
    name: "Angličtina (Filipíny)",
    nativeName: "English (Philippines)",
    primary: false,
  },
  "en-ZW": {
    tag: "en-ZW",
    name: "Angličtina (Zimbabwe)",
    nativeName: "English (Zimbabwe)",
    primary: false,
  },
  "en-BZ": {
    tag: "en-BZ",
    name: "Angličtina (Belize)",
    nativeName: "English (Belize)",
    primary: false,
  },
  "en-CB": {
    tag: "en-CB",
    name: "Angličtina (Karibik)",
    nativeName: "English (Caribbean)",
    primary: false,
  },
  "en-JM": {
    tag: "en-JM",
    name: "Angličtina (Jamajka)",
    nativeName: "English (Jamaica)",
    primary: false,
  },
  "en-TT": {
    tag: "en-TT",
    name: "Angličtina (Trinidad a Tobago)",
    nativeName: "English (Trinidad and Tobago)",
    primary: false,
  },
  "en-NG": {
    tag: "en-NG",
    name: "Angličtina (Nigérie)",
    nativeName: "English (Nigeria)",
    primary: false,
  },
  "en-UG": {
    tag: "en-UG",
    name: "Angličtina (Uganda)",
    nativeName: "English (Uganda)",
    primary: false,
  },
  "hi-IN": {
    tag: "hi-IN",
    name: "Hindština",
    nativeName: "हिन्दी (Hindi)",
    primary: false,
  },
  "es-ES": {
    tag: "es-ES",
    name: "Španělština (Španělsko)",
    nativeName: "Español (España)",
    primary: true,
  },
  "es-MX": {
    tag: "es-MX",
    name: "Španělština (Mexiko)",
    nativeName: "Español (México)",
    primary: false,
  },
  "es-AR": {
    tag: "es-AR",
    name: "Španělština (Argentina)",
    nativeName: "Español (Argentina)",
    primary: false,
  },
  "es-CO": {
    tag: "es-CO",
    name: "Španělština (Kolumbie)",
    nativeName: "Español (Colombia)",
    primary: false,
  },
  "es-PE": {
    tag: "es-PE",
    name: "Španělština (Peru)",
    nativeName: "Español (Perú)",
    primary: false,
  },
  "es-VE": {
    tag: "es-VE",
    name: "Španělština (Venezuela)",
    nativeName: "Español (Venezuela)",
    primary: false,
  },
  "es-CL": {
    tag: "es-CL",
    name: "Španělština (Chile)",
    nativeName: "Español (Chile)",
    primary: false,
  },
  "es-EC": {
    tag: "es-EC",
    name: "Španělština (Ekvádor)",
    nativeName: "Español (Ecuador)",
    primary: false,
  },
  "es-GT": {
    tag: "es-GT",
    name: "Španělština (Guatemala)",
    nativeName: "Español (Guatemala)",
    primary: false,
  },
  "es-CU": {
    tag: "es-CU",
    name: "Španělština (Kuba)",
    nativeName: "Español (Cuba)",
    primary: false,
  },
  "es-BO": {
    tag: "es-BO",
    name: "Španělština (Bolívie)",
    nativeName: "Español (Bolivia)",
    primary: false,
  },
  "es-DO": {
    tag: "es-DO",
    name: "Španělština (Dominikánská republika)",
    nativeName: "Español (República Dominicana)",
    primary: false,
  },
  "es-HN": {
    tag: "es-HN",
    name: "Španělština (Honduras)",
    nativeName: "Español (Honduras)",
    primary: false,
  },
  "es-PY": {
    tag: "es-PY",
    name: "Španělština (Paraguay)",
    nativeName: "Español (Paraguay)",
    primary: false,
  },
  "es-SV": {
    tag: "es-SV",
    name: "Španělština (El Salvador)",
    nativeName: "Español (El Salvador)",
    primary: false,
  },
  "es-NI": {
    tag: "es-NI",
    name: "Španělština (Nikaragua)",
    nativeName: "Español (Nicaragua)",
    primary: false,
  },
  "es-PR": {
    tag: "es-PR",
    name: "Španělština (Portoriko)",
    nativeName: "Español (Puerto Rico)",
    primary: false,
  },
  "es-UY": {
    tag: "es-UY",
    name: "Španělština (Uruguay)",
    nativeName: "Español (Uruguay)",
    primary: false,
  },
  "es-PA": {
    tag: "es-PA",
    name: "Španělština (Panama)",
    nativeName: "Español (Panamá)",
    primary: false,
  },
  "es-CR": {
    tag: "es-CR",
    name: "Španělština (Kostarika)",
    nativeName: "Español (Costa Rica)",
    primary: false,
  },
  "ar-EG": {
    tag: "ar-EG",
    name: "Arabština (Egypt)",
    nativeName: "العربية (مصر)",
    primary: true,
  },
  "ar-SA": {
    tag: "ar-SA",
    name: "Arabština (Saúdská Arábie)",
    nativeName: "العربية (السعودية)",
    primary: false,
  },
  "ar-DZ": {
    tag: "ar-DZ",
    name: "Arabština (Alžírsko)",
    nativeName: "العربية (الجزائر)",
    primary: false,
  },
  "ar-MA": {
    tag: "ar-MA",
    name: "Arabština (Maroko)",
    nativeName: "العربية (المغرب)",
    primary: false,
  },
  "ar-IQ": {
    tag: "ar-IQ",
    name: "Arabština (Irák)",
    nativeName: "العربية (العراق)",
    primary: false,
  },
  "ar-SD": {
    tag: "ar-SD",
    name: "Arabština (Súdán)",
    nativeName: "العربية (السودان)",
    primary: false,
  },
  "ar-YE": {
    tag: "ar-YE",
    name: "Arabština (Jemen)",
    nativeName: "العربية (اليمن)",
    primary: false,
  },
  "ar-SY": {
    tag: "ar-SY",
    name: "Arabština (Sýrie)",
    nativeName: "العربية (سوريا)",
    primary: false,
  },
  "ar-TN": {
    tag: "ar-TN",
    name: "Arabština (Tunisko)",
    nativeName: "العربية (تونس)",
    primary: false,
  },
  "ar-LY": {
    tag: "ar-LY",
    name: "Arabština (Libye)",
    nativeName: "العربية (ليبيا)",
    primary: false,
  },
  "ar-JO": {
    tag: "ar-JO",
    name: "Arabština (Jordánsko)",
    nativeName: "العربية (الأردن)",
    primary: false,
  },
  "ar-LB": {
    tag: "ar-LB",
    name: "Arabština (Libanon)",
    nativeName: "العربية (لبنان)",
    primary: false,
  },
  "ar-KW": {
    tag: "ar-KW",
    name: "Arabština (Kuvajt)",
    nativeName: "العربية (الكويت)",
    primary: false,
  },
  "ar-AE": {
    tag: "ar-AE",
    name: "Arabština (Spojené arabské emiráty)",
    nativeName: "العربية (الإمارات)",
    primary: false,
  },
  "ar-BH": {
    tag: "ar-BH",
    name: "Arabština (Bahrajn)",
    nativeName: "العربية (البحرين)",
    primary: false,
  },
  "ar-QA": {
    tag: "ar-QA",
    name: "Arabština (Katar)",
    nativeName: "العربية (قطر)",
    primary: false,
  },
  "ar-OM": {
    tag: "ar-OM",
    name: "Arabština (Omán)",
    nativeName: "العربية (عمان)",
    primary: false,
  },
  "pt-BR": {
    tag: "pt-BR",
    name: "Portugalština (Brazílie)",
    nativeName: "Português (Brasil)",
    primary: false,
  },
  "pt-PT": {
    tag: "pt-PT",
    name: "Portugalština (Portugalsko)",
    nativeName: "Português (Portugal)",
    primary: true,
  },
  "ru-RU": {
    tag: "ru-RU",
    name: "Ruština",
    nativeName: "Русский (Россия)",
    primary: true,
  },
  "ja-JP": {
    tag: "ja-JP",
    name: "Japonština",
    nativeName: "日本語 (日本)",
    primary: true,
  },
  "de-DE": {
    tag: "de-DE",
    name: "Němčina (Německo)",
    nativeName: "Deutsch (Deutschland)",
    primary: true,
  },
  "de-AT": {
    tag: "de-AT",
    name: "Němčina (Rakousko)",
    nativeName: "Deutsch (Österreich)",
    primary: false,
  },
  "de-CH": {
    tag: "de-CH",
    name: "Němčina (Švýcarsko)",
    nativeName: "Deutsch (Schweiz)",
    primary: false,
  },
  "fr-FR": {
    tag: "fr-FR",
    name: "Francouzština (Francie)",
    nativeName: "Français (France)",
    primary: true,
  },
  "fr-CA": {
    tag: "fr-CA",
    name: "Francouzština (Kanada)",
    nativeName: "Français (Canada)",
    primary: false,
  },
  "fr-BE": {
    tag: "fr-BE",
    name: "Francouzština (Belgie)",
    nativeName: "Français (Belgique)",
    primary: false,
  },
  "fr-CH": {
    tag: "fr-CH",
    name: "Francouzština (Švýcarsko)",
    nativeName: "Français (Suisse)",
    primary: false,
  },
  "fr-LU": {
    tag: "fr-LU",
    name: "Francouzština (Lucembursko)",
    nativeName: "Français (Luxembourg)",
    primary: false,
  },
  "fr-MC": {
    tag: "fr-MC",
    name: "Francouzština (Monako)",
    nativeName: "Français (Monaco)",
    primary: false,
  },
  "fr-CD": {
    tag: "fr-CD",
    name: "Francouzština (Demokratická republika Kongo)",
    nativeName: "Français (République démocratique du Congo)",
    primary: false,
  },
  "ko-KR": {
    tag: "ko-KR",
    name: "Korejština (Jižní Korea)",
    nativeName: "한국어 (대한민국)",
    primary: true,
  },
  "ko-KP": {
    tag: "ko-KP",
    name: "Korejština (Severní Korea)",
    nativeName: "한국어 (조선민주주인민공화국)",
    primary: false,
  },
  "it-IT": {
    tag: "it-IT",
    name: "Italština",
    nativeName: "Italiano (Italia)",
    primary: true,
  },
  "it-CH": {
    tag: "it-CH",
    name: "Italština (Švýcarsko)",
    nativeName: "Italiano (Svizzera)",
    primary: false,
  },
  "nl-NL": {
    tag: "nl-NL",
    name: "Nizozemština",
    nativeName: "Nederlands (Nederland)",
    primary: true,
  },
  "nl-BE": {
    tag: "nl-BE",
    name: "Nizozemština (Belgie)",
    nativeName: "Nederlands (België)",
    primary: false,
  },
  "bn-BD": {
    tag: "bn-BD",
    name: "Bengálština (Bangladéš)",
    nativeName: "বাংলা (বাংলাদেশ)",
    primary: false,
  },
  "pl-PL": {
    tag: "pl-PL",
    name: "Polština",
    nativeName: "Polski (Polska)",
    primary: false,
  },
  "vi-VN": {
    tag: "vi-VN",
    name: "Vietnamština",
    nativeName: "Tiếng Việt (Việt Nam)",
    primary: false,
  },
  "tr-TR": {
    tag: "tr-TR",
    name: "Turečtina",
    nativeName: "Türkçe (Türkiye)",
    primary: false,
  },
  "th-TH": {
    tag: "th-TH",
    name: "Thajština",
    nativeName: "ไทย (ประเทศไทย)",
    primary: false,
  },
  "el-GR": {
    tag: "el-GR",
    name: "Řečtina",
    nativeName: "Ελληνικά (Ελλάδα)",
    primary: false,
  },
  "cs-CZ": {
    tag: "cs-CZ",
    name: "Čeština",
    nativeName: "Čeština (Česká republika)",
    primary: false,
  },
  "sv-SE": {
    tag: "sv-SE",
    name: "Švédština",
    nativeName: "Svenska (Sverige)",
    primary: false,
  },
  "sv-FI": {
    tag: "sv-FI",
    name: "Švédština (Finsko)",
    nativeName: "Svenska (Finland)",
    primary: false,
  },
  "hu-HU": {
    tag: "hu-HU",
    name: "Maďarština",
    nativeName: "Magyar (Magyarország)",
    primary: false,
  },
  "fi-FI": {
    tag: "fi-FI",
    name: "Finština",
    nativeName: "Suomi (Suomi)",
    primary: false,
  },
  "da-DK": {
    tag: "da-DK",
    name: "Dánština",
    nativeName: "Dansk (Danmark)",
    primary: false,
  },
  "nb-NO": {
    tag: "nb-NO",
    name: "Norština Bokmål",
    nativeName: "Norsk Bokmål (Norge)",
    primary: false,
  },
  "nn-NO": {
    tag: "nn-NO",
    name: "Norština Nynorsk",
    nativeName: "Norsk Nynorsk (Norge)",
    primary: false,
  },
  "he-IL": {
    tag: "he-IL",
    name: "Hebrejština",
    nativeName: "עברית (ישראל)",
    primary: false,
  },
  "id-ID": {
    tag: "id-ID",
    name: "Indonéština",
    nativeName: "Bahasa Indonesia (Indonesia)",
    primary: false,
  },
  "ms-MY": {
    tag: "ms-MY",
    name: "Malajština (Malajsie)",
    nativeName: "Bahasa Melayu (Malaysia)",
    primary: false,
  },
  "ms-BN": {
    tag: "ms-BN",
    name: "Malajština (Brunej)",
    nativeName: "Bahasa Melayu (Brunei)",
    primary: false,
  },
  "ro-RO": {
    tag: "ro-RO",
    name: "Rumunština",
    nativeName: "Română (România)",
    primary: false,
  },
  "bg-BG": {
    tag: "bg-BG",
    name: "Bulharština",
    nativeName: "Български (България)",
    primary: false,
  },
  "uk-UA": {
    tag: "uk-UA",
    name: "Ukrajinština",
    nativeName: "Українська (Україна)",
    primary: false,
  },
  "sk-SK": {
    tag: "sk-SK",
    name: "Slovenština",
    nativeName: "Slovenčina (Slovensko)",
    primary: false,
  },
  "sl-SI": {
    tag: "sl-SI",
    name: "Slovinština",
    nativeName: "Slovenščina (Slovenija)",
    primary: false,
  },
  "hr-HR": {
    tag: "hr-HR",
    name: "Chorvatština",
    nativeName: "Hrvatski (Hrvatska)",
    primary: false,
  },
  "ca-ES": {
    tag: "ca-ES",
    name: "Katalánština",
    nativeName: "Català (Catalunya)",
    primary: false,
  },
  "lt-LT": {
    tag: "lt-LT",
    name: "Litevština",
    nativeName: "Lietuvių (Lietuva)",
    primary: false,
  },
  "lv-LV": {
    tag: "lv-LV",
    name: "Lotyština",
    nativeName: "Latviešu (Latvija)",
    primary: false,
  },
  "et-EE": {
    tag: "et-EE",
    name: "Estonština",
    nativeName: "Eesti (Eesti)",
    primary: false,
  },
  "sq-AL": {
    tag: "sq-AL",
    name: "Albánština",
    nativeName: "Shqip (Shqipëri)",
    primary: false,
  },
  "mk-MK": {
    tag: "mk-MK",
    name: "Makedonština",
    nativeName: "Македонски (Македонија)",
    primary: false,
  },
  "be-BY": {
    tag: "be-BY",
    name: "Běloruština",
    nativeName: "Беларуская (Беларусь)",
    primary: false,
  },
  "is-IS": {
    tag: "is-IS",
    name: "Islandština",
    nativeName: "Íslenska (Ísland)",
    primary: false,
  },
  "gl-ES": {
    tag: "gl-ES",
    name: "Galicijština",
    nativeName: "Galego (Galicia)",
    primary: false,
  },
  "eu-ES": {
    tag: "eu-ES",
    name: "Baskičtina",
    nativeName: "Euskara (Euskal Herria)",
    primary: false,
  },
  "af-ZA": {
    tag: "af-ZA",
    name: "Afrikánština",
    nativeName: "Afrikaans (Suid-Afrika)",
    primary: false,
  },
  "sw-KE": {
    tag: "sw-KE",
    name: "Svahilština",
    nativeName: "Kiswahili (Kenya)",
    primary: false,
  },
  "ta-IN": {
    tag: "ta-IN",
    name: "Tamilština",
    nativeName: "தமிழ் (இந்தியா)",
    primary: false,
  },
  "te-IN": {
    tag: "te-IN",
    name: "Telugština",
    nativeName: "తెలుగు (భారతదేశం)",
    primary: false,
  },
  "kn-IN": {
    tag: "kn-IN",
    name: "Kannadština",
    nativeName: "ಕನ್ನಡ (ಭಾರತ)",
    primary: false,
  },
  "mr-IN": {
    tag: "mr-IN",
    name: "Maráthština",
    nativeName: "मराठी (भारत)",
    primary: false,
  },
  "gu-IN": {
    tag: "gu-IN",
    name: "Gudžarátština",
    nativeName: "ગુજરાતી (ભારત)",
    primary: false,
  },
  "pa-IN": {
    tag: "pa-IN",
    name: "Paňdžábština",
    nativeName: "ਪੰਜਾਬੀ (ਭਾਰਤ)",
    primary: false,
  },
  "kok-IN": {
    tag: "kok-IN",
    name: "Kónkánština",
    nativeName: "कोंकणी (भारत)",
    primary: false,
  },
  "sa-IN": {
    tag: "sa-IN",
    name: "Sanskrt",
    nativeName: "संस्कृत (भारत)",
    primary: false,
  },
  "ur-PK": {
    tag: "ur-PK",
    name: "Urdština",
    nativeName: "اردو (پاکستان)",
    primary: false,
  },
  "fa-IR": {
    tag: "fa-IR",
    name: "Perština",
    nativeName: "فارسی (ایران)",
    primary: false,
  },
  "syr-SY": {
    tag: "syr-SY",
    name: "Sýrština",
    nativeName: "ܣܘܪܝܝܐ (ܣܘܪܝܐ)",
    primary: false,
  },
  "div-MV": {
    tag: "div-MV",
    name: "Maldivština",
    nativeName: "ދިވެހި (މޯލްޑިވްސް)",
    primary: false,
  },
  "ka-GE": {
    tag: "ka-GE",
    name: "Gruzínština",
    nativeName: "ქართული (საქართველო)",
    primary: false,
  },
  "am-ET": {
    tag: "am-ET",
    name: "Amharština (Etiopie)",
    nativeName: "አማርኛ (ኢትዮጵያ)",
    primary: false,
  },
  "my-MM": {
    tag: "my-MM",
    name: "Barmština",
    nativeName: "မြန်မာ (မြန်မာ)",
    primary: false,
  },
};

const { getTag, getTags, getPrimaryTags } = createTagUtils(tags);
export { getTag, getTags, getPrimaryTags };
export * from "./types";
