import { createTagUtils } from './utils'

export const tags = {
        "zh-CN": {"tag": "zh-CN", "name": "Kinesisk (forenklet)", "nativeName": "简体中文", "primary": true },
        "zh-TW": {"tag": "zh-TW", "name": "Kinesisk (traditionel - Taiwan)", "nativeName": "繁體中文 (中國臺灣)", "primary": false },
        "zh-HK": {"tag": "zh-HK", "name": "Kinesisk (traditionel - Hongkong)", "nativeName": "繁體中文(中國香港)", "primary": false },
        "zh-MO": {"tag": "zh-MO", "name": "Kinesisk (traditionel - Macau)", "nativeName": "繁體中文 (中國澳门)", "primary": false },
        "zh-SG": {"tag": "zh-SG", "name": "Kinesisk (forenklet - Singapore)", "nativeName": "简体中文 (新加坡)", "primary": false },      
        "zh-CHS": {"tag": "zh-CHS", "name": "Kinesisk (forenklet)", "nativeName": "简体中文", "primary": false },
        "zh-CHT": {"tag": "zh-CHT", "name": "Kinesisk (traditionel)", "nativeName": "繁體中文 (Traditional Chinese)", "primary": false },
        "en-US": {"tag": "en-US", "name": "Engelsk (USA)", "nativeName": "English (United States)", "primary": true },
        "en-GB": {"tag": "en-GB", "name": "Engelsk (Storbritannien)", "nativeName": "English (United Kingdom)", "primary": false },
        "en-CA": {"tag": "en-CA", "name": "Engelsk (Canada)", "nativeName": "English (Canada)", "primary": false },
        "en-AU": {"tag": "en-AU", "name": "Engelsk (Australien)", "nativeName": "English (Australia)", "primary": false },
        "en-IN": {"tag": "en-IN", "name": "Engelsk (Indien)", "nativeName": "English (India)", "primary": false },
        "en-ZA": {"tag": "en-ZA", "name": "Engelsk (Sydafrika)", "nativeName": "English (South Africa)", "primary": false },
        "en-NZ": {"tag": "en-NZ", "name": "Engelsk (New Zealand)", "nativeName": "English (New Zealand)", "primary": false },
        "en-IE": {"tag": "en-IE", "name": "Engelsk (Irland)", "nativeName": "English (Ireland)", "primary": false },
        "en-PH": {"tag": "en-PH", "name": "Engelsk (Filippinerne)", "nativeName": "English (Philippines)", "primary": false },
        "en-ZW": {"tag": "en-ZW", "name": "Engelsk (Zimbabwe)", "nativeName": "English (Zimbabwe)", "primary": false },
        "en-BZ": {"tag": "en-BZ", "name": "Engelsk (Belize)", "nativeName": "English (Belize)", "primary": false },
        "en-CB": {"tag": "en-CB", "name": "Engelsk (Caribien)", "nativeName": "English (Caribbean)", "primary": false },
        "en-JM": {"tag": "en-JM", "name": "Engelsk (Jamaica)", "nativeName": "English (Jamaica)", "primary": false },
        "en-TT": {"tag": "en-TT", "name": "Engelsk (Trinidad og Tobago)", "nativeName": "English (Trinidad and Tobago)", "primary": false },
        "en-NG": {"tag": "en-NG", "name": "Engelsk (Nigeria)", "nativeName": "English (Nigeria)", "primary": false },
        "en-UG": {"tag": "en-UG", "name": "Engelsk (Uganda)", "nativeName": "English (Uganda)", "primary": false },
        "hi-IN": {"tag": "hi-IN", "name": "Hindi (Indien)", "nativeName": "हिन्दी (Hindi)", "primary": false },
        "es-ES": {"tag": "es-ES", "name": "Spansk (Spanien)", "nativeName": "Español (España)", "primary": true },
        "es-MX": {"tag": "es-MX", "name": "Spansk (Mexico)", "nativeName": "Español (México)", "primary": false },
        "es-AR": {"tag": "es-AR", "name": "Spansk (Argentina)", "nativeName": "Español (Argentina)", "primary": false },
        "es-CO": {"tag": "es-CO", "name": "Spansk (Colombia)", "nativeName": "Español (Colombia)", "primary": false },
        "es-PE": {"tag": "es-PE", "name": "Spansk (Peru)", "nativeName": "Español (Perú)", "primary": false },
        "es-VE": {"tag": "es-VE", "name": "Spansk (Venezuela)", "nativeName": "Español (Venezuela)", "primary": false },
        "es-CL": {"tag": "es-CL", "name": "Spansk (Chile)", "nativeName": "Español (Chile)", "primary": false },
        "es-EC": {"tag": "es-EC", "name": "Spansk (Ecuador)", "nativeName": "Español (Ecuador)", "primary": false },
        "es-GT": {"tag": "es-GT", "name": "Spansk (Guatemala)", "nativeName": "Español (Guatemala)", "primary": false },
        "es-CU": {"tag": "es-CU", "name": "Spansk (Cuba)", "nativeName": "Español (Cuba)", "primary": false },
        "es-BO": {"tag": "es-BO", "name": "Spansk (Bolivia)", "nativeName": "Español (Bolivia)", "primary": false },
        "es-DO": {"tag": "es-DO", "name": "Spansk (Dominikanske Republik)", "nativeName": "Español (República Dominicana)", "primary": false },
        "es-HN": {"tag": "es-HN", "name": "Spansk (Honduras)", "nativeName": "Español (Honduras)", "primary": false },
        "es-PY": {"tag": "es-PY", "name": "Spansk (Paraguay)", "nativeName": "Español (Paraguay)", "primary": false },
        "es-SV": {"tag": "es-SV", "name": "Spansk (El Salvador)", "nativeName": "Español (El Salvador)", "primary": false },
        "es-NI": {"tag": "es-NI", "name": "Spansk (Nicaragua)", "nativeName": "Español (Nicaragua)", "primary": false },
        "es-PR": {"tag": "es-PR", "name": "Spansk (Puerto Rico)", "nativeName": "Español (Puerto Rico)", "primary": false },
        "es-UY": {"tag": "es-UY", "name": "Spansk (Uruguay)", "nativeName": "Español (Uruguay)", "primary": false },
        "es-PA": {"tag": "es-PA", "name": "Spansk (Panama)", "nativeName": "Español (Panamá)", "primary": false },
        "es-CR": {"tag": "es-CR", "name": "Spansk (Costa Rica)", "nativeName": "Español (Costa Rica)", "primary": false },
        "ar-EG": {"tag": "ar-EG", "name": "Arabisk (Egypten)", "nativeName": "العربية (مصر)", "primary": true },
        "ar-SA": {"tag": "ar-SA", "name": "Arabisk (Saudi-Arabien)", "nativeName": "العربية (السعودية)", "primary": false },
        "ar-DZ": {"tag": "ar-DZ", "name": "Arabisk (Algeriet)", "nativeName": "العربية (الجزائر)", "primary": false },
        "ar-MA": {"tag": "ar-MA", "name": "Arabisk (Marokko)", "nativeName": "العربية (المغرب)", "primary": false },
        "ar-IQ": {"tag": "ar-IQ", "name": "Arabisk (Irak)", "nativeName": "العربية (العراق)", "primary": false },
        "ar-SD": {"tag": "ar-SD", "name": "Arabisk (Sudan)", "nativeName": "العربية (السودان)", "primary": false },
        "ar-YE": {"tag": "ar-YE", "name": "Arabisk (Yemen)", "nativeName": "العربية (اليمن)", "primary": false },
        "ar-SY": {"tag": "ar-SY", "name": "Arabisk (Syrien)", "nativeName": "العربية (سوريا)", "primary": false },
        "ar-TN": {"tag": "ar-TN", "name": "Arabisk (Tunesien)", "nativeName": "العربية (تونس)", "primary": false },
        "ar-LY": {"tag": "ar-LY", "name": "Arabisk (Libyen)", "nativeName": "العربية (ليبيا)", "primary": false },
        "ar-JO": {"tag": "ar-JO", "name": "Arabisk (Jordan)", "nativeName": "العربية (الأردن)", "primary": false },
        "ar-LB": {"tag": "ar-LB", "name": "Arabisk (Libanon)", "nativeName": "العربية (لبنان)", "primary": false },
        "ar-KW": {"tag": "ar-KW", "name": "Arabisk (Kuwait)", "nativeName": "العربية (الكويت)", "primary": false },
        "ar-AE": {"tag": "ar-AE", "name": "Arabisk (De Forenede Arabiske Emirater)", "nativeName": "العربية (الإمارات)", "primary": false },
        "ar-BH": {"tag": "ar-BH", "name": "Arabisk (Bahrain)", "nativeName": "العربية (البحرين)", "primary": false },
        "ar-QA": {"tag": "ar-QA", "name": "Arabisk (Qatar)", "nativeName": "العربية (قطر)", "primary": false },
        "ar-OM": {"tag": "ar-OM", "name": "Arabisk (Oman)", "nativeName": "العربية (عمان)", "primary": false },
        "pt-BR": {"tag": "pt-BR", "name": "Portugisisk (Brasilien)", "nativeName": "Português (Brasil)", "primary": false },
        "pt-PT": {"tag": "pt-PT", "name": "Portugisisk (Portugal)", "nativeName": "Português (Portugal)", "primary": true },
        "ru-RU": {"tag": "ru-RU", "name": "Russisk (Rusland)", "nativeName": "Русский (Россия)", "primary": true },
        "ja-JP": {"tag": "ja-JP", "name": "Japansk (Japan)", "nativeName": "日本語 (日本)", "primary": true },
        "de-DE": {"tag": "de-DE", "name": "Tysk (Tyskland)", "nativeName": "Deutsch (Deutschland)", "primary": true },
        "de-AT": {"tag": "de-AT", "name": "Tysk (Østrig)", "nativeName": "Deutsch (Österreich)", "primary": false },
        "de-CH": {"tag": "de-CH", "name": "Tysk (Schweiz)", "nativeName": "Deutsch (Schweiz)", "primary": false },
        "fr-FR": {"tag": "fr-FR", "name": "Fransk (Frankrig)", "nativeName": "Français (France)", "primary": true },
        "fr-CA": {"tag": "fr-CA", "name": "Fransk (Canada)", "nativeName": "Français (Canada)", "primary": false },
        "fr-BE": {"tag": "fr-BE", "name": "Fransk (Belgien)", "nativeName": "Français (Belgique)", "primary": false },
        "fr-CH": {"tag": "fr-CH", "name": "Fransk (Schweiz)", "nativeName": "Français (Suisse)", "primary": false },
        "fr-LU": {"tag": "fr-LU", "name": "Fransk (Luxembourg)", "nativeName": "Français (Luxembourg)", "primary": false },
        "fr-MC": {"tag": "fr-MC", "name": "Fransk (Monaco)", "nativeName": "Français (Monaco)", "primary": false },
        "fr-CD": {"tag": "fr-CD", "name": "Fransk (Demokratiske Republik Congo)", "nativeName": "Français (République démocratique du Congo)", "primary": false },
        "ko-KR": {"tag": "ko-KR", "name": "Koreansk (Sydkorea)", "nativeName": "한국어 (대한민국)", "primary": true },
        "ko-KP": {"tag": "ko-KP", "name": "Koreansk (Nordkorea)", "nativeName": "한국어 (조선민주주인민공화국)", "primary": false },
        "it-IT": {"tag": "it-IT", "name": "Italiensk (Italien)", "nativeName": "Italiano (Italia)", "primary": true },
        "it-CH": {"tag": "it-CH", "name": "Italiensk (Schweiz)", "nativeName": "Italiano (Svizzera)", "primary": false },
        "nl-NL": {"tag": "nl-NL", "name": "Hollandsk (Holland)", "nativeName": "Nederlands (Nederland)", "primary": true },
        "nl-BE": {"tag": "nl-BE", "name": "Hollandsk (Belgien)", "nativeName": "Nederlands (België)", "primary": false },
        "bn-BD": {"tag": "bn-BD", "name": "Bengalsk (Bangladesh)", "nativeName": "বাংলা (বাংলাদেশ)", "primary": false },
        "pl-PL": {"tag": "pl-PL", "name": "Polsk (Polen)", "nativeName": "Polski (Polska)", "primary": false },
        "vi-VN": {"tag": "vi-VN", "name": "Vietnamesisk (Vietnam)", "nativeName": "Tiếng Việt (Việt Nam)", "primary": false },
        "tr-TR": {"tag": "tr-TR", "name": "Tyrkisk (Tyrkiet)", "nativeName": "Türkçe (Türkiye)", "primary": false },
        "th-TH": {"tag": "th-TH", "name": "Thailandsk (Thailand)", "nativeName": "ไทย (ประเทศไทย)", "primary": false },
        "el-GR": {"tag": "el-GR", "name": "Græsk (Grækenland)", "nativeName": "Ελληνικά (Ελλάδα)", "primary": false },
        "cs-CZ": {"tag": "cs-CZ", "name": "Tjekkisk (Tjekkiet)", "nativeName": "Čeština (Česká republika)", "primary": false },
        "sv-SE": {"tag": "sv-SE", "name": "Svensk (Sverige)", "nativeName": "Svenska (Sverige)", "primary": false },
        "sv-FI": {"tag": "sv-FI", "name": "Svensk (Finland)", "nativeName": "Svenska (Finland)", "primary": false },
        "hu-HU": {"tag": "hu-HU", "name": "Ungarsk (Ungarn)", "nativeName": "Magyar (Magyarország)", "primary": false },
        "fi-FI": {"tag": "fi-FI", "name": "Finsk (Finland)", "nativeName": "Suomi (Suomi)", "primary": false },
        "da-DK": {"tag": "da-DK", "name": "Dansk (Danmark)", "nativeName": "Dansk (Danmark)", "primary": false },
        "nb-NO": {"tag": "nb-NO", "name": "Norsk Bokmål (Norge)", "nativeName": "Norsk Bokmål (Norge)", "primary": false },
        "nn-NO": {"tag": "nn-NO", "name": "Norsk Nynorsk (Norge)", "nativeName": "Norsk Nynorsk (Norge)", "primary": false },
        "he-IL": {"tag": "he-IL", "name": "Hebraisk (Israel)", "nativeName": "עברית (ישראל)", "primary": false },
        "id-ID": {"tag": "id-ID", "name": "Indonesisk (Indonesien)", "nativeName": "Bahasa Indonesia (Indonesia)", "primary": false },
        "ms-MY": {"tag": "ms-MY", "name": "Malaysisk (Malaysia)", "nativeName": "Bahasa Melayu (Malaysia)", "primary": false },
        "ms-BN": {"tag": "ms-BN", "name": "Malaysisk (Brunei)", "nativeName": "Bahasa Melayu (Brunei)", "primary": false },       
        "ro-RO": {"tag": "ro-RO", "name": "Rumænsk (Rumænien)", "nativeName": "Română (România)", "primary": false },
        "bg-BG": {"tag": "bg-BG", "name": "Bulgarsk (Bulgarien)", "nativeName": "Български (България)", "primary": false },
        "uk-UA": {"tag": "uk-UA", "name": "Ukrainsk (Ukraine)", "nativeName": "Українська (Україна)", "primary": false },
        "sk-SK": {"tag": "sk-SK", "name": "Slovakisk (Slovakiet)", "nativeName": "Slovenčina (Slovensko)", "primary": false },
        "sl-SI": {"tag": "sl-SI", "name": "Slovensk (Slovenien)", "nativeName": "Slovenščina (Slovenija)", "primary": false },
        "hr-HR": {"tag": "hr-HR", "name": "Kroatisk (Kroatien)", "nativeName": "Hrvatski (Hrvatska)", "primary": false },
        "ca-ES": {"tag": "ca-ES", "name": "Catalansk (Catalonien)", "nativeName": "Català (Catalunya)", "primary": false },
        "lt-LT": {"tag": "lt-LT", "name": "Litauisk (Litauen)", "nativeName": "Lietuvių (Lietuva)", "primary": false },
        "lv-LV": {"tag": "lv-LV", "name": "Lettisk (Letland)", "nativeName": "Latviešu (Latvija)", "primary": false },
        "et-EE": {"tag": "et-EE", "name": "Estisk (Estland)", "nativeName": "Eesti (Eesti)", "primary": false },
        "sq-AL": {"tag": "sq-AL", "name": "Albansk (Albanien)", "nativeName": "Shqip (Shqipëri)", "primary": false },
        "mk-MK": {"tag": "mk-MK", "name": "Makedonsk (Nordmakedonien)", "nativeName": "Македонски (Македонија)", "primary": false },
        "be-BY": {"tag": "be-BY", "name": "Hviderussisk (Hviderusland)", "nativeName": "Беларуская (Беларусь)", "primary": false },
        "is-IS": {"tag": "is-IS", "name": "Islandsk (Island)", "nativeName": "Íslenska (Ísland)", "primary": false },
        "gl-ES": {"tag": "gl-ES", "name": "Galicisk (Galicien)", "nativeName": "Galego (Galicia)", "primary": false },
        "eu-ES": {"tag": "eu-ES", "name": "Baskisk (Baskerlandet)", "nativeName": "Euskara (Euskal Herria)", "primary": false },
        "af-ZA": {"tag": "af-ZA", "name": "Afrikaans (Sydafrika)", "nativeName": "Afrikaans (Suid-Afrika)", "primary": false },
        "sw-KE": {"tag": "sw-KE", "name": "Swahili (Kenya)", "nativeName": "Kiswahili (Kenya)", "primary": false },
        "ta-IN": {"tag": "ta-IN", "name": "Tamilsk (Indien)", "nativeName": "தமிழ் (இந்தியா)", "primary": false },
        "te-IN": {"tag": "te-IN", "name": "Telugu (Indien)", "nativeName": "తెలుగు (భారతదేశం)", "primary": false },
        "kn-IN": {"tag": "kn-IN", "name": "Kannada (Indien)", "nativeName": "ಕನ್ನಡ (ಭಾರತ)", "primary": false },
        "mr-IN": {"tag": "mr-IN", "name": "Marathi (Indien)", "nativeName": "मराठी (भारत)", "primary": false },
        "gu-IN": {"tag": "gu-IN", "name": "Gujarati (Indien)", "nativeName": "ગુજરાતી (ભારત)", "primary": false },
        "pa-IN": {"tag": "pa-IN", "name": "Punjabi (Indien)", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)", "primary": false },
        "kok-IN": {"tag": "kok-IN", "name": "Konkani (Indien)", "nativeName": "कोंकणी (भारत)", "primary": false },
        "sa-IN": {"tag": "sa-IN", "name": "Sanskrit (Indien)", "nativeName": "संस्कृत (भारत)", "primary": false },
        "ur-PK": {"tag": "ur-PK", "name": "Urdu (Pakistan)", "nativeName": "اردو (پاکستان)", "primary": false },
        "fa-IR": {"tag": "fa-IR", "name": "Persisk (Iran)", "nativeName": "فارسی (ایران)", "primary": false },
        "syr-SY": {"tag": "syr-SY", "name": "Syriansk (Syrien)", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)", "primary": false },
        "div-MV": {"tag": "div-MV", "name": "Dhivehi (Maldiverne)", "nativeName": "ދިވެހި (މޯލްޑިވްސް)", "primary": false },
        "ka-GE": {"tag": "ka-GE", "name": "Georgisk (Georgien)", "nativeName": "ქართული (საქართველო)", "primary": false },
        "am-ET": {"tag": "am-ET", "name": "Amharisk (Etiopien)", "nativeName": "አማርኛ (ኢትዮጵያ)", "primary": false },
        "my-MM": {"tag": "my-MM", "name": "Burmesisk (Myanmar)", "nativeName": "မြန်မာ (မြန်မာ)", "primary": false }
}


const { getTag, getTags, getPrimaryTags } = createTagUtils(tags)
export {
    getTag, getTags,getPrimaryTags
}
export * from './types'    