import { createTagUtils } from './utils'

export const tags = {
        "zh-CN": {"tag": "zh-CN", "name": "Κινεζικά (Απλοποιημένα)", "nativeName": "简体中文", "primary": true },
        "zh-TW": {"tag": "zh-TW", "name": "Κινεζικά (Παραδοσιακά - Ταϊβάν)", "nativeName": "繁體中文 (中國臺灣)", "primary": false },
        "zh-HK": {"tag": "zh-HK", "name": "Κινεζικά (Παραδοσιακά - Χονγκ Κονγκ)", "nativeName": "繁體中文(中國香港)", "primary": false },
        "zh-MO": {"tag": "zh-MO", "name": "Κινεζικά (Παραδοσιακά - Μακάο)", "nativeName": "繁體中文 (中國澳门)", "primary": false },
        "zh-SG": {"tag": "zh-SG", "name": "Κινεζικά (Απλοποιημένα - Σιγκαπούρη)", "nativeName": "简体中文 (新加坡)", "primary": false },      
        "zh-CHS": {"tag": "zh-CHS", "name": "Κινεζικά (Απλοποιημένα)", "nativeName": "简体中文", "primary": false },
        "zh-CHT": {"tag": "zh-CHT", "name": "Κινεζικά (Παραδοσιακά)", "nativeName": "繁體中文 (Traditional Chinese)", "primary": false },
        "en-US": {"tag": "en-US", "name": "Αγγλικά (Ηνωμένες Πολιτείες)", "nativeName": "English (United States)", "primary": true },
        "en-GB": {"tag": "en-GB", "name": "Αγγλικά (Ηνωμένο Βασίλειο)", "nativeName": "English (United Kingdom)", "primary": false },
        "en-CA": {"tag": "en-CA", "name": "Αγγλικά (Καναδάς)", "nativeName": "English (Canada)", "primary": false },
        "en-AU": {"tag": "en-AU", "name": "Αγγλικά (Αυστραλία)", "nativeName": "English (Australia)", "primary": false },
        "en-IN": {"tag": "en-IN", "name": "Αγγλικά (Ινδία)", "nativeName": "English (India)", "primary": false },
        "en-ZA": {"tag": "en-ZA", "name": "Αγγλικά (Νότια Αφρική)", "nativeName": "English (South Africa)", "primary": false },
        "en-NZ": {"tag": "en-NZ", "name": "Αγγλικά (Νέα Ζηλανδία)", "nativeName": "English (New Zealand)", "primary": false },
        "en-IE": {"tag": "en-IE", "name": "Αγγλικά (Ιρλανδία)", "nativeName": "English (Ireland)", "primary": false },
        "en-PH": {"tag": "en-PH", "name": "Αγγλικά (Φιλιππίνες)", "nativeName": "English (Philippines)", "primary": false },
        "en-ZW": {"tag": "en-ZW", "name": "Αγγλικά (Ζιμπάμπουε)", "nativeName": "English (Zimbabwe)", "primary": false },
        "en-BZ": {"tag": "en-BZ", "name": "Αγγλικά (Μπελίζ)", "nativeName": "English (Belize)", "primary": false },
        "en-CB": {"tag": "en-CB", "name": "Αγγλικά (Καραϊβική)", "nativeName": "English (Caribbean)", "primary": false },
        "en-JM": {"tag": "en-JM", "name": "Αγγλικά (Τζαμάικα)", "nativeName": "English (Jamaica)", "primary": false },
        "en-TT": {"tag": "en-TT", "name": "Αγγλικά (Τρινιντάντ και Τομπάγκο)", "nativeName": "English (Trinidad and Tobago)", "primary": false },
        "en-NG": {"tag": "en-NG", "name": "Αγγλικά (Νιγηρία)", "nativeName": "English (Nigeria)", "primary": false },
        "en-UG": {"tag": "en-UG", "name": "Αγγλικά (Ουγκάντα)", "nativeName": "English (Uganda)", "primary": false },
        "hi-IN": {"tag": "hi-IN", "name": "Χίντι (Ινδία)", "nativeName": "हिन्दी (Hindi)", "primary": false },
        "es-ES": {"tag": "es-ES", "name": "Ισπανικά (Ισπανία)", "nativeName": "Español (España)", "primary": true },
        "es-MX": {"tag": "es-MX", "name": "Ισπανικά (Μεξικό)", "nativeName": "Español (México)", "primary": false },
        "es-AR": {"tag": "es-AR", "name": "Ισπανικά (Αργεντινή)", "nativeName": "Español (Argentina)", "primary": false },
        "es-CO": {"tag": "es-CO", "name": "Ισπανικά (Κολομβία)", "nativeName": "Español (Colombia)", "primary": false },
        "es-PE": {"tag": "es-PE", "name": "Ισπανικά (Περού)", "nativeName": "Español (Perú)", "primary": false },
        "es-VE": {"tag": "es-VE", "name": "Ισπανικά (Βενεζουέλα)", "nativeName": "Español (Venezuela)", "primary": false },
        "es-CL": {"tag": "es-CL", "name": "Ισπανικά (Χιλή)", "nativeName": "Español (Chile)", "primary": false },
        "es-EC": {"tag": "es-EC", "name": "Ισπανικά (Ισημερινός)", "nativeName": "Español (Ecuador)", "primary": false },
        "es-GT": {"tag": "es-GT", "name": "Ισπανικά (Γουατεμάλα)", "nativeName": "Español (Guatemala)", "primary": false },
        "es-CU": {"tag": "es-CU", "name": "Ισπανικά (Κούβα)", "nativeName": "Español (Cuba)", "primary": false },
        "es-BO": {"tag": "es-BO", "name": "Ισπανικά (Βολιβία)", "nativeName": "Español (Bolivia)", "primary": false },
        "es-DO": {"tag": "es-DO", "name": "Ισπανικά (Δομινικανή Δημοκρατία)", "nativeName": "Español (República Dominicana)", "primary": false },
        "es-HN": {"tag": "es-HN", "name": "Ισπανικά (Ονδούρα)", "nativeName": "Español (Honduras)", "primary": false },
        "es-PY": {"tag": "es-PY", "name": "Ισπανικά (Παραγουάη)", "nativeName": "Español (Paraguay)", "primary": false },
        "es-SV": {"tag": "es-SV", "name": "Ισπανικά (Ελ Σαλβαδόρ)", "nativeName": "Español (El Salvador)", "primary": false },
        "es-NI": {"tag": "es-NI", "name": "Ισπανικά (Νικαράγουα)", "nativeName": "Español (Nicaragua)", "primary": false },
        "es-PR": {"tag": "es-PR", "name": "Ισπανικά (Πουέρτο Ρίκο)", "nativeName": "Español (Puerto Rico)", "primary": false },
        "es-UY": {"tag": "es-UY", "name": "Ισπανικά (Ουρουγουάη)", "nativeName": "Español (Uruguay)", "primary": false },
        "es-PA": {"tag": "es-PA", "name": "Ισπανικά (Παναμάς)", "nativeName": "Español (Panamá)", "primary": false },
        "es-CR": {"tag": "es-CR", "name": "Ισπανικά (Κόστα Ρίκα)", "nativeName": "Español (Costa Rica)", "primary": false },
        "ar-EG": {"tag": "ar-EG", "name": "Αραβικά (Αίγυπτος)", "nativeName": "العربية (مصر)", "primary": true },
        "ar-SA": {"tag": "ar-SA", "name": "Αραβικά (Σαουδική Αραβία)", "nativeName": "العربية (السعودية)", "primary": false },
        "ar-DZ": {"tag": "ar-DZ", "name": "Αραβικά (Αλγερία)", "nativeName": "العربية (الجزائر)", "primary": false },
        "ar-MA": {"tag": "ar-MA", "name": "Αραβικά (Μαρόκο)", "nativeName": "العربية (المغرب)", "primary": false },
        "ar-IQ": {"tag": "ar-IQ", "name": "Αραβικά (Ιράκ)", "nativeName": "العربية (العراق)", "primary": false },
        "ar-SD": {"tag": "ar-SD", "name": "Αραβικά (Σουδάν)", "nativeName": "العربية (السودان)", "primary": false },
        "ar-YE": {"tag": "ar-YE", "name": "Αραβικά (Υεμένη)", "nativeName": "العربية (اليمن)", "primary": false },
        "ar-SY": {"tag": "ar-SY", "name": "Αραβικά (Συρία)", "nativeName": "العربية (سوريا)", "primary": false },
        "ar-TN": {"tag": "ar-TN", "name": "Αραβικά (Τυνησία)", "nativeName": "العربية (تونس)", "primary": false },
        "ar-LY": {"tag": "ar-LY", "name": "Αραβικά (Λιβύη)", "nativeName": "العربية (ليبيا)", "primary": false },
        "ar-JO": {"tag": "ar-JO", "name": "Αραβικά (Ιορδανία)", "nativeName": "العربية (الأردن)", "primary": false },
        "ar-LB": {"tag": "ar-LB", "name": "Αραβικά (Λίβανος)", "nativeName": "العربية (لبنان)", "primary": false },
        "ar-KW": {"tag": "ar-KW", "name": "Αραβικά (Κουβέιτ)", "nativeName": "العربية (الكويت)", "primary": false },
        "ar-AE": {"tag": "ar-AE", "name": "Αραβικά (Ηνωμένα Αραβικά Εμιράτα)", "nativeName": "العربية (الإمارات)", "primary": false },
        "ar-BH": {"tag": "ar-BH", "name": "Αραβικά (Μπαχρέιν)", "nativeName": "العربية (البحرين)", "primary": false },
        "ar-QA": {"tag": "ar-QA", "name": "Αραβικά (Κατάρ)", "nativeName": "العربية (قطر)", "primary": false },
        "ar-OM": {"tag": "ar-OM", "name": "Αραβικά (Ομάν)", "nativeName": "العربية (عمان)", "primary": false },
        "pt-BR": {"tag": "pt-BR", "name": "Πορτογαλικά (Βραζιλία)", "nativeName": "Português (Brasil)", "primary": false },
        "pt-PT": {"tag": "pt-PT", "name": "Πορτογαλικά (Πορτογαλία)", "nativeName": "Português (Portugal)", "primary": true },
        "ru-RU": {"tag": "ru-RU", "name": "Ρωσικά (Ρωσία)", "nativeName": "Русский (Россия)", "primary": true },
        "ja-JP": {"tag": "ja-JP", "name": "Ιαπωνικά (Ιαπωνία)", "nativeName": "日本語 (日本)", "primary": true },
        "de-DE": {"tag": "de-DE", "name": "Γερμανικά (Γερμανία)", "nativeName": "Deutsch (Deutschland)", "primary": true },
        "de-AT": {"tag": "de-AT", "name": "Γερμανικά (Αυστρία)", "nativeName": "Deutsch (Österreich)", "primary": false },
        "de-CH": {"tag": "de-CH", "name": "Γερμανικά (Ελβετία)", "nativeName": "Deutsch (Schweiz)", "primary": false },
        "fr-FR": {"tag": "fr-FR", "name": "Γαλλικά (Γαλλία)", "nativeName": "Français (France)", "primary": true },
        "fr-CA": {"tag": "fr-CA", "name": "Γαλλικά (Καναδάς)", "nativeName": "Français (Canada)", "primary": false },
        "fr-BE": {"tag": "fr-BE", "name": "Γαλλικά (Βέλγιο)", "nativeName": "Français (Belgique)", "primary": false },
        "fr-CH": {"tag": "fr-CH", "name": "Γαλλικά (Ελβετία)", "nativeName": "Français (Suisse)", "primary": false },
        "fr-LU": {"tag": "fr-LU", "name": "Γαλλικά (Λουξεμβούργο)", "nativeName": "Français (Luxembourg)", "primary": false },
        "fr-MC": {"tag": "fr-MC", "name": "Γαλλικά (Μονακό)", "nativeName": "Français (Monaco)", "primary": false },
        "fr-CD": {"tag": "fr-CD", "name": "Γαλλικά (Λαϊκή Δημοκρατία του Κονγκό)", "nativeName": "Français (République démocratique du Congo)", "primary": false },
        "ko-KR": {"tag": "ko-KR", "name": "Κορεατικά (Νότια Κορέα)", "nativeName": "한국어 (대한민국)", "primary": true },
        "ko-KP": {"tag": "ko-KP", "name": "Κορεατικά (Βόρεια Κορέα)", "nativeName": "한국어 (조선민주주인민공화국)", "primary": false },
        "it-IT": {"tag": "it-IT", "name": "Ιταλικά (Ιταλία)", "nativeName": "Italiano (Italia)", "primary": true },
        "it-CH": {"tag": "it-CH", "name": "Ιταλικά (Ελβετία)", "nativeName": "Italiano (Svizzera)", "primary": false },
        "nl-NL": {"tag": "nl-NL", "name": "Ολλανδικά (Ολλανδία)", "nativeName": "Nederlands (Nederland)", "primary": true },
        "nl-BE": {"tag": "nl-BE", "name": "Ολλανδικά (Βέλγιο)", "nativeName": "Nederlands (België)", "primary": false },
        "bn-BD": {"tag": "bn-BD", "name": "Μπενγκάλι (Μπαγκλαντές)", "nativeName": "বাংলা (বাংলাদেশ)", "primary": false },
        "pl-PL": {"tag": "pl-PL", "name": "Πολωνικά (Πολωνία)", "nativeName": "Polski (Polska)", "primary": false },
        "vi-VN": {"tag": "vi-VN", "name": "Βιετναμέζικα (Βιετνάμ)", "nativeName": "Tiếng Việt (Việt Nam)", "primary": false },
        "tr-TR": {"tag": "tr-TR", "name": "Τουρκικά (Τουρκία)", "nativeName": "Türkçe (Türkiye)", "primary": false },
        "th-TH": {"tag": "th-TH", "name": "Ταϊλανδέζικα (Ταϊλάνδη)", "nativeName": "ไทย (ประเทศไทย)", "primary": false },
        "el-GR": {"tag": "el-GR", "name": "Ελληνικά (Ελλάδα)", "nativeName": "Ελληνικά (Ελλάδα)", "primary": false },
        "cs-CZ": {"tag": "cs-CZ", "name": "Τσεχικά (Τσεχία)", "nativeName": "Čeština (Česká republika)", "primary": false },
        "sv-SE": {"tag": "sv-SE", "name": "Σουηδικά (Σουηδία)", "nativeName": "Svenska (Sverige)", "primary": false },
        "sv-FI": {"tag": "sv-FI", "name": "Σουηδικά (Φινλανδία)", "nativeName": "Svenska (Finland)", "primary": false },
        "hu-HU": {"tag": "hu-HU", "name": "Ουγγρικά (Ουγγαρία)", "nativeName": "Magyar (Magyarország)", "primary": false },
        "fi-FI": {"tag": "fi-FI", "name": "Φινλανδικά (Φινλανδία)", "nativeName": "Suomi (Suomi)", "primary": false },
        "da-DK": {"tag": "da-DK", "name": "Δανέζικα (Δανία)", "nativeName": "Dansk (Danmark)", "primary": false },
        "nb-NO": {"tag": "nb-NO", "name": "Νορβηγικά Μποκμάλ (Νορβηγία)", "nativeName": "Norsk Bokmål (Norge)", "primary": false },
        "nn-NO": {"tag": "nn-NO", "name": "Νορβηγικά Νινόρσκ (Νορβηγία)", "nativeName": "Norsk Nynorsk (Norge)", "primary": false },
        "he-IL": {"tag": "he-IL", "name": "Εβραϊκά (Ισραήλ)", "nativeName": "עברית (ישראל)", "primary": false },
        "id-ID": {"tag": "id-ID", "name": "Ινδονησιακά (Ινδονησία)", "nativeName": "Bahasa Indonesia (Indonesia)", "primary": false },
        "ms-MY": {"tag": "ms-MY", "name": "Μαλαισιανά (Μαλαισία)", "nativeName": "Bahasa Melayu (Malaysia)", "primary": false },
        "ms-BN": {"tag": "ms-BN", "name": "Μαλαισιανά (Μπρουνέι)", "nativeName": "Bahasa Melayu (Brunei)", "primary": false },       
        "ro-RO": {"tag": "ro-RO", "name": "Ρουμανικά (Ρουμανία)", "nativeName": "Română (România)", "primary": false },
        "bg-BG": {"tag": "bg-BG", "name": "Βουλγαρικά (Βουλγαρία)", "nativeName": "Български (България)", "primary": false },
        "uk-UA": {"tag": "uk-UA", "name": "Ουκρανικά (Ουκρανία)", "nativeName": "Українська (Україна)", "primary": false },
        "sk-SK": {"tag": "sk-SK", "name": "Σλοβακικά (Σλοβακία)", "nativeName": "Slovenčina (Slovensko)", "primary": false },
        "sl-SI": {"tag": "sl-SI", "name": "Σλοβενικά (Σλοβενία)", "nativeName": "Slovenščina (Slovenija)", "primary": false },
        "hr-HR": {"tag": "hr-HR", "name": "Κροατικά (Κροατία)", "nativeName": "Hrvatski (Hrvatska)", "primary": false },
        "ca-ES": {"tag": "ca-ES", "name": "Καταλανικά (Καταλονία)", "nativeName": "Català (Catalunya)", "primary": false },
        "lt-LT": {"tag": "lt-LT", "name": "Λιθουανικά (Λιθουανία)", "nativeName": "Lietuvių (Lietuva)", "primary": false },
        "lv-LV": {"tag": "lv-LV", "name": "Λετονικά (Λετονία)", "nativeName": "Latviešu (Latvija)", "primary": false },
        "et-EE": {"tag": "et-EE", "name": "Εσθονικά (Εσθονία)", "nativeName": "Eesti (Eesti)", "primary": false },
        "sq-AL": {"tag": "sq-AL", "name": "Αλβανικά (Αλβανία)", "nativeName": "Shqip (Shqipëri)", "primary": false },
        "mk-MK": {"tag": "mk-MK", "name": "Σλαβομακεδονικά (Βόρεια Μακεδονία)", "nativeName": "Македонски (Македонија)", "primary": false },
        "be-BY": {"tag": "be-BY", "name": "Λευκορωσικά (Λευκορωσία)", "nativeName": "Беларуская (Беларусь)", "primary": false },
        "is-IS": {"tag": "is-IS", "name": "Ισλανδικά (Ισλανδία)", "nativeName": "Íslenska (Ísland)", "primary": false },
        "gl-ES": {"tag": "gl-ES", "name": "Γαλικιανά (Γαλικία)", "nativeName": "Galego (Galicia)", "primary": false },
        "eu-ES": {"tag": "eu-ES", "name": "Βασκικά (Χώρα των Βάσκων)", "nativeName": "Euskara (Euskal Herria)", "primary": false },
        "af-ZA": {"tag": "af-ZA", "name": "Αφρικάανς (Νότια Αφρική)", "nativeName": "Afrikaans (Suid-Afrika)", "primary": false },
        "sw-KE": {"tag": "sw-KE", "name": "Σουαχίλι (Κένυα)", "nativeName": "Kiswahili (Kenya)", "primary": false },
        "ta-IN": {"tag": "ta-IN", "name": "Ταμίλ (Ινδία)", "nativeName": "தமிழ் (இந்தியா)", "primary": false },
        "te-IN": {"tag": "te-IN", "name": "Τελούγκου (Ινδία)", "nativeName": "తెలుగు (భారతదేశం)", "primary": false },
        "kn-IN": {"tag": "kn-IN", "name": "Κανάντα (Ινδία)", "nativeName": "ಕನ್ನಡ (ಭಾರತ)", "primary": false },
        "mr-IN": {"tag": "mr-IN", "name": "Μαράθι (Ινδία)", "nativeName": "मराठी (भारत)", "primary": false },
        "gu-IN": {"tag": "gu-IN", "name": "Γκουτζαράτι (Ινδία)", "nativeName": "ગુજરાતી (ભારત)", "primary": false },
        "pa-IN": {"tag": "pa-IN", "name": "Παντζάμπι (Ινδία)", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)", "primary": false },
        "kok-IN": {"tag": "kok-IN", "name": "Κονκάνι (Ινδία)", "nativeName": "कोंकणी (भारत)", "primary": false },
        "sa-IN": {"tag": "sa-IN", "name": "Σανσκριτικά (Ινδία)", "nativeName": "संस्कृत (भारत)", "primary": false },
        "ur-PK": {"tag": "ur-PK", "name": "Ουρντού (Πακιστάν)", "nativeName": "اردو (پاکستان)", "primary": false },
        "fa-IR": {"tag": "fa-IR", "name": "Περσικά (Ιράν)", "nativeName": "فارسی (ایران)", "primary": false },
        "syr-SY": {"tag": "syr-SY", "name": "Αραμαϊκά Συρίας (Συρία)", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)", "primary": false },
        "div-MV": {"tag": "div-MV", "name": "Ντιβέχι (Μαλδίβες)", "nativeName": "ދިވެހި (މޯލްޑިވްސް)", "primary": false },
        "ka-GE": {"tag": "ka-GE", "name": "Γεωργιανά (Γεωργία)", "nativeName": "ქართული (საქართველო)", "primary": false },
        "am-ET": {"tag": "am-ET", "name": "Αμχαρικά (Αιθιοπία)", "nativeName": "አማርኛ (ኢትዮጵያ)", "primary": false },
        "my-MM": {"tag": "my-MM", "name": "Βιρμανικά (Μιανμάρ)", "nativeName": "မြန်မာ (မြန်မာ)", "primary": false }
}


const { getTag, getTags, getPrimaryTags } = createTagUtils(tags)
export {
    getTag, getTags,getPrimaryTags
}
export * from './types'    
