import { createTagUtils } from './utils'

export const tags = {
        "zh-CN": {"tag": "zh-CN", "name": "Chinese (Simplified)", "nativeName": "简体中文", "default": true},
        "zh-TW": {"tag": "zh-TW", "name": "Chinese (Traditional - Taiwan)", "nativeName": "繁體中文 (臺灣)"},
        "zh-HK": {"tag": "zh-HK", "name": "Chinese (Traditional - Hong Kong)", "nativeName": "繁體中文（香港）"},
        "zh-MO": {"tag": "zh-MO", "name": "Chinese (Traditional - Macau)", "nativeName": "繁體中文 (Traditional Chinese - Macau)"},
        "zh-SG": {"tag": "zh-SG", "name": "Chinese (Simplified - Singapore)", "nativeName": "简体中文 (Simplified Chinese - Singapore)"},      
        "zh-CHS": {"tag": "zh-CHS", "name": "Chinese (Simplified)", "nativeName": "简体中文"},
        "zh-CHT": {"tag": "zh-CHT", "name": "Chinese (Traditional)", "nativeName": "繁體中文 (Traditional Chinese)"},
        "en-US": {"tag": "en-US", "name": "English (United States)", "nativeName": "English (United States)", "default": true},
        "en-GB": {"tag": "en-GB", "name": "English (United Kingdom)", "nativeName": "English (United Kingdom)"},
        "en-CA": {"tag": "en-CA", "name": "English (Canada)", "nativeName": "English (Canada)"},
        "en-AU": {"tag": "en-AU", "name": "English (Australia)", "nativeName": "English (Australia)"},
        "en-IN": {"tag": "en-IN", "name": "English (India)", "nativeName": "English (India)"},
        "en-ZA": {"tag": "en-ZA", "name": "English (South Africa)", "nativeName": "English (South Africa)"},
        "en-NZ": {"tag": "en-NZ", "name": "English (New Zealand)", "nativeName": "English (New Zealand)"},
        "en-IE": {"tag": "en-IE", "name": "English (Ireland)", "nativeName": "English (Ireland)"},
        "en-PH": {"tag": "en-PH", "name": "English (Philippines)", "nativeName": "English (Philippines)"},
        "en-ZW": {"tag": "en-ZW", "name": "English (Zimbabwe)", "nativeName": "English (Zimbabwe)"},
        "en-BZ": {"tag": "en-BZ", "name": "English (Belize)", "nativeName": "English (Belize)"},
        "en-CB": {"tag": "en-CB", "name": "English (Caribbean)", "nativeName": "English (Caribbean)"},
        "en-JM": {"tag": "en-JM", "name": "English (Jamaica)", "nativeName": "English (Jamaica)"},
        "en-TT": {"tag": "en-TT", "name": "English (Trinidad and Tobago)", "nativeName": "English (Trinidad and Tobago)"},
        "hi-IN": {"tag": "hi-IN", "name": "Hindi (India)", "nativeName": "हिन्दी (Hindi)"},
        "es-ES": {"tag": "es-ES", "name": "Spanish (Spain)", "nativeName": "Español (España)", "default": true},
        "es-MX": {"tag": "es-MX", "name": "Spanish (Mexico)", "nativeName": "Español (México)"},
        "es-AR": {"tag": "es-AR", "name": "Spanish (Argentina)", "nativeName": "Español (Argentina)"},
        "es-CO": {"tag": "es-CO", "name": "Spanish (Colombia)", "nativeName": "Español (Colombia)"},
        "es-PE": {"tag": "es-PE", "name": "Spanish (Peru)", "nativeName": "Español (Perú)"},
        "es-VE": {"tag": "es-VE", "name": "Spanish (Venezuela)", "nativeName": "Español (Venezuela)"},
        "es-CL": {"tag": "es-CL", "name": "Spanish (Chile)", "nativeName": "Español (Chile)"},
        "es-EC": {"tag": "es-EC", "name": "Spanish (Ecuador)", "nativeName": "Español (Ecuador)"},
        "es-GT": {"tag": "es-GT", "name": "Spanish (Guatemala)", "nativeName": "Español (Guatemala)"},
        "es-CU": {"tag": "es-CU", "name": "Spanish (Cuba)", "nativeName": "Español (Cuba)"},
        "es-BO": {"tag": "es-BO", "name": "Spanish (Bolivia)", "nativeName": "Español (Bolivia)"},
        "es-DO": {"tag": "es-DO", "name": "Spanish (Dominican Republic)", "nativeName": "Español (República Dominicana)"},
        "es-HN": {"tag": "es-HN", "name": "Spanish (Honduras)", "nativeName": "Español (Honduras)"},
        "es-PY": {"tag": "es-PY", "name": "Spanish (Paraguay)", "nativeName": "Español (Paraguay)"},
        "es-SV": {"tag": "es-SV", "name": "Spanish (El Salvador)", "nativeName": "Español (El Salvador)"},
        "es-NI": {"tag": "es-NI", "name": "Spanish (Nicaragua)", "nativeName": "Español (Nicaragua)"},
        "es-PR": {"tag": "es-PR", "name": "Spanish (Puerto Rico)", "nativeName": "Español (Puerto Rico)"},
        "es-UY": {"tag": "es-UY", "name": "Spanish (Uruguay)", "nativeName": "Español (Uruguay)"},
        "es-PA": {"tag": "es-PA", "name": "Spanish (Panama)", "nativeName": "Español (Panamá)"},
        "es-CR": {"tag": "es-CR", "name": "Spanish (Costa Rica)", "nativeName": "Español (Costa Rica)"},
        "ar-EG": {"tag": "ar-EG", "name": "Arabic (Egypt)", "nativeName": "العربية (مصر)", "default": true},
        "ar-SA": {"tag": "ar-SA", "name": "Arabic (Saudi Arabia)", "nativeName": "العربية (السعودية)"},
        "ar-DZ": {"tag": "ar-DZ", "name": "Arabic (Algeria)", "nativeName": "العربية (الجزائر)"},
        "ar-MA": {"tag": "ar-MA", "name": "Arabic (Morocco)", "nativeName": "العربية (المغرب)"},
        "ar-IQ": {"tag": "ar-IQ", "name": "Arabic (Iraq)", "nativeName": "العربية (العراق)"},
        "ar-SD": {"tag": "ar-SD", "name": "Arabic (Sudan)", "nativeName": "العربية (السودان)"},
        "ar-YE": {"tag": "ar-YE", "name": "Arabic (Yemen)", "nativeName": "العربية (اليمن)"},
        "ar-SY": {"tag": "ar-SY", "name": "Arabic (Syria)", "nativeName": "العربية (سوريا)"},
        "ar-TN": {"tag": "ar-TN", "name": "Arabic (Tunisia)", "nativeName": "العربية (تونس)"},
        "ar-LY": {"tag": "ar-LY", "name": "Arabic (Libya)", "nativeName": "العربية (ليبيا)"},
        "ar-JO": {"tag": "ar-JO", "name": "Arabic (Jordan)", "nativeName": "العربية (الأردن)"},
        "ar-LB": {"tag": "ar-LB", "name": "Arabic (Lebanon)", "nativeName": "العربية (لبنان)"},
        "ar-KW": {"tag": "ar-KW", "name": "Arabic (Kuwait)", "nativeName": "العربية (الكويت)"},
        "ar-AE": {"tag": "ar-AE", "name": "Arabic (United Arab Emirates)", "nativeName": "العربية (الإمارات)"},
        "ar-BH": {"tag": "ar-BH", "name": "Arabic (Bahrain)", "nativeName": "العربية (البحرين)"},
        "ar-QA": {"tag": "ar-QA", "name": "Arabic (Qatar)", "nativeName": "العربية (قطر)"},
        "ar-OM": {"tag": "ar-OM", "name": "Arabic (Oman)", "nativeName": "العربية (عمان)"},
        "pt-BR": {"tag": "pt-BR", "name": "Portuguese (Brazil)", "nativeName": "Português (Brasil)"},
        "pt-PT": {"tag": "pt-PT", "name": "Portuguese (Portugal)", "nativeName": "Português (Portugal)", "default": true},
        "ru-RU": {"tag": "ru-RU", "name": "Russian (Russia)", "nativeName": "Русский (Россия)", "default": true},
        "ja-JP": {"tag": "ja-JP", "name": "Japanese (Japan)", "nativeName": "日本語 (日本)", "default": true},
        "de-DE": {"tag": "de-DE", "name": "German (Germany)", "nativeName": "Deutsch (Deutschland)", "default": true},
        "de-AT": {"tag": "de-AT", "name": "German (Austria)", "nativeName": "Deutsch (Österreich)"},
        "de-CH": {"tag": "de-CH", "name": "German (Switzerland)", "nativeName": "Deutsch (Schweiz)"},
        "fr-FR": {"tag": "fr-FR", "name": "French (France)", "nativeName": "Français (France)", "default": true},
        "fr-CA": {"tag": "fr-CA", "name": "French (Canada)", "nativeName": "Français (Canada)"},
        "fr-BE": {"tag": "fr-BE", "name": "French (Belgium)", "nativeName": "Français (Belgique)"},
        "fr-CH": {"tag": "fr-CH", "name": "French (Switzerland)", "nativeName": "Français (Suisse)"},
        "fr-LU": {"tag": "fr-LU", "name": "French (Luxembourg)", "nativeName": "Français (Luxembourg)"},
        "fr-MC": {"tag": "fr-MC", "name": "French (Monaco)", "nativeName": "Français (Monaco)"},
        "ko-KR": {"tag": "ko-KR", "name": "Korean (South Korea)", "nativeName": "한국어 (대한민국)"},
        "it-IT": {"tag": "it-IT", "name": "Italian (Italy)", "nativeName": "Italiano (Italia)", "default": true },
        "it-CH": {"tag": "it-CH", "name": "Italian (Switzerland)", "nativeName": "Italiano (Svizzera)"},
        "nl-NL": {"tag": "nl-NL", "name": "Dutch (Netherlands)", "nativeName": "Nederlands (Nederland)"},
        "nl-BE": {"tag": "nl-BE", "name": "Dutch (Belgium)", "nativeName": "Nederlands (België)"},
        "pl-PL": {"tag": "pl-PL", "name": "Polish (Poland)", "nativeName": "Polski (Polska)"},
        "vi-VN": {"tag": "vi-VN", "name": "Vietnamese (Vietnam)", "nativeName": "Tiếng Việt (Việt Nam)"},
        "tr-TR": {"tag": "tr-TR", "name": "Turkish (Turkey)", "nativeName": "Türkçe (Türkiye)"},
        "th-TH": {"tag": "th-TH", "name": "Thai (Thailand)", "nativeName": "ไทย (ประเทศไทย)"},
        "el-GR": {"tag": "el-GR", "name": "Greek (Greece)", "nativeName": "Ελληνικά (Ελλάδα)"},
        "cs-CZ": {"tag": "cs-CZ", "name": "Czech (Czech Republic)", "nativeName": "Čeština (Česká republika)"},
        "sv-SE": {"tag": "sv-SE", "name": "Swedish (Sweden)", "nativeName": "Svenska (Sverige)", "default": true},
        "sv-FI": {"tag": "sv-FI", "name": "Swedish (Finland)", "nativeName": "Svenska (Finland)"},
        "hu-HU": {"tag": "hu-HU", "name": "Hungarian (Hungary)", "nativeName": "Magyar (Magyarország)"},
        "fi-FI": {"tag": "fi-FI", "name": "Finnish (Finland)", "nativeName": "Suomi (Suomi)"},
        "da-DK": {"tag": "da-DK", "name": "Danish (Denmark)", "nativeName": "Dansk (Danmark)"},
        "nb-NO": {"tag": "nb-NO", "name": "Norwegian Bokmål (Norway)", "nativeName": "Norsk Bokmål (Norge)"},
        "nn-NO": {"tag": "nn-NO", "name": "Norwegian Nynorsk (Norway)", "nativeName": "Norsk Nynorsk (Norge)"},
        "he-IL": {"tag": "he-IL", "name": "Hebrew (Israel)", "nativeName": "עברית (ישראל)"},
        "id-ID": {"tag": "id-ID", "name": "Indonesian (Indonesia)", "nativeName": "Bahasa Indonesia (Indonesia)"},
        "ms-MY": {"tag": "ms-MY", "name": "Malay (Malaysia)", "nativeName": "Bahasa Melayu (Malaysia)"},
        "ms-BN": {"tag": "ms-BN", "name": "Malay (Brunei)", "nativeName": "Bahasa Melayu (Brunei)"},
        "ro-RO": {"tag": "ro-RO", "name": "Romanian (Romania)", "nativeName": "Română (România)"},
        "bg-BG": {"tag": "bg-BG", "name": "Bulgarian (Bulgaria)", "nativeName": "Български (България)"},
        "uk-UA": {"tag": "uk-UA", "name": "Ukrainian (Ukraine)", "nativeName": "Українська (Україна)"},
        "sk-SK": {"tag": "sk-SK", "name": "Slovak (Slovakia)", "nativeName": "Slovenčina (Slovensko)"},
        "sl-SI": {"tag": "sl-SI", "name": "Slovene (Slovenia)", "nativeName": "Slovenščina (Slovenija)"},
        "hr-HR": {"tag": "hr-HR", "name": "Croatian (Croatia)", "nativeName": "Hrvatski (Hrvatska)"},
        "ca-ES": {"tag": "ca-ES", "name": "Catalan (Catalonia)", "nativeName": "Català (Catalunya)"},
        "lt-LT": {"tag": "lt-LT", "name": "Lithuanian (Lithuania)", "nativeName": "Lietuvių (Lietuva)"},
        "lv-LV": {"tag": "lv-LV", "name": "Latvian (Latvia)", "nativeName": "Latviešu (Latvija)"},
        "et-EE": {"tag": "et-EE", "name": "Estonian (Estonia)", "nativeName": "Eesti (Eesti)"},
        "sq-AL": {"tag": "sq-AL", "name": "Albanian (Albania)", "nativeName": "Shqip (Shqipëri)"},
        "mk-MK": {"tag": "mk-MK", "name": "Macedonian (North Macedonia)", "nativeName": "Македонски (Македонија)"},
        "be-BY": {"tag": "be-BY", "name": "Belarusian (Belarus)", "nativeName": "Беларуская (Беларусь)"},
        "is-IS": {"tag": "is-IS", "name": "Icelandic (Iceland)", "nativeName": "Íslenska (Ísland)"},
        "gl-ES": {"tag": "gl-ES", "name": "Galician (Galicia)", "nativeName": "Galego (Galicia)"},
        "eu-ES": {"tag": "eu-ES", "name": "Basque (Basque Country)", "nativeName": "Euskara (Euskal Herria)"},
        "af-ZA": {"tag": "af-ZA", "name": "Afrikaans (South Africa)", "nativeName": "Afrikaans (Suid-Afrika)"},
        "sw-KE": {"tag": "sw-KE", "name": "Swahili (Kenya)", "nativeName": "Kiswahili (Kenya)"},
        "ta-IN": {"tag": "ta-IN", "name": "Tamil (India)", "nativeName": "தமிழ் (இந்தியா)"},
        "te-IN": {"tag": "te-IN", "name": "Telugu (India)", "nativeName": "తెలుగు (భారతదేశం)"},
        "kn-IN": {"tag": "kn-IN", "name": "Kannada (India)", "nativeName": "ಕನ್ನಡ (ಭಾರತ)"},
        "mr-IN": {"tag": "mr-IN", "name": "Marathi (India)", "nativeName": "मराठी (भारत)"},
        "gu-IN": {"tag": "gu-IN", "name": "Gujarati (India)", "nativeName": "ગુજરાતી (ભારત)"},
        "pa-IN": {"tag": "pa-IN", "name": "Punjabi (India)", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)"},
        "kok-IN": {"tag": "kok-IN", "name": "Konkani (India)", "nativeName": "कोंकणी (भारत)"},
        "sa-IN": {"tag": "sa-IN", "name": "Sanskrit (India)", "nativeName": "संस्कृत (भारत)"},
        "ur-PK": {"tag": "ur-PK", "name": "Urdu (Pakistan)", "nativeName": "اردو (پاکستان)"},
        "fa-IR": {"tag": "fa-IR", "name": "Persian (Iran)", "nativeName": "فارسی (ایران)"},
        "syr-SY": {"tag": "syr-SY", "name": "Syriac (Syria)", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)"},
        "div-MV": {"tag": "div-MV", "name": "Dhivehi (Maldives)", "nativeName": "ދިވެހި (މޯލްޑިވްސް)"},
        "ka-GE": {"tag": "ka-GE", "name": "Georgian (Georgia)", "nativeName": "ქართული (საქართველო)"},      
}


const { getTag, getTags, getDefaultTags } = createTagUtils(tags)
export {
    getTag, getTags,getDefaultTags
}
export * from './types'    