import { createTagUtils } from './utils'

export const tags = {
        "zh-CN": {"tag": "zh-CN", "name": "Chino Simplificado", "nativeName": "简体中文", "default": true},
        "zh-TW": {"tag": "zh-TW", "name": "Chino Tradicional (Taiwán)", "nativeName": "繁體中文 (臺灣)"},
        "zh-HK": {"tag": "zh-HK", "name": "Chino Tradicional (Hong Kong)", "nativeName": "繁體中文（香港）"},
        "zh-MO": {"tag": "zh-MO", "name": "Chino Tradicional (Macao)", "nativeName": "繁體中文 (Traditional Chinese - Macau)"},
        "zh-SG": {"tag": "zh-SG", "name": "Chino Simplificado (Singapur)", "nativeName": "简体中文 (Simplified Chinese - Singapore)"},      
        "zh-CHS": {"tag": "zh-CHS", "name": "Chino Simplificado", "nativeName": "简体中文"},
        "zh-CHT": {"tag": "zh-CHT", "name": "Chino Tradicional", "nativeName": "繁體中文 (Traditional Chinese)"},
        "en-US": {"tag": "en-US", "name": "Inglés (Estados Unidos)", "nativeName": "English (United States)", "default": true},
        "en-GB": {"tag": "en-GB", "name": "Inglés (Reino Unido)", "nativeName": "English (United Kingdom)"},
        "en-CA": {"tag": "en-CA", "name": "Inglés (Canadá)", "nativeName": "English (Canada)"},
        "en-AU": {"tag": "en-AU", "name": "Inglés (Australia)", "nativeName": "English (Australia)"},
        "en-IN": {"tag": "en-IN", "name": "Inglés (India)", "nativeName": "English (India)"},
        "en-ZA": {"tag": "en-ZA", "name": "Inglés (Sudáfrica)", "nativeName": "English (South Africa)"},
        "en-NZ": {"tag": "en-NZ", "name": "Inglés (Nueva Zelanda)", "nativeName": "English (New Zealand)"},
        "en-IE": {"tag": "en-IE", "name": "Inglés (Irlanda)", "nativeName": "English (Ireland)"},
        "en-PH": {"tag": "en-PH", "name": "Inglés (Filipinas)", "nativeName": "English (Philippines)"},
        "en-ZW": {"tag": "en-ZW", "name": "Inglés (Zimbabue)", "nativeName": "English (Zimbabwe)"},
        "en-BZ": {"tag": "en-BZ", "name": "Inglés (Belice)", "nativeName": "English (Belize)"},
        "en-CB": {"tag": "en-CB", "name": "Inglés (Caribe)", "nativeName": "English (Caribbean)"},
        "en-JM": {"tag": "en-JM", "name": "Inglés (Jamaica)", "nativeName": "English (Jamaica)"},
        "en-TT": {"tag": "en-TT", "name": "Inglés (Trinidad y Tobago)", "nativeName": "English (Trinidad and Tobago)"},
        "hi-IN": {"tag": "hi-IN", "name": "Hindi (India)", "nativeName": "हिन्दी (Hindi)"},
        "es-ES": {"tag": "es-ES", "name": "Español (España)", "nativeName": "Español (España)", "default": true},
        "es-MX": {"tag": "es-MX", "name": "Español (México)", "nativeName": "Español (México)"},
        "es-AR": {"tag": "es-AR", "name": "Español (Argentina)", "nativeName": "Español (Argentina)"},
        "es-CO": {"tag": "es-CO", "name": "Español (Colombia)", "nativeName": "Español (Colombia)"},
        "es-PE": {"tag": "es-PE", "name": "Español (Perú)", "nativeName": "Español (Perú)"},
        "es-VE": {"tag": "es-VE", "name": "Español (Venezuela)", "nativeName": "Español (Venezuela)"},
        "es-CL": {"tag": "es-CL", "name": "Español (Chile)", "nativeName": "Español (Chile)"},
        "es-EC": {"tag": "es-EC", "name": "Español (Ecuador)", "nativeName": "Español (Ecuador)"},
        "es-GT": {"tag": "es-GT", "name": "Español (Guatemala)", "nativeName": "Español (Guatemala)"},
        "es-CU": {"tag": "es-CU", "name": "Español (Cuba)", "nativeName": "Español (Cuba)"},
        "es-BO": {"tag": "es-BO", "name": "Español (Bolivia)", "nativeName": "Español (Bolivia)"},
        "es-DO": {"tag": "es-DO", "name": "Español (República Dominicana)", "nativeName": "Español (República Dominicana)"},
        "es-HN": {"tag": "es-HN", "name": "Español (Honduras)", "nativeName": "Español (Honduras)"},
        "es-PY": {"tag": "es-PY", "name": "Español (Paraguay)", "nativeName": "Español (Paraguay)"},
        "es-SV": {"tag": "es-SV", "name": "Español (El Salvador)", "nativeName": "Español (El Salvador)"},
        "es-NI": {"tag": "es-NI", "name": "Español (Nicaragua)", "nativeName": "Español (Nicaragua)"},
        "es-PR": {"tag": "es-PR", "name": "Español (Puerto Rico)", "nativeName": "Español (Puerto Rico)"},
        "es-UY": {"tag": "es-UY", "name": "Español (Uruguay)", "nativeName": "Español (Uruguay)"},
        "es-PA": {"tag": "es-PA", "name": "Español (Panamá)", "nativeName": "Español (Panamá)"},
        "es-CR": {"tag": "es-CR", "name": "Español (Costa Rica)", "nativeName": "Español (Costa Rica)"},
        "ar-EG": {"tag": "ar-EG", "name": "Árabe (Egipto)", "nativeName": "العربية (مصر)", "default": true},
        "ar-SA": {"tag": "ar-SA", "name": "Árabe (Arabia Saudita)", "nativeName": "العربية (السعودية)"},
        "ar-DZ": {"tag": "ar-DZ", "name": "Árabe (Argelia)", "nativeName": "العربية (الجزائر)"},
        "ar-MA": {"tag": "ar-MA", "name": "Árabe (Marruecos)", "nativeName": "العربية (المغرب)"},
        "ar-IQ": {"tag": "ar-IQ", "name": "Árabe (Irak)", "nativeName": "العربية (العراق)"},
        "ar-SD": {"tag": "ar-SD", "name": "Árabe (Sudán)", "nativeName": "العربية (السودان)"},
        "ar-YE": {"tag": "ar-YE", "name": "Árabe (Yemen)", "nativeName": "العربية (اليمن)"},
        "ar-SY": {"tag": "ar-SY", "name": "Árabe (Siria)", "nativeName": "العربية (سوريا)"},
        "ar-TN": {"tag": "ar-TN", "name": "Árabe (Túnez)", "nativeName": "العربية (تونس)"},
        "ar-LY": {"tag": "ar-LY", "name": "Árabe (Libia)", "nativeName": "العربية (ليبيا)"},
        "ar-JO": {"tag": "ar-JO", "name": "Árabe (Jordania)", "nativeName": "العربية (الأردن)"},
        "ar-LB": {"tag": "ar-LB", "name": "Árabe (Líbano)", "nativeName": "العربية (لبنان)"},
        "ar-KW": {"tag": "ar-KW", "name": "Árabe (Kuwait)", "nativeName": "العربية (الكويت)"},
        "ar-AE": {"tag": "ar-AE", "name": "Árabe (Emiratos Árabes Unidos)", "nativeName": "العربية (الإمارات)"},
        "ar-BH": {"tag": "ar-BH", "name": "Árabe (Baréin)", "nativeName": "العربية (البحرين)"},
        "ar-QA": {"tag": "ar-QA", "name": "Árabe (Catar)", "nativeName": "العربية (قطر)"},
        "ar-OM": {"tag": "ar-OM", "name": "Árabe (Omán)", "nativeName": "العربية (عمان)"},
        "pt-BR": {"tag": "pt-BR", "name": "Portugués (Brasil)", "nativeName": "Português (Brasil)"},
        "pt-PT": {"tag": "pt-PT", "name": "Portugués (Portugal)", "nativeName": "Português (Portugal)", "default": true},
        "ru-RU": {"tag": "ru-RU", "name": "Ruso (Rusia)", "nativeName": "Русский (Россия)", "default": true},
        "ja-JP": {"tag": "ja-JP", "name": "Japonés (Japón)", "nativeName": "日本語 (日本)", "default": true},
        "de-DE": {"tag": "de-DE", "name": "Alemán (Alemania)", "nativeName": "Deutsch (Deutschland)", "default": true},
        "de-AT": {"tag": "de-AT", "name": "Alemán (Austria)", "nativeName": "Deutsch (Österreich)"},
        "de-CH": {"tag": "de-CH", "name": "Alemán (Suiza)", "nativeName": "Deutsch (Schweiz)"},
        "fr-FR": {"tag": "fr-FR", "name": "Francés (Francia)", "nativeName": "Français (France)", "default": true},
        "fr-CA": {"tag": "fr-CA", "name": "Francés (Canadá)", "nativeName": "Français (Canada)"},
        "fr-BE": {"tag": "fr-BE", "name": "Francés (Bélgica)", "nativeName": "Français (Belgique)"},
        "fr-CH": {"tag": "fr-CH", "name": "Francés (Suiza)", "nativeName": "Français (Suisse)"},
        "fr-LU": {"tag": "fr-LU", "name": "Francés (Luxemburgo)", "nativeName": "Français (Luxembourg)"},
        "fr-MC": {"tag": "fr-MC", "name": "Francés (Mónaco)", "nativeName": "Français (Monaco)"},
        "ko-KR": {"tag": "ko-KR", "name": "Coreano (Corea del Sur)", "nativeName": "한국어 (대한민국)"},
        "it-IT": {"tag": "it-IT", "name": "Italiano (Italia)", "nativeName": "Italiano (Italia)", "default": true },
        "it-CH": {"tag": "it-CH", "name": "Italiano (Suiza)", "nativeName": "Italiano (Svizzera)"},
        "nl-NL": {"tag": "nl-NL", "name": "Neerlandés (Países Bajos)", "nativeName": "Nederlands (Nederland)"},
        "nl-BE": {"tag": "nl-BE", "name": "Neerlandés (Bélgica)", "nativeName": "Nederlands (België)"},
        "pl-PL": {"tag": "pl-PL", "name": "Polaco (Polonia)", "nativeName": "Polski (Polska)"},
        "vi-VN": {"tag": "vi-VN", "name": "Vietnamita (Vietnam)", "nativeName": "Tiếng Việt (Việt Nam)"},
        "tr-TR": {"tag": "tr-TR", "name": "Turco (Turquía)", "nativeName": "Türkçe (Türkiye)"},
        "th-TH": {"tag": "th-TH", "name": "Tailandés (Tailandia)", "nativeName": "ไทย (ประเทศไทย)"},
        "el-GR": {"tag": "el-GR", "name": "Griego (Grecia)", "nativeName": "Ελληνικά (Ελλάδα)"},
        "cs-CZ": {"tag": "cs-CZ", "name": "Checo (República Checa)", "nativeName": "Čeština (Česká republika)"},
        "sv-SE": {"tag": "sv-SE", "name": "Sueco (Suecia)", "nativeName": "Svenska (Sverige)", "default": true},
        "sv-FI": {"tag": "sv-FI", "name": "Sueco (Finlandia)", "nativeName": "Svenska (Finland)"},
        "hu-HU": {"tag": "hu-HU", "name": "Húngaro (Hungría)", "nativeName": "Magyar (Magyarország)"},
        "fi-FI": {"tag": "fi-FI", "name": "Finés (Finlandia)", "nativeName": "Suomi (Suomi)"},
        "da-DK": {"tag": "da-DK", "name": "Danés (Dinamarca)", "nativeName": "Dansk (Danmark)"},
        "nb-NO": {"tag": "nb-NO", "name": "Noruego Bokmål (Noruega)", "nativeName": "Norsk Bokmål (Norge)"},
        "nn-NO": {"tag": "nn-NO", "name": "Noruego Nynorsk (Noruega)", "nativeName": "Norsk Nynorsk (Norge)"},
        "he-IL": {"tag": "he-IL", "name": "Hebreo (Israel)", "nativeName": "עברית (ישראל)"},
        "id-ID": {"tag": "id-ID", "name": "Indonesio (Indonesia)", "nativeName": "Bahasa Indonesia (Indonesia)"},
        "ms-MY": {"tag": "ms-MY", "name": "Malayo (Malasia)", "nativeName": "Bahasa Melayu (Malaysia)"},
        "ms-BN": {"tag": "ms-BN", "name": "Malayo (Brunéi)", "nativeName": "Bahasa Melayu (Brunei)"},
        "ro-RO": {"tag": "ro-RO", "name": "Rumano (Rumanía)", "nativeName": "Română (România)"},
        "bg-BG": {"tag": "bg-BG", "name": "Búlgaro (Bulgaria)", "nativeName": "Български (България)"},
        "uk-UA": {"tag": "uk-UA", "name": "Ucraniano (Ucrania)", "nativeName": "Українська (Україна)"},
        "sk-SK": {"tag": "sk-SK", "name": "Eslovaco (Eslovaquia)", "nativeName": "Slovenčina (Slovensko)"},
        "sl-SI": {"tag": "sl-SI", "name": "Esloveno (Eslovenia)", "nativeName": "Slovenščina (Slovenija)"},
        "hr-HR": {"tag": "hr-HR", "name": "Croata (Croacia)", "nativeName": "Hrvatski (Hrvatska)"},
        "ca-ES": {"tag": "ca-ES", "name": "Catalán (Cataluña)", "nativeName": "Català (Catalunya)"},
        "lt-LT": {"tag": "lt-LT", "name": "Lituano (Lituania)", "nativeName": "Lietuvių (Lietuva)"},
        "lv-LV": {"tag": "lv-LV", "name": "Letón (Letonia)", "nativeName": "Latviešu (Latvija)"},
        "et-EE": {"tag": "et-EE", "name": "Estonio (Estonia)", "nativeName": "Eesti (Eesti)"},
        "sq-AL": {"tag": "sq-AL", "name": "Albanés (Albania)", "nativeName": "Shqip (Shqipëri)"},        
        "mk-MK": {"tag": "mk-MK", "name": "Macedonio (Macedonia del Norte)", "nativeName": "Македонски (Македонија)"},
        "be-BY": {"tag": "be-BY", "name": "Bielorruso (Bielorrusia)", "nativeName": "Беларуская (Беларусь)"},
        "is-IS": {"tag": "is-IS", "name": "Islandés (Islandia)", "nativeName": "Íslenska (Ísland)"},
        "gl-ES": {"tag": "gl-ES", "name": "Gallego (Galicia)", "nativeName": "Galego (Galicia)"},
        "eu-ES": {"tag": "eu-ES", "name": "Vasco (País Vasco)", "nativeName": "Euskara (Euskal Herria)"},
        "af-ZA": {"tag": "af-ZA", "name": "Afrikáans (Sudáfrica)", "nativeName": "Afrikaans (Suid-Afrika)"},
        "sw-KE": {"tag": "sw-KE", "name": "Suajili (Kenia)", "nativeName": "Kiswahili (Kenya)"},
        "ta-IN": {"tag": "ta-IN", "name": "Tamil (India)", "nativeName": "தமிழ் (இந்தியா)"},
        "te-IN": {"tag": "te-IN", "name": "Telugu (India)", "nativeName": "తెలుగు (భారతదేశం)"},
        "kn-IN": {"tag": "kn-IN", "name": "Canarés (India)", "nativeName": "ಕನ್ನಡ (ಭಾರತ)"},
        "mr-IN": {"tag": "mr-IN", "name": "Maratí (India)", "nativeName": "मराठी (भारत)"},
        "gu-IN": {"tag": "gu-IN", "name": "Guyaratí (India)", "nativeName": "ગુજરાતી (ભારત)"},
        "pa-IN": {"tag": "pa-IN", "name": "Panyabí (India)", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)"},
        "kok-IN": {"tag": "kok-IN", "name": "Konkaní (India)", "nativeName": "कोंकणी (भारत)"},
        "sa-IN": {"tag": "sa-IN", "name": "Sánscrito (India)", "nativeName": "संस्कृत (भारत)"},
        "ur-PK": {"tag": "ur-PK", "name": "Urdu (Pakistán)", "nativeName": "اردو (پاکستان)"},
        "fa-IR": {"tag": "fa-IR", "name": "Persa (Irán)", "nativeName": "فارسی (ایران)"},
        "syr-SY": {"tag": "syr-SY", "name": "Siríaco (Siria)", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)"},
        "div-MV": {"tag": "div-MV", "name": "Dhivehi (Maldivas)", "nativeName": "ދިވެހި (މޯލްޑިވްސް)"},
        "ka-GE": {"tag": "ka-GE", "name": "Georgiano (Georgia)", "nativeName": "ქართული (საქართველო)"},      
}

const { getTag, getTags, getDefaultTags } = createTagUtils(tags)
export {
    getTag, getTags,getDefaultTags
}
export * from './types'    