import { createTagUtils } from './utils'

export const tags = {
        "zh-CN": {"tag": "zh-CN", "name": "Chino Simplificado", "nativeName": "简体中文", "primary": true},
        "zh-TW": {"tag": "zh-TW", "name": "Chino Tradicional (Taiwán)", "nativeName": "繁體中文(臺灣)", "primary": false},
        "zh-HK": {"tag": "zh-HK", "name": "Chino Tradicional (Hong Kong)", "nativeName": "繁體中文(香港)", "primary": false},
        "zh-MO": {"tag": "zh-MO", "name": "Chino Tradicional (Macao)", "nativeName": "繁體中文(Traditional Chinese - Macau)", "primary": false},
        "zh-SG": {"tag": "zh-SG", "name": "Chino Simplificado (Singapur)", "nativeName": "简体中文(Simplified Chinese - Singapore)", "primary": false},      
        "zh-CHS": {"tag": "zh-CHS", "name": "Chino Simplificado", "nativeName": "简体中文", "primary": false},
        "zh-CHT": {"tag": "zh-CHT", "name": "Chino Tradicional", "nativeName": "繁體中文(Traditional Chinese)", "primary": false},
        "en-US": {"tag": "en-US", "name": "Inglés (Estados Unidos)", "nativeName": "English (United States)", "primary": true },
        "en-GB": {"tag": "en-GB", "name": "Inglés (Reino Unido)", "nativeName": "English (United Kingdom)", "primary": false},
        "en-CA": {"tag": "en-CA", "name": "Inglés (Canadá)", "nativeName": "English (Canada)", "primary": false},
        "en-AU": {"tag": "en-AU", "name": "Inglés (Australia)", "nativeName": "English (Australia)", "primary": false},
        "en-IN": {"tag": "en-IN", "name": "Inglés (India)", "nativeName": "English (India)", "primary": false},
        "en-ZA": {"tag": "en-ZA", "name": "Inglés (Sudáfrica)", "nativeName": "English (South Africa)", "primary": false},
        "en-NZ": {"tag": "en-NZ", "name": "Inglés (Nueva Zelanda)", "nativeName": "English (New Zealand)", "primary": false},
        "en-IE": {"tag": "en-IE", "name": "Inglés (Irlanda)", "nativeName": "English (Ireland)", "primary": false},
        "en-PH": {"tag": "en-PH", "name": "Inglés (Filipinas)", "nativeName": "English (Philippines)", "primary": false},
        "en-ZW": {"tag": "en-ZW", "name": "Inglés (Zimbabue)", "nativeName": "English (Zimbabwe)", "primary": false},
        "en-BZ": {"tag": "en-BZ", "name": "Inglés (Belice)", "nativeName": "English (Belize)", "primary": false},
        "en-CB": {"tag": "en-CB", "name": "Inglés (Caribe)", "nativeName": "English (Caribbean)", "primary": false},
        "en-JM": {"tag": "en-JM", "name": "Inglés (Jamaica)", "nativeName": "English (Jamaica)", "primary": false},
        "en-TT": {"tag": "en-TT", "name": "Inglés (Trinidad y Tobago)", "nativeName": "English (Trinidad and Tobago)", "primary": false},
        "hi-IN": {"tag": "hi-IN", "name": "Hindi (India)", "nativeName": "हिन्दी (Hindi)", "primary": false},
        "es-ES": {"tag": "es-ES", "name": "Español (España)", "nativeName": "Español (España)", "primary": true},
        "es-MX": {"tag": "es-MX", "name": "Español (México)", "nativeName": "Español (México)", "primary": false},
        "es-AR": {"tag": "es-AR", "name": "Español (Argentina)", "nativeName": "Español (Argentina)", "primary": false},
        "es-CO": {"tag": "es-CO", "name": "Español (Colombia)", "nativeName": "Español (Colombia)", "primary": false},
        "es-PE": {"tag": "es-PE", "name": "Español (Perú)", "nativeName": "Español (Perú)", "primary": false},
        "es-VE": {"tag": "es-VE", "name": "Español (Venezuela)", "nativeName": "Español (Venezuela)", "primary": false},
        "es-CL": {"tag": "es-CL", "name": "Español (Chile)", "nativeName": "Español (Chile)", "primary": false},
        "es-EC": {"tag": "es-EC", "name": "Español (Ecuador)", "nativeName": "Español (Ecuador)", "primary": false},
        "es-GT": {"tag": "es-GT", "name": "Español (Guatemala)", "nativeName": "Español (Guatemala)", "primary": false},
        "es-CU": {"tag": "es-CU", "name": "Español (Cuba)", "nativeName": "Español (Cuba)", "primary": false},
        "es-BO": {"tag": "es-BO", "name": "Español (Bolivia)", "nativeName": "Español (Bolivia)", "primary": false},
        "es-DO": {"tag": "es-DO", "name": "Español (República Dominicana)", "nativeName": "Español (República Dominicana)", "primary": false},
        "es-HN": {"tag": "es-HN", "name": "Español (Honduras)", "nativeName": "Español (Honduras)", "primary": false},
        "es-PY": {"tag": "es-PY", "name": "Español (Paraguay)", "nativeName": "Español (Paraguay)", "primary": false},
        "es-SV": {"tag": "es-SV", "name": "Español (El Salvador)", "nativeName": "Español (El Salvador)", "primary": false},
        "es-NI": {"tag": "es-NI", "name": "Español (Nicaragua)", "nativeName": "Español (Nicaragua)", "primary": false},
        "es-PR": {"tag": "es-PR", "name": "Español (Puerto Rico)", "nativeName": "Español (Puerto Rico)", "primary": false},
        "es-UY": {"tag": "es-UY", "name": "Español (Uruguay)", "nativeName": "Español (Uruguay)", "primary": false},
        "es-PA": {"tag": "es-PA", "name": "Español (Panamá)", "nativeName": "Español (Panamá)", "primary": false},
        "es-CR": {"tag": "es-CR", "name": "Español (Costa Rica)", "nativeName": "Español (Costa Rica)", "primary": false},
        "ar-EG": {"tag": "ar-EG", "name": "Árabe (Egipto)", "nativeName": "العربية (مصر)", "primary": true},
        "ar-SA": {"tag": "ar-SA", "name": "Árabe (Arabia Saudita)", "nativeName": "العربية (السعودية)", "primary": false},
        "ar-DZ": {"tag": "ar-DZ", "name": "Árabe (Argelia)", "nativeName": "العربية (الجزائر)", "primary": false},
        "ar-MA": {"tag": "ar-MA", "name": "Árabe (Marruecos)", "nativeName": "العربية (المغرب)", "primary": false},
        "ar-IQ": {"tag": "ar-IQ", "name": "Árabe (Irak)", "nativeName": "العربية (العراق)", "primary": false},
        "ar-SD": {"tag": "ar-SD", "name": "Árabe (Sudán)", "nativeName": "العربية (السودان)", "primary": false},
        "ar-YE": {"tag": "ar-YE", "name": "Árabe (Yemen)", "nativeName": "العربية (اليمن)", "primary": false},
        "ar-SY": {"tag": "ar-SY", "name": "Árabe (Siria)", "nativeName": "العربية (سوريا)", "primary": false},
        "ar-TN": {"tag": "ar-TN", "name": "Árabe (Túnez)", "nativeName": "العربية (تونس)", "primary": false},
        "ar-LY": {"tag": "ar-LY", "name": "Árabe (Libia)", "nativeName": "العربية (ليبيا)", "primary": false},
        "ar-JO": {"tag": "ar-JO", "name": "Árabe (Jordania)", "nativeName": "العربية (الأردن)", "primary": false},
        "ar-LB": {"tag": "ar-LB", "name": "Árabe (Líbano)", "nativeName": "العربية (لبنان)", "primary": false},
        "ar-KW": {"tag": "ar-KW", "name": "Árabe (Kuwait)", "nativeName": "العربية (الكويت)", "primary": false},
        "ar-AE": {"tag": "ar-AE", "name": "Árabe (Emiratos Árabes Unidos)", "nativeName": "العربية (الإمارات)", "primary": false},
        "ar-BH": {"tag": "ar-BH", "name": "Árabe (Baréin)", "nativeName": "العربية (البحرين)", "primary": false},
        "ar-QA": {"tag": "ar-QA", "name": "Árabe (Catar)", "nativeName": "العربية (قطر)", "primary": false},
        "ar-OM": {"tag": "ar-OM", "name": "Árabe (Omán)", "nativeName": "العربية (عمان)", "primary": false},
        "pt-BR": {"tag": "pt-BR", "name": "Portugués (Brasil)", "nativeName": "Português (Brasil)", "primary": false},
        "pt-PT": {"tag": "pt-PT", "name": "Portugués (Portugal)", "nativeName": "Português (Portugal)", "primary": true},
        "ru-RU": {"tag": "ru-RU", "name": "Ruso (Rusia)", "nativeName": "Русский (Россия)", "primary": true},
        "ja-JP": {"tag": "ja-JP", "name": "Japonés (Japón)", "nativeName": "日本語 (日本)", "primary": true},
        "de-DE": {"tag": "de-DE", "name": "Alemán (Alemania)", "nativeName": "Deutsch (Deutschland)", "primary": true},
        "de-AT": {"tag": "de-AT", "name": "Alemán (Austria)", "nativeName": "Deutsch (Österreich)", "primary": false},
        "de-CH": {"tag": "de-CH", "name": "Alemán (Suiza)", "nativeName": "Deutsch (Schweiz)", "primary": false},
        "fr-FR": {"tag": "fr-FR", "name": "Francés (Francia)", "nativeName": "Français (France)", "primary": true},
        "fr-CA": {"tag": "fr-CA", "name": "Francés (Canadá)", "nativeName": "Français (Canada)", "primary": false},
        "fr-BE": {"tag": "fr-BE", "name": "Francés (Bélgica)", "nativeName": "Français (Belgique)", "primary": false},
        "fr-CH": {"tag": "fr-CH", "name": "Francés (Suiza)", "nativeName": "Français (Suisse)", "primary": false},
        "fr-LU": {"tag": "fr-LU", "name": "Francés (Luxemburgo)", "nativeName": "Français (Luxembourg)", "primary": false},
        "fr-MC": {"tag": "fr-MC", "name": "Francés (Mónaco)", "nativeName": "Français (Monaco)", "primary": false},
        "ko-KR": {"tag": "ko-KR", "name": "Coreano (Corea del Sur)", "nativeName": "한국어 (대한민국)", "primary": true },
        "it-IT": {"tag": "it-IT", "name": "Italiano (Italia)", "nativeName": "Italiano (Italia)", "primary": true},
        "it-CH": {"tag": "it-CH", "name": "Italiano (Suiza)", "nativeName": "Italiano (Svizzera)", "primary": false},
        "nl-NL": {"tag": "nl-NL", "name": "Neerlandés (Países Bajos)", "nativeName": "Nederlands (Nederland)", "primary": true},
        "nl-BE": {"tag": "nl-BE", "name": "Neerlandés (Bélgica)", "nativeName": "Nederlands (België)", "primary": false},
        "pl-PL": {"tag": "pl-PL", "name": "Polaco (Polonia)", "nativeName": "Polski (Polska)", "primary": false},
        "vi-VN": {"tag": "vi-VN", "name": "Vietnamita (Vietnam)", "nativeName": "Tiếng Việt (Việt Nam)", "primary": false},
        "tr-TR": {"tag": "tr-TR", "name": "Turco (Turquía)", "nativeName": "Türkçe (Türkiye)", "primary": false},
        "th-TH": {"tag": "th-TH", "name": "Tailandés (Tailandia)", "nativeName": "ไทย (ประเทศไทย)", "primary": false},
        "el-GR": {"tag": "el-GR", "name": "Griego (Grecia)", "nativeName": "Ελληνικά (Ελλάδα)", "primary": false},
        "cs-CZ": {"tag": "cs-CZ", "name": "Checo (República Checa)", "nativeName": "Čeština (Česká republika)", "primary": false},
        "sv-SE": {"tag": "sv-SE", "name": "Sueco (Suecia)", "nativeName": "Svenska (Sverige)", "primary": false},
        "sv-FI": {"tag": "sv-FI", "name": "Sueco (Finlandia)", "nativeName": "Svenska (Finland)", "primary": false},
        "hu-HU": {"tag": "hu-HU", "name": "Húngaro (Hungría)", "nativeName": "Magyar (Magyarország)", "primary": false},
        "fi-FI": {"tag": "fi-FI", "name": "Finés (Finlandia)", "nativeName": "Suomi (Suomi)", "primary": false},
        "da-DK": {"tag": "da-DK", "name": "Danés (Dinamarca)", "nativeName": "Dansk (Danmark)", "primary": false},
        "nb-NO": {"tag": "nb-NO", "name": "Noruego Bokmål (Noruega)", "nativeName": "Norsk Bokmål (Norge)", "primary": false},
        "nn-NO": {"tag": "nn-NO", "name": "Noruego Nynorsk (Noruega)", "nativeName": "Norsk Nynorsk (Norge)", "primary": false},
        "he-IL": {"tag": "he-IL", "name": "Hebreo (Israel)", "nativeName": "עברית (ישראל)", "primary": false},
        "id-ID": {"tag": "id-ID", "name": "Indonesio (Indonesia)", "nativeName": "Bahasa Indonesia (Indonesia)", "primary": false},
        "ms-MY": {"tag": "ms-MY", "name": "Malayo (Malasia)", "nativeName": "Bahasa Melayu (Malaysia)", "primary": false},
        "ms-BN": {"tag": "ms-BN", "name": "Malayo (Brunéi)", "nativeName": "Bahasa Melayu (Brunei)", "primary": false},
        "ro-RO": {"tag": "ro-RO", "name": "Rumano (Rumanía)", "nativeName": "Română (România)", "primary": false},
        "bg-BG": {"tag": "bg-BG", "name": "Búlgaro (Bulgaria)", "nativeName": "Български (България)", "primary": false},
        "uk-UA": {"tag": "uk-UA", "name": "Ucraniano (Ucrania)", "nativeName": "Українська (Україна)", "primary": false},
        "sk-SK": {"tag": "sk-SK", "name": "Eslovaco (Eslovaquia)", "nativeName": "Slovenčina (Slovensko)", "primary": false},
        "sl-SI": {"tag": "sl-SI", "name": "Esloveno (Eslovenia)", "nativeName": "Slovenščina (Slovenija)", "primary": false},
        "hr-HR": {"tag": "hr-HR", "name": "Croata (Croacia)", "nativeName": "Hrvatski (Hrvatska)", "primary": false},
        "ca-ES": {"tag": "ca-ES", "name": "Catalán (Cataluña)", "nativeName": "Català (Catalunya)", "primary": false},
        "lt-LT": {"tag": "lt-LT", "name": "Lituano (Lituania)", "nativeName": "Lietuvių (Lietuva)", "primary": false},
        "lv-LV": {"tag": "lv-LV", "name": "Letón (Letonia)", "nativeName": "Latviešu (Latvija)", "primary": false},
        "et-EE": {"tag": "et-EE", "name": "Estonio (Estonia)", "nativeName": "Eesti (Eesti)", "primary": false},
        "sq-AL": {"tag": "sq-AL", "name": "Albanés (Albania)", "nativeName": "Shqip (Shqipëri)", "primary": false},        
        "mk-MK": {"tag": "mk-MK", "name": "Macedonio (Macedonia del Norte)", "nativeName": "Македонски (Македонија)", "primary": false},
        "be-BY": {"tag": "be-BY", "name": "Bielorruso (Bielorrusia)", "nativeName": "Беларуская (Беларусь)", "primary": false},
        "is-IS": {"tag": "is-IS", "name": "Islandés (Islandia)", "nativeName": "Íslenska (Ísland)", "primary": false},
        "gl-ES": {"tag": "gl-ES", "name": "Gallego (Galicia)", "nativeName": "Galego (Galicia)", "primary": false},
        "eu-ES": {"tag": "eu-ES", "name": "Vasco (País Vasco)", "nativeName": "Euskara (Euskal Herria)", "primary": false},
        "af-ZA": {"tag": "af-ZA", "name": "Afrikáans (Sudáfrica)", "nativeName": "Afrikaans (Suid-Afrika)", "primary": false},
        "sw-KE": {"tag": "sw-KE", "name": "Suajili (Kenia)", "nativeName": "Kiswahili (Kenya)", "primary": false},
        "ta-IN": {"tag": "ta-IN", "name": "Tamil (India)", "nativeName": "தமிழ் (இந்தியா)", "primary": false},
        "te-IN": {"tag": "te-IN", "name": "Telugu (India)", "nativeName": "తెలుగు (భారతదేశం)", "primary": false},
        "kn-IN": {"tag": "kn-IN", "name": "Canarés (India)", "nativeName": "ಕನ್ನಡ (ಭಾರತ)", "primary": false},
        "mr-IN": {"tag": "mr-IN", "name": "Maratí (India)", "nativeName": "मराठी (भारत)", "primary": false},
        "gu-IN": {"tag": "gu-IN", "name": "Guyaratí (India)", "nativeName": "ગુજરાતી (ભારત)", "primary": false},
        "pa-IN": {"tag": "pa-IN", "name": "Panyabí (India)", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)", "primary": false},
        "kok-IN": {"tag": "kok-IN", "name": "Konkaní (India)", "nativeName": "कोंकणी (भारत)", "primary": false},
        "sa-IN": {"tag": "sa-IN", "name": "Sánscrito (India)", "nativeName": "संस्कृत (भारत)", "primary": false},
        "ur-PK": {"tag": "ur-PK", "name": "Urdu (Pakistán)", "nativeName": "اردو (پاکستان)", "primary": false},
        "fa-IR": {"tag": "fa-IR", "name": "Persa (Irán)", "nativeName": "فارسی (ایران)", "primary": false},
        "syr-SY": {"tag": "syr-SY", "name": "Siríaco (Siria)", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)", "primary": false},
        "div-MV": {"tag": "div-MV", "name": "Dhivehi (Maldivas)", "nativeName": "ދިވެހި (މޯލްޑިވްސް)", "primary": false},
        "ka-GE": {"tag": "ka-GE", "name": "Georgiano (Georgia)", "nativeName": "ქართული (საქართველო)", "primary": false},      
}

const { getTag, getTags, getPrimaryTags } = createTagUtils(tags)
export {
    getTag, getTags,getPrimaryTags
}
export * from './types'    