import { createTagUtils } from './utils'

export const tags = {
    "zh-CN": {"tag": "zh-CN", "name": "Kiina (yksinkertaistettu)", "nativeName": "简体中文", "primary": true },
    "zh-TW": {"tag": "zh-TW", "name": "Kiina (perinteinen - Taiwan)", "nativeName": "繁體中文(中國臺灣)", "primary": false},
    "zh-HK": {"tag": "zh-HK", "name": "Kiina (perinteinen - Hongkong)", "nativeName": "繁體中文(中國香港)", "primary": false},
    "zh-MO": {"tag": "zh-MO", "name": "Kiina (perinteinen - Macao)", "nativeName": "繁體中文(中國澳門)", "primary": false},
    "zh-SG": {"tag": "zh-SG", "name": "Kiina (yksinkertaistettu - Singapore)", "nativeName": "简体中文(新加坡)", "primary": false},      
    "zh-CHS": {"tag": "zh-CHS", "name": "Kiina (yksinkertaistettu)", "nativeName": "简体中文", "primary": false},
    "zh-CHT": {"tag": "zh-CHT", "name": "Kiina (perinteinen)", "nativeName": "繁體中文(Traditional Chinese)", "primary": false},
    "en-US": {"tag": "en-US", "name": "Englanti (Yhdysvallat)", "nativeName": "English (United States)", "primary": true },
    "en-GB": {"tag": "en-GB", "name": "Englanti (Yhdistynyt kuningaskunta)", "nativeName": "English (United Kingdom)", "primary": false},
    "en-CA": {"tag": "en-CA", "name": "Englanti (Kanada)", "nativeName": "English (Canada)", "primary": false},
    "en-AU": {"tag": "en-AU", "name": "Englanti (Australia)", "nativeName": "English (Australia)", "primary": false},
    "en-IN": {"tag": "en-IN", "name": "Englanti (Intia)", "nativeName": "English (India)", "primary": false},
    "en-ZA": {"tag": "en-ZA", "name": "Englanti (Etelä-Afrikka)", "nativeName": "English (South Africa)", "primary": false},
    "en-NZ": {"tag": "en-NZ", "name": "Englanti (Uusi-Seelanti)", "nativeName": "English (New Zealand)", "primary": false},
    "en-IE": {"tag": "en-IE", "name": "Englanti (Irlanti)", "nativeName": "English (Ireland)", "primary": false},
    "en-PH": {"tag": "en-PH", "name": "Englanti (Filippiinit)", "nativeName": "English (Philippines)", "primary": false},
    "en-ZW": {"tag": "en-ZW", "name": "Englanti (Zimbabwe)", "nativeName": "English (Zimbabwe)", "primary": false},
    "en-BZ": {"tag": "en-BZ", "name": "Englanti (Belize)", "nativeName": "English (Belize)", "primary": false},
    "en-CB": {"tag": "en-CB", "name": "Englanti (Karibia)", "nativeName": "English (Caribbean)", "primary": false},
    "en-JM": {"tag": "en-JM", "name": "Englanti (Jamaika)", "nativeName": "English (Jamaica)", "primary": false},
    "en-TT": {"tag": "en-TT", "name": "Englanti (Trinidad ja Tobago)", "nativeName": "English (Trinidad and Tobago)", "primary": false},
    "en-NG": {"tag": "en-NG", "name": "Englanti (Nigeria)", "nativeName": "English (Nigeria)", "primary": false},
    "en-UG": {"tag": "en-UG", "name": "Englanti (Uganda)", "nativeName": "English (Uganda)", "primary": false},
    "hi-IN": {"tag": "hi-IN", "name": "Hindi (Intia)", "nativeName": "हिन्दी (Hindi)", "primary": false},
    "es-ES": {"tag": "es-ES", "name": "Espanja (Espanja)", "nativeName": "Español (España)", "primary": true },
    "es-MX": {"tag": "es-MX", "name": "Espanja (Meksiko)", "nativeName": "Español (México)", "primary": false},
    "es-AR": {"tag": "es-AR", "name": "Espanja (Argentiina)", "nativeName": "Español (Argentina)", "primary": false},
    "es-CO": {"tag": "es-CO", "name": "Espanja (Kolumbia)", "nativeName": "Español (Colombia)", "primary": false},
    "es-PE": {"tag": "es-PE", "name": "Espanja (Peru)", "nativeName": "Español (Perú)", "primary": false},
    "es-VE": {"tag": "es-VE", "name": "Espanja (Venezuela)", "nativeName": "Español (Venezuela)", "primary": false},
    "es-CL": {"tag": "es-CL", "name": "Espanja (Chile)", "nativeName": "Español (Chile)", "primary": false},
    "es-EC": {"tag": "es-EC", "name": "Espanja (Ecuador)", "nativeName": "Español (Ecuador)", "primary": false},
    "es-GT": {"tag": "es-GT", "name": "Espanja (Guatemala)", "nativeName": "Español (Guatemala)", "primary": false},
    "es-CU": {"tag": "es-CU", "name": "Espanja (Kuuba)", "nativeName": "Español (Cuba)", "primary": false},
    "es-BO": {"tag": "es-BO", "name": "Espanja (Bolivia)", "nativeName": "Español (Bolivia)", "primary": false},
    "es-DO": {"tag": "es-DO", "name": "Espanja (Dominikaaninen tasavalta)", "nativeName": "Español (República Dominicana)", "primary": false},
    "es-HN": {"tag": "es-HN", "name": "Espanja (Honduras)", "nativeName": "Español (Honduras)", "primary": false},
    "es-PY": {"tag": "es-PY", "name": "Espanja (Paraguay)", "nativeName": "Español (Paraguay)", "primary": false},
    "es-SV": {"tag": "es-SV", "name": "Espanja (El Salvador)", "nativeName": "Español (El Salvador)", "primary": false},
    "es-NI": {"tag": "es-NI", "name": "Espanja (Nicaragua)", "nativeName": "Español (Nicaragua)", "primary": false},
    "es-PR": {"tag": "es-PR", "name": "Espanja (Puerto Rico)", "nativeName": "Español (Puerto Rico)", "primary": false},
    "es-UY": {"tag": "es-UY", "name": "Espanja (Uruguay)", "nativeName": "Español (Uruguay)", "primary": false},
    "es-PA": {"tag": "es-PA", "name": "Espanja (Panama)", "nativeName": "Español (Panamá)", "primary": false},
    "es-CR": {"tag": "es-CR", "name": "Espanja (Costa Rica)", "nativeName": "Español (Costa Rica)", "primary": false},
    "ar-EG": {"tag": "ar-EG", "name": "Arabia (Egypti)", "nativeName": "العربية (مصر)", "primary": true },
    "ar-SA": {"tag": "ar-SA", "name": "Arabia (Saudi-Arabia)", "nativeName": "العربية (السعودية)", "primary": false},
    "ar-DZ": {"tag": "ar-DZ", "name": "Arabia (Algeria)", "nativeName": "العربية (الجزائر)", "primary": false},
    "ar-MA": {"tag": "ar-MA", "name": "Arabia (Marokko)", "nativeName": "العربية (المغرب)", "primary": false},
    "ar-IQ": {"tag": "ar-IQ", "name": "Arabia (Irak)", "nativeName": "العربية (العراق)", "primary": false},
    "ar-SD": {"tag": "ar-SD", "name": "Arabia (Sudan)", "nativeName": "العربية (السودان)", "primary": false},
    "ar-YE": {"tag": "ar-YE", "name": "Arabia (Jemen)", "nativeName": "العربية (اليمن)", "primary": false},
    "ar-SY": {"tag": "ar-SY", "name": "Arabia (Syyria)", "nativeName": "العربية (سوريا)", "primary": false},
    "ar-TN": {"tag": "ar-TN", "name": "Arabia (Tunisia)", "nativeName": "العربية (تونس)", "primary": false},
    "ar-LY": {"tag": "ar-LY", "name": "Arabia (Libya)", "nativeName": "العربية (ليبيا)", "primary": false},
    "ar-JO": {"tag": "ar-JO", "name": "Arabia (Jordania)", "nativeName": "العربية (الأردن)", "primary": false},
    "ar-LB": {"tag": "ar-LB", "name": "Arabia (Libanon)", "nativeName": "العربية (لبنان)", "primary": false},
    "ar-KW": {"tag": "ar-KW", "name": "Arabia (Kuwait)", "nativeName": "العربية (الكويت)", "primary": false},
    "ar-AE": {"tag": "ar-AE", "name": "Arabia (Yhdistyneet arabiemiirikunnat)", "nativeName": "العربية (الإمارات)", "primary": false},
    "ar-BH": {"tag": "ar-BH", "name": "Arabia (Bahrain)", "nativeName": "العربية (البحرين)", "primary": false},
    "ar-QA": {"tag": "ar-QA", "name": "Arabia (Qatar)", "nativeName": "العربية (قطر)", "primary": false},
    "ar-OM": {"tag": "ar-OM", "name": "Arabia (Oman)", "nativeName": "العربية (عمان)", "primary": false},
    "pt-BR": {"tag": "pt-BR", "name": "Portugali (Brasilia)", "nativeName": "Português (Brasil)", "primary": false},
    "pt-PT": {"tag": "pt-PT", "name": "Portugali (Portugali)", "nativeName": "Português (Portugal)", "primary": true },
    "ru-RU": {"tag": "ru-RU", "name": "Venäjä (Venäjä)", "nativeName": "Русский (Россия)", "primary": true },
    "ja-JP": {"tag": "ja-JP", "name": "Japani (Japani)", "nativeName": "日本語 (日本)", "primary": true },
    "de-DE": {"tag": "de-DE", "name": "Saksa (Saksa)", "nativeName": "Deutsch (Deutschland)", "primary": true },
    "de-AT": {"tag": "de-AT", "name": "Saksa (Itävalta)", "nativeName": "Deutsch (Österreich)", "primary": false},
    "de-CH": {"tag": "de-CH", "name": "Saksa (Sveitsi)", "nativeName": "Deutsch (Schweiz)", "primary": false},
    "fr-FR": {"tag": "fr-FR", "name": "Ranska (Ranska)", "nativeName": "Français (France)", "primary": true },
    "fr-CA": {"tag": "fr-CA", "name": "Ranska (Kanada)", "nativeName": "Français (Canada)", "primary": false},
    "fr-BE": {"tag": "fr-BE", "name": "Ranska (Belgia)", "nativeName": "Français (Belgique)", "primary": false},
    "fr-CH": {"tag": "fr-CH", "name": "Ranska (Sveitsi)", "nativeName": "Français (Suisse)", "primary": false},
    "fr-LU": {"tag": "fr-LU", "name": "Ranska (Luxemburg)", "nativeName": "Français (Luxembourg)", "primary": false},
    "fr-MC": {"tag": "fr-MC", "name": "Ranska (Monaco)", "nativeName": "Français (Monaco)", "primary": false},
    "fr-CD": {"tag": "fr-CD", "name": "Ranska (Kongon demokraattinen tasavalta)", "nativeName": "Français (République démocratique du Congo)", "primary": false},
    "ko-KR": {"tag": "ko-KR", "name": "Korea (Etelä-Korea)", "nativeName": "한국어 (대한민국)", "primary": true},
    "ko-KP": {"tag": "ko-KP", "name": "Korea (Pohjois-Korea)", "nativeName": "한국어 (조선민주주인민공화국)", "primary": false},
    "it-IT": {"tag": "it-IT", "name": "Italia (Italia)", "nativeName": "Italiano (Italia)", "primary": true },
    "it-CH": {"tag": "it-CH", "name": "Italia (Sveitsi)", "nativeName": "Italiano (Svizzera)", "primary": false},
    "nl-NL": {"tag": "nl-NL", "name": "Hollanti (Alankomaat)", "nativeName": "Nederlands (Nederland)", "primary": true},
    "nl-BE": {"tag": "nl-BE", "name": "Hollanti (Belgia)", "nativeName": "Nederlands (België)", "primary": false},
    "bn-BD": {"tag": "bn-BD", "name": "Bengali (Bangladesh)", "nativeName": "বাংলা (বাংলাদেশ)", "primary": false},
    "pl-PL": {"tag": "pl-PL", "name": "Puola (Puola)", "nativeName": "Polski (Polska)", "primary": false},
    "vi-VN": {"tag": "vi-VN", "name": "Vietnam (Vietnam)", "nativeName": "Tiếng Việt (Việt Nam)", "primary": false},
    "tr-TR": {"tag": "tr-TR", "name": "Turkki (Turkki)", "nativeName": "Türkçe (Türkiye)", "primary": false},
    "th-TH": {"tag": "th-TH", "name": "Thai (Thaimaa)", "nativeName": "ไทย (ประเทศไทย)", "primary": false},
    "el-GR": {"tag": "el-GR", "name": "Kreikka (Kreikka)", "nativeName": "Ελληνικά (Ελλάδα)", "primary": false},
    "cs-CZ": {"tag": "cs-CZ", "name": "Tšekki (Tšekki)", "nativeName": "Čeština (Česká republika)", "primary": false},
    "sv-SE": {"tag": "sv-SE", "name": "Ruotsi (Ruotsi)", "nativeName": "Svenska (Sverige)", "primary": false },
    "sv-FI": {"tag": "sv-FI", "name": "Ruotsi (Suomi)", "nativeName": "Svenska (Finland)", "primary": false},
    "hu-HU": {"tag": "hu-HU", "name": "Unkari (Unkari)", "nativeName": "Magyar (Magyarország)", "primary": false},
    "fi-FI": {"tag": "fi-FI", "name": "Suomi (Suomi)", "nativeName": "Suomi (Suomi)", "primary": false},
    "da-DK": {"tag": "da-DK", "name": "Tanska (Tanska)", "nativeName": "Dansk (Danmark)", "primary": false},
    "nb-NO": {"tag": "nb-NO", "name": "Norjan bokmål (Norja)", "nativeName": "Norsk Bokmål (Norge)", "primary": false},
    "nn-NO": {"tag": "nn-NO", "name": "Norjan nynorsk (Norja)", "nativeName": "Norsk Nynorsk (Norge)", "primary": false},
    "he-IL": {"tag": "he-IL", "name": "Heprea (Israel)", "nativeName": "עברית (ישראל)", "primary": false},
    "id-ID": {"tag": "id-ID", "name": "Indonesia (Indonesia)", "nativeName": "Bahasa Indonesia (Indonesia)", "primary": false},
    "ms-MY": {"tag": "ms-MY", "name": "Malaiji (Malesia)", "nativeName": "Bahasa Melayu (Malaysia)", "primary": false},
    "ms-BN": {"tag": "ms-BN", "name": "Malaiji (Brunei)", "nativeName": "Bahasa Melayu (Brunei)", "primary": false},
    "ro-RO": {"tag": "ro-RO", "name": "Romania (Romania)", "nativeName": "Română (România)", "primary": false},
    "bg-BG": {"tag": "bg-BG", "name": "Bulgaria (Bulgaria)", "nativeName": "Български (България)", "primary": false},
    "uk-UA": {"tag": "uk-UA", "name": "Ukraina (Ukraina)", "nativeName": "Українська (Україна)", "primary": false},
    "sk-SK": {"tag": "sk-SK", "name": "Slovakia (Slovakia)", "nativeName": "Slovenčina (Slovensko)", "primary": false},
    "sl-SI": {"tag": "sl-SI", "name": "Slovenia (Slovenia)", "nativeName": "Slovenščina (Slovenija)", "primary": false},
    "hr-HR": {"tag": "hr-HR", "name": "Kroatia (Kroatia)", "nativeName": "Hrvatski (Hrvatska)", "primary": false},
    "ca-ES": {"tag": "ca-ES", "name": "Katalaani (Katalonia)", "nativeName": "Català (Catalunya)", "primary": false},
    "lt-LT": {"tag": "lt-LT", "name": "Liettua (Liettua)", "nativeName": "Lietuvių (Lietuva)", "primary": false},
    "lv-LV": {"tag": "lv-LV", "name": "Latvia (Latvia)", "nativeName": "Latviešu (Latvija)", "primary": false},
    "et-EE": {"tag": "et-EE", "name": "Viro (Viro)", "nativeName": "Eesti (Eesti)", "primary": false},        
    "sq-AL": {"tag": "sq-AL", "name": "Albania (Albania)", "nativeName": "Shqip (Shqipëri)", "primary": false},
    "mk-MK": {"tag": "mk-MK", "name": "Makedonia (Pohjois-Makedonia)", "nativeName": "Македонски (Македонија)", "primary": false},
    "be-BY": {"tag": "be-BY", "name": "Valkovenäjä (Valko-Venäjä)", "nativeName": "Беларуская (Беларусь)", "primary": false},
    "is-IS": {"tag": "is-IS", "name": "Islanti (Islanti)", "nativeName": "Íslenska (Ísland)", "primary": false},
    "gl-ES": {"tag": "gl-ES", "name": "Galicia (Galicia)", "nativeName": "Galego (Galicia)", "primary": false},
    "eu-ES": {"tag": "eu-ES", "name": "Baski (Baskimaa)", "nativeName": "Euskara (Euskal Herria)", "primary": false},
    "af-ZA": {"tag": "af-ZA", "name": "Afrikaans (Etelä-Afrikka)", "nativeName": "Afrikaans (Suid-Afrika)", "primary": false},
    "sw-KE": {"tag": "sw-KE", "name": "Swahili (Kenia)", "nativeName": "Kiswahili (Kenya)", "primary": false},
    "ta-IN": {"tag": "ta-IN", "name": "Tamil (Intia)", "nativeName": "தமிழ் (இந்தியா)", "primary": false},
    "te-IN": {"tag": "te-IN", "name": "Telugu (Intia)", "nativeName": "తెలుగు (భారతదేశం)", "primary": false},
    "kn-IN": {"tag": "kn-IN", "name": "Kannada (Intia)", "nativeName": "ಕನ್ನಡ (ಭಾರತ)", "primary": false},
    "mr-IN": {"tag": "mr-IN", "name": "Marathi (Intia)", "nativeName": "मराठी (भारत)", "primary": false},
    "gu-IN": {"tag": "gu-IN", "name": "Gujarati (Intia)", "nativeName": "ગુજરાતી (ભારત)", "primary": false},
    "pa-IN": {"tag": "pa-IN", "name": "Punjabi (Intia)", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)", "primary": false},
    "kok-IN": {"tag": "kok-IN", "name": "Konkani (Intia)", "nativeName": "कोंकणी (भारत)", "primary": false},
    "sa-IN": {"tag": "sa-IN", "name": "Sanskrit (Intia)", "nativeName": "संस्कृत (भारत)", "primary": false},
    "ur-PK": {"tag": "ur-PK", "name": "Urdu (Pakistan)", "nativeName": "اردو (پاکستان)", "primary": false},
    "fa-IR": {"tag": "fa-IR", "name": "Persia (Iran)", "nativeName": "فارسی (ایران)", "primary": false},
    "syr-SY": {"tag": "syr-SY", "name": "Syyria (Syyria)", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)", "primary": false},
    "div-MV": {"tag": "div-MV", "name": "Divehi (Malediivit)", "nativeName": "ދިވެހި (މޯލްޑިވްސް)", "primary": false},
    "ka-GE": {"tag": "ka-GE", "name": "Georgia (Georgia)", "nativeName": "ქართული (საქართველო)", "primary": false},
    "am-ET": {"tag": "am-ET", "name": "Amhara (Etiopia)", "nativeName": "አማርኛ (ኢትዮጵያ)", "primary": false},
    "my-MM": {"tag": "my-MM", "name": "Burma (Myanmar)", "nativeName": "မြန်မာ (မြန်မာ)", "primary": false}
}



const { getTag, getTags, getPrimaryTags } = createTagUtils(tags)
export {
    getTag, getTags,getPrimaryTags
}
export * from './types'    
