import { createTagUtils } from './utils'
 
export const tags = {
    "zh-CN": {"tag": "zh-CN", "name": "Chinois (simplifié)", "nativeName": "简体中文", "default": true},
    "zh-TW": {"tag": "zh-TW", "name": "Chinois (traditionnel - Taïwan)", "nativeName": "繁體中文 (臺灣)"},
    "zh-HK": {"tag": "zh-HK", "name": "Chinois (traditionnel - Hong Kong)", "nativeName": "繁體中文（香港）"},
    "zh-MO": {"tag": "zh-MO", "name": "Chinois (traditionnel - Macao)", "nativeName": "繁體中文 (Traditional Chinese - Macau)"},
    "zh-SG": {"tag": "zh-SG", "name": "Chinois (simplifié - Singapour)", "nativeName": "简体中文 (Simplified Chinese - Singapore)"},      
    "zh-CHS": {"tag": "zh-CHS", "name": "Chinois (simplifié)", "nativeName": "简体中文"},
    "zh-CHT": {"tag": "zh-CHT", "name": "Chinois (traditionnel)", "nativeName": "繁體中文 (Traditional Chinese)"},
    "en-US": {"tag": "en-US", "name": "Anglais (États-Unis)", "nativeName": "English (United States)", "default": true},
    "en-GB": {"tag": "en-GB", "name": "Anglais (Royaume-Uni)", "nativeName": "English (United Kingdom)"},
    "en-CA": {"tag": "en-CA", "name": "Anglais (Canada)", "nativeName": "English (Canada)"},
    "en-AU": {"tag": "en-AU", "name": "Anglais (Australie)", "nativeName": "English (Australia)"},
    "en-IN": {"tag": "en-IN", "name": "Anglais (Inde)", "nativeName": "English (India)"},
    "en-ZA": {"tag": "en-ZA", "name": "Anglais (Afrique du Sud)", "nativeName": "English (South Africa)"},
    "en-NZ": {"tag": "en-NZ", "name": "Anglais (Nouvelle-Zélande)", "nativeName": "English (New Zealand)"},
    "en-IE": {"tag": "en-IE", "name": "Anglais (Irlande)", "nativeName": "English (Ireland)"},
    "en-PH": {"tag": "en-PH", "name": "Anglais (Philippines)", "nativeName": "English (Philippines)"},
    "en-ZW": {"tag": "en-ZW", "name": "Anglais (Zimbabwe)", "nativeName": "English (Zimbabwe)"},
    "en-BZ": {"tag": "en-BZ", "name": "Anglais (Belize)", "nativeName": "English (Belize)"},
    "en-CB": {"tag": "en-CB", "name": "Anglais (Caraïbes)", "nativeName": "English (Caribbean)"},
    "en-JM": {"tag": "en-JM", "name": "Anglais (Jamaïque)", "nativeName": "English (Jamaica)"},
    "en-TT": {"tag": "en-TT", "name": "Anglais (Trinité-et-Tobago)", "nativeName": "English (Trinidad and Tobago)"},
    "hi-IN": {"tag": "hi-IN", "name": "Hindi (Inde)", "nativeName": "हिन्दी (Hindi)"},
    "es-ES": {"tag": "es-ES", "name": "Espagnol (Espagne)", "nativeName": "Español (España)", "default": true},
    "es-MX": {"tag": "es-MX", "name": "Espagnol (Mexique)", "nativeName": "Español (México)"},
    "es-AR": {"tag": "es-AR", "name": "Espagnol (Argentine)", "nativeName": "Español (Argentina)"},
    "es-CO": {"tag": "es-CO", "name": "Espagnol (Colombie)", "nativeName": "Español (Colombia)"},
    "es-PE": {"tag": "es-PE", "name": "Espagnol (Pérou)", "nativeName": "Español (Perú)"},
    "es-VE": {"tag": "es-VE", "name": "Espagnol (Venezuela)", "nativeName": "Español (Venezuela)"},
    "es-CL": {"tag": "es-CL", "name": "Espagnol (Chili)", "nativeName": "Español (Chile)"},
    "es-EC": {"tag": "es-EC", "name": "Espagnol (Équateur)", "nativeName": "Español (Ecuador)"},
    "es-GT": {"tag": "es-GT", "name": "Espagnol (Guatemala)", "nativeName": "Español (Guatemala)"},
    "es-CU": {"tag": "es-CU", "name": "Espagnol (Cuba)", "nativeName": "Español (Cuba)"},
    "es-BO": {"tag": "es-BO", "name": "Espagnol (Bolivie)", "nativeName": "Español (Bolivia)"},
    "es-DO": {"tag": "es-DO", "name": "Espagnol (République dominicaine)", "nativeName": "Español (República Dominicana)"},
    "es-HN": {"tag": "es-HN", "name": "Espagnol (Honduras)", "nativeName": "Español (Honduras)"},
    "es-PY": {"tag": "es-PY", "name": "Espagnol (Paraguay)", "nativeName": "Español (Paraguay)"},
    "es-SV": {"tag": "es-SV", "name": "Espagnol (El Salvador)", "nativeName": "Español (El Salvador)"},
    "es-NI": {"tag": "es-NI", "name": "Espagnol (Nicaragua)", "nativeName": "Español (Nicaragua)"},
    "es-PR": {"tag": "es-PR", "name": "Espagnol (Porto Rico)", "nativeName": "Español (Puerto Rico)"},
    "es-UY": {"tag": "es-UY", "name": "Espagnol (Uruguay)", "nativeName": "Español (Uruguay)"},
    "es-PA": {"tag": "es-PA", "name": "Espagnol (Panama)", "nativeName": "Español (Panamá)"},
    "es-CR": {"tag": "es-CR", "name": "Espagnol (Costa Rica)", "nativeName": "Español (Costa Rica)"},
    "ar-EG": {"tag": "ar-EG", "name": "Arabe (Égypte)", "nativeName": "العربية (مصر)", "default": true},
    "ar-SA": {"tag": "ar-SA", "name": "Arabe (Arabie saoudite)", "nativeName": "العربية (السعودية)"},
    "ar-DZ": {"tag": "ar-DZ", "name": "Arabe (Algérie)", "nativeName": "العربية (الجزائر)"},
    "ar-MA": {"tag": "ar-MA", "name": "Arabe (Maroc)", "nativeName": "العربية (المغرب)"},
    "ar-IQ": {"tag": "ar-IQ", "name": "Arabe (Irak)", "nativeName": "العربية (العراق)"},
    "ar-SD": {"tag": "ar-SD", "name": "Arabe (Soudan)", "nativeName": "العربية (السودان)"},
    "ar-YE": {"tag": "ar-YE", "name": "Arabe (Yémen)", "nativeName": "العربية (اليمن)"},
    "ar-SY": {"tag": "ar-SY", "name": "Arabe (Syrie)", "nativeName": "العربية (سوريا)"},
    "ar-TN": {"tag": "ar-TN", "name": "Arabe (Tunisie)", "nativeName": "العربية (تونس)"},
    "ar-LY": {"tag": "ar-LY", "name": "Arabe (Libye)", "nativeName": "العربية (ليبيا)"},
    "ar-JO": {"tag": "ar-JO", "name": "Arabe (Jordanie)", "nativeName": "العربية (الأردن)"},
    "ar-LB": {"tag": "ar-LB", "name": "Arabe (Liban)", "nativeName": "العربية (لبنان)"},
    "ar-KW": {"tag": "ar-KW", "name": "Arabe (Koweït)", "nativeName": "العربية (الكويت)"},
    "ar-AE": {"tag": "ar-AE", "name": "Arabe (Émirats arabes unis)", "nativeName": "العربية (الإمارات)"},
    "ar-BH": {"tag": "ar-BH", "name": "Arabe (Bahreïn)", "nativeName": "العربية (البحرين)"},
    "ar-QA": {"tag": "ar-QA", "name": "Arabe (Qatar)", "nativeName": "العربية (قطر)"},
    "ar-OM": {"tag": "ar-OM", "name": "Arabe (Oman)", "nativeName": "العربية (عمان)"},
    "pt-BR": {"tag": "pt-BR", "name": "Portugais (Brésil)", "nativeName": "Português (Brasil)"},
    "pt-PT": {"tag": "pt-PT", "name": "Portugais (Portugal)", "nativeName": "Português (Portugal)", "default": true},
    "ru-RU": {"tag": "ru-RU", "name": "Russe (Russie)", "nativeName": "Русский (Россия)", "default": true},
    "ja-JP": {"tag": "ja-JP", "name": "Japonais (Japon)", "nativeName": "日本語 (日本)", "default": true},
    "de-DE": {"tag": "de-DE", "name": "Allemand (Allemagne)", "nativeName": "Deutsch (Deutschland)", "default": true},
    "de-AT": {"tag": "de-AT", "name": "Allemand (Autriche)", "nativeName": "Deutsch (Österreich)"},
    "de-CH": {"tag": "de-CH", "name": "Allemand (Suisse)", "nativeName": "Deutsch (Schweiz)"},
    "fr-FR": {"tag": "fr-FR", "name": "Français (France)", "nativeName": "Français (France)", "default": true},
    "fr-CA": {"tag": "fr-CA", "name": "Français (Canada)", "nativeName": "Français (Canada)"},
    "fr-BE": {"tag": "fr-BE", "name": "Français (Belgique)", "nativeName": "Français (Belgique)"},
    "fr-CH": {"tag": "fr-CH", "name": "Français (Suisse)", "nativeName": "Français (Suisse)"},
    "fr-LU": {"tag": "fr-LU", "name": "Français (Luxembourg)", "nativeName": "Français (Luxembourg)"},
    "fr-MC": {"tag": "fr-MC", "name": "Français (Monaco)", "nativeName": "Français (Monaco)"},
    "ko-KR": {"tag": "ko-KR", "name": "Coréen (Corée du Sud)", "nativeName": "한국어 (대한민국)"},
    "it-IT": {"tag": "it-IT", "name": "Italien (Italie)", "nativeName": "Italiano (Italia)", "default": true },
    "it-CH": {"tag": "it-CH", "name": "Italien (Suisse)", "nativeName": "Italiano (Svizzera)"},
    "nl-NL": {"tag": "nl-NL", "name": "Néerlandais (Pays-Bas)", "nativeName": "Nederlands (Nederland)"},
    "nl-BE": {"tag": "nl-BE", "name": "Néerlandais (Belgique)", "nativeName": "Nederlands (België)"},
    "pl-PL": {"tag": "pl-PL", "name": "Polonais (Pologne)", "nativeName": "Polski (Polska)"},
    "vi-VN": {"tag": "vi-VN", "name": "Vietnamien (Vietnam)", "nativeName": "Tiếng Việt (Việt Nam)"},
    "tr-TR": {"tag": "tr-TR", "name": "Turc (Turquie)", "nativeName": "Türkçe (Türkiye)"},
    "th-TH": {"tag": "th-TH", "name": "Thaï (Thaïlande)", "nativeName": "ไทย (ประเทศไทย)"},
    "el-GR": {"tag": "el-GR", "name": "Grec (Grèce)", "nativeName": "Ελληνικά (Ελλάδα)"},
    "cs-CZ": {"tag": "cs-CZ", "name": "Tchèque (République tchèque)", "nativeName": "Čeština (Česká republika)"},
    "sv-SE": {"tag": "sv-SE", "name": "Suédois (Suède)", "nativeName": "Svenska (Sverige)", "default": true},
    "sv-FI": {"tag": "sv-FI", "name": "Suédois (Finlande)", "nativeName": "Svenska (Finland)"},
    "hu-HU": {"tag": "hu-HU", "name": "Hongrois (Hongrie)", "nativeName": "Magyar (Magyarország)"},
    "fi-FI": {"tag": "fi-FI", "name": "Finnois (Finlande)", "nativeName": "Suomi (Suomi)"},
    "da-DK": {"tag": "da-DK", "name": "Danois (Danemark)", "nativeName": "Dansk (Danmark)"},
    "nb-NO": {"tag": "nb-NO", "name": "Norvégien Bokmål (Norvège)", "nativeName": "Norsk Bokmål (Norge)"},
    "nn-NO": {"tag": "nn-NO", "name": "Norvégien Nynorsk (Norvège)", "nativeName": "Norsk Nynorsk (Norge)"},
    "he-IL": {"tag": "he-IL", "name": "Hébreu (Israël)", "nativeName": "עברית (ישראל)"},
    "id-ID": {"tag": "id-ID", "name": "Indonésien (Indonésie)", "nativeName": "Bahasa Indonesia (Indonesia)"},
    "ms-MY": {"tag": "ms-MY", "name": "Malais (Malaisie)", "nativeName": "Bahasa Melayu (Malaysia)"},
    "ms-BN": {"tag": "ms-BN", "name": "Malais (Brunei)", "nativeName": "Bahasa Melayu (Brunei)"},
    "ro-RO": {"tag": "ro-RO", "name": "Roumain (Roumanie)", "nativeName": "Română (România)"},
    "bg-BG": {"tag": "bg-BG", "name": "Bulgare (Bulgarie)", "nativeName": "Български (България)"},
    "uk-UA": {"tag": "uk-UA", "name": "Ukrainien (Ukraine)", "nativeName": "Українська (Україна)"},
    "sk-SK": {"tag": "sk-SK", "name": "Slovaque (Slovaquie)", "nativeName": "Slovenčina (Slovensko)"},
    "sl-SI": {"tag": "sl-SI", "name": "Slovène (Slovénie)", "nativeName": "Slovenščina (Slovenija)"},
    "hr-HR": {"tag": "hr-HR", "name": "Croate (Croatie)", "nativeName": "Hrvatski (Hrvatska)"},
    "ca-ES": {"tag": "ca-ES", "name": "Catalan (Catalogne)", "nativeName": "Català (Catalunya)"},
    "lt-LT": {"tag": "lt-LT", "name": "Lituanien (Lituanie)", "nativeName": "Lietuvių (Lietuva)"},
    "lv-LV": {"tag": "lv-LV", "name": "Letton (Lettonie)", "nativeName": "Latviešu (Latvija)"},
    "et-EE": {"tag": "et-EE", "name": "Estonien (Estonie)", "nativeName": "Eesti (Eesti)"},
    "sq-AL": {"tag": "sq-AL", "name": "Albanais (Albanie)", "nativeName": "Shqip (Shqipëri)"},
    "mk-MK": {"tag": "mk-MK", "name": "Macédonien (Macédoine du Nord)", "nativeName": "Македонски (Македонија)"},
    "be-BY": {"tag": "be-BY", "name": "Biélorusse (Biélorussie)", "nativeName": "Беларуская (Беларусь)"},
    "is-IS": {"tag": "is-IS", "name": "Islandais (Islande)", "nativeName": "Íslenska (Ísland)"},
    "gl-ES": {"tag": "gl-ES", "name": "Galicien (Galice)", "nativeName": "Galego (Galicia)"},
    "eu-ES": {"tag": "eu-ES", "name": "Basque (Pays basque)", "nativeName": "Euskara (Euskal Herria)"},
    "af-ZA": {"tag": "af-ZA", "name": "Afrikaans (Afrique du Sud)", "nativeName": "Afrikaans (Suid-Afrika)"},
    "sw-KE": {"tag": "sw-KE", "name": "Swahili (Kenya)", "nativeName": "Kiswahili (Kenya)"},
    "ta-IN": {"tag": "ta-IN", "name": "Tamoul (Inde)", "nativeName": "தமிழ் (இந்தியா)"},
    "te-IN": {"tag": "te-IN", "name": "Télougou (Inde)", "nativeName": "తెలుగు (భారతదేశం)"},
    "kn-IN": {"tag": "kn-IN", "name": "Kannada (Inde)", "nativeName": "ಕನ್ನಡ (ಭಾರತ)"},
    "mr-IN": {"tag": "mr-IN", "name": "Marathi (Inde)", "nativeName": "मराठी (भारत)"},
    "gu-IN": {"tag": "gu-IN", "name": "Gujarati (Inde)", "nativeName": "ગુજરાતી (ભારત)"},
    "pa-IN": {"tag": "pa-IN", "name": "Pendjabi (Inde)", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)"},
    "kok-IN": {"tag": "kok-IN", "name": "Konkani (Inde)", "nativeName": "कोंकणी (भारत)"},
    "sa-IN": {"tag": "sa-IN", "name": "Sanskrit (Inde)", "nativeName": "संस्कृत (भारत)"},
    "ur-PK": {"tag": "ur-PK", "name": "Ourdou (Pakistan)", "nativeName": "اردو (پاکستان)"},
    "fa-IR": {"tag": "fa-IR", "name": "Persan (Iran)", "nativeName": "فارسی (ایران)"},
    "syr-SY": {"tag": "syr-SY", "name": "Syriaque (Syrie)", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)"},
    "div-MV": {"tag": "div-MV", "name": "Dhivehi (Maldives)", "nativeName": "ދިވެހި (މޯލްޑިވްސް)"},
    "ka-GE": {"tag": "ka-GE", "name": "Géorgien (Géorgie)", "nativeName": "ქართული (საქართველო)"},      
}

const { getTag, getTags, getDefaultTags } = createTagUtils(tags)
export {
    getTag, getTags,getDefaultTags
}
export * from './types'    