import { createTagUtils } from './utils'
 
export const tags = {
    "zh-CN": {"tag": "zh-CN", "name": "Chinois (simplifié)", "nativeName": "简体中文", "primary": true },
    "zh-TW": {"tag": "zh-TW", "name": "Chinois (traditionnel - Taïwan)", "nativeName": "繁體中文 (臺灣)", "primary": false},
    "zh-HK": {"tag": "zh-HK", "name": "Chinois (traditionnel - Hong Kong)", "nativeName": "繁體中文（香港）", "primary": false},
    "zh-MO": {"tag": "zh-MO", "name": "Chinois (traditionnel - Macao)", "nativeName": "繁體中文 (Traditional Chinese - Macau)", "primary": false},
    "zh-SG": {"tag": "zh-SG", "name": "Chinois (simplifié - Singapour)", "nativeName": "简体中文 (Simplified Chinese - Singapore)", "primary": false},      
    "zh-CHS": {"tag": "zh-CHS", "name": "Chinois (simplifié)", "nativeName": "简体中文", "primary": false},
    "zh-CHT": {"tag": "zh-CHT", "name": "Chinois (traditionnel)", "nativeName": "繁體中文 (Traditional Chinese)", "primary": false},
    "en-US": {"tag": "en-US", "name": "Anglais (États-Unis)", "nativeName": "English (United States)", "primary": true },
    "en-GB": {"tag": "en-GB", "name": "Anglais (Royaume-Uni)", "nativeName": "English (United Kingdom)", "primary": false},
    "en-CA": {"tag": "en-CA", "name": "Anglais (Canada)", "nativeName": "English (Canada)", "primary": false},
    "en-AU": {"tag": "en-AU", "name": "Anglais (Australie)", "nativeName": "English (Australia)", "primary": false},
    "en-IN": {"tag": "en-IN", "name": "Anglais (Inde)", "nativeName": "English (India)", "primary": false},
    "en-ZA": {"tag": "en-ZA", "name": "Anglais (Afrique du Sud)", "nativeName": "English (South Africa)", "primary": false},
    "en-NZ": {"tag": "en-NZ", "name": "Anglais (Nouvelle-Zélande)", "nativeName": "English (New Zealand)", "primary": false},
    "en-IE": {"tag": "en-IE", "name": "Anglais (Irlande)", "nativeName": "English (Ireland)", "primary": false},
    "en-PH": {"tag": "en-PH", "name": "Anglais (Philippines)", "nativeName": "English (Philippines)", "primary": false},
    "en-ZW": {"tag": "en-ZW", "name": "Anglais (Zimbabwe)", "nativeName": "English (Zimbabwe)", "primary": false},
    "en-BZ": {"tag": "en-BZ", "name": "Anglais (Belize)", "nativeName": "English (Belize)", "primary": false},
    "en-CB": {"tag": "en-CB", "name": "Anglais (Caraïbes)", "nativeName": "English (Caribbean)", "primary": false},
    "en-JM": {"tag": "en-JM", "name": "Anglais (Jamaïque)", "nativeName": "English (Jamaica)", "primary": false},
    "en-TT": {"tag": "en-TT", "name": "Anglais (Trinité-et-Tobago)", "nativeName": "English (Trinidad and Tobago)", "primary": false},
    "hi-IN": {"tag": "hi-IN", "name": "Hindi (Inde)", "nativeName": "हिन्दी (Hindi)", "primary": false},
    "es-ES": {"tag": "es-ES", "name": "Espagnol (Espagne)", "nativeName": "Español (España)", "primary": true },
    "es-MX": {"tag": "es-MX", "name": "Espagnol (Mexique)", "nativeName": "Español (México)", "primary": false},
    "es-AR": {"tag": "es-AR", "name": "Espagnol (Argentine)", "nativeName": "Español (Argentina)", "primary": false},
    "es-CO": {"tag": "es-CO", "name": "Espagnol (Colombie)", "nativeName": "Español (Colombia)", "primary": false},
    "es-PE": {"tag": "es-PE", "name": "Espagnol (Pérou)", "nativeName": "Español (Perú)", "primary": false},
    "es-VE": {"tag": "es-VE", "name": "Espagnol (Venezuela)", "nativeName": "Español (Venezuela)", "primary": false},
    "es-CL": {"tag": "es-CL", "name": "Espagnol (Chili)", "nativeName": "Español (Chile)", "primary": false},
    "es-EC": {"tag": "es-EC", "name": "Espagnol (Équateur)", "nativeName": "Español (Ecuador)", "primary": false},
    "es-GT": {"tag": "es-GT", "name": "Espagnol (Guatemala)", "nativeName": "Español (Guatemala)", "primary": false},
    "es-CU": {"tag": "es-CU", "name": "Espagnol (Cuba)", "nativeName": "Español (Cuba)", "primary": false},
    "es-BO": {"tag": "es-BO", "name": "Espagnol (Bolivie)", "nativeName": "Español (Bolivia)", "primary": false},
    "es-DO": {"tag": "es-DO", "name": "Espagnol (République dominicaine)", "nativeName": "Español (República Dominicana)", "primary": false},
    "es-HN": {"tag": "es-HN", "name": "Espagnol (Honduras)", "nativeName": "Español (Honduras)", "primary": false},
    "es-PY": {"tag": "es-PY", "name": "Espagnol (Paraguay)", "nativeName": "Español (Paraguay)", "primary": false},
    "es-SV": {"tag": "es-SV", "name": "Espagnol (El Salvador)", "nativeName": "Español (El Salvador)", "primary": false},
    "es-NI": {"tag": "es-NI", "name": "Espagnol (Nicaragua)", "nativeName": "Español (Nicaragua)", "primary": false},
    "es-PR": {"tag": "es-PR", "name": "Espagnol (Porto Rico)", "nativeName": "Español (Puerto Rico)", "primary": false},
    "es-UY": {"tag": "es-UY", "name": "Espagnol (Uruguay)", "nativeName": "Español (Uruguay)", "primary": false},
    "es-PA": {"tag": "es-PA", "name": "Espagnol (Panama)", "nativeName": "Español (Panamá)", "primary": false},
    "es-CR": {"tag": "es-CR", "name": "Espagnol (Costa Rica)", "nativeName": "Español (Costa Rica)", "primary": false},
    "ar-EG": {"tag": "ar-EG", "name": "Arabe (Égypte)", "nativeName": "العربية (مصر)", "primary": true },
    "ar-SA": {"tag": "ar-SA", "name": "Arabe (Arabie saoudite)", "nativeName": "العربية (السعودية)", "primary": false},
    "ar-DZ": {"tag": "ar-DZ", "name": "Arabe (Algérie)", "nativeName": "العربية (الجزائر)", "primary": false},
    "ar-MA": {"tag": "ar-MA", "name": "Arabe (Maroc)", "nativeName": "العربية (المغرب)", "primary": false},
    "ar-IQ": {"tag": "ar-IQ", "name": "Arabe (Irak)", "nativeName": "العربية (العراق)", "primary": false},
    "ar-SD": {"tag": "ar-SD", "name": "Arabe (Soudan)", "nativeName": "العربية (السودان)", "primary": false},
    "ar-YE": {"tag": "ar-YE", "name": "Arabe (Yémen)", "nativeName": "العربية (اليمن)", "primary": false},
    "ar-SY": {"tag": "ar-SY", "name": "Arabe (Syrie)", "nativeName": "العربية (سوريا)", "primary": false},
    "ar-TN": {"tag": "ar-TN", "name": "Arabe (Tunisie)", "nativeName": "العربية (تونس)", "primary": false},
    "ar-LY": {"tag": "ar-LY", "name": "Arabe (Libye)", "nativeName": "العربية (ليبيا)", "primary": false},
    "ar-JO": {"tag": "ar-JO", "name": "Arabe (Jordanie)", "nativeName": "العربية (الأردن)", "primary": false},
    "ar-LB": {"tag": "ar-LB", "name": "Arabe (Liban)", "nativeName": "العربية (لبنان)", "primary": false},
    "ar-KW": {"tag": "ar-KW", "name": "Arabe (Koweït)", "nativeName": "العربية (الكويت)", "primary": false},
    "ar-AE": {"tag": "ar-AE", "name": "Arabe (Émirats arabes unis)", "nativeName": "العربية (الإمارات)", "primary": false},
    "ar-BH": {"tag": "ar-BH", "name": "Arabe (Bahreïn)", "nativeName": "العربية (البحرين)", "primary": false},
    "ar-QA": {"tag": "ar-QA", "name": "Arabe (Qatar)", "nativeName": "العربية (قطر)", "primary": false},
    "ar-OM": {"tag": "ar-OM", "name": "Arabe (Oman)", "nativeName": "العربية (عمان)", "primary": false},
    "pt-BR": {"tag": "pt-BR", "name": "Portugais (Brésil)", "nativeName": "Português (Brasil)", "primary": false},
    "pt-PT": {"tag": "pt-PT", "name": "Portugais (Portugal)", "nativeName": "Português (Portugal)", "primary": true },
    "ru-RU": {"tag": "ru-RU", "name": "Russe (Russie)", "nativeName": "Русский (Россия)", "primary": true },
    "ja-JP": {"tag": "ja-JP", "name": "Japonais (Japon)", "nativeName": "日本語 (日本)", "primary": true },
    "de-DE": {"tag": "de-DE", "name": "Allemand (Allemagne)", "nativeName": "Deutsch (Deutschland)", "primary": true },
    "de-AT": {"tag": "de-AT", "name": "Allemand (Autriche)", "nativeName": "Deutsch (Österreich)", "primary": false},
    "de-CH": {"tag": "de-CH", "name": "Allemand (Suisse)", "nativeName": "Deutsch (Schweiz)", "primary": false},
    "fr-FR": {"tag": "fr-FR", "name": "Français (France)", "nativeName": "Français (France)", "primary": true },
    "fr-CA": {"tag": "fr-CA", "name": "Français (Canada)", "nativeName": "Français (Canada)", "primary": false},
    "fr-BE": {"tag": "fr-BE", "name": "Français (Belgique)", "nativeName": "Français (Belgique)", "primary": false},
    "fr-CH": {"tag": "fr-CH", "name": "Français (Suisse)", "nativeName": "Français (Suisse)", "primary": false},
    "fr-LU": {"tag": "fr-LU", "name": "Français (Luxembourg)", "nativeName": "Français (Luxembourg)", "primary": false},
    "fr-MC": {"tag": "fr-MC", "name": "Français (Monaco)", "nativeName": "Français (Monaco)", "primary": false},
    "ko-KR": {"tag": "ko-KR", "name": "Coréen (Corée du Sud)", "nativeName": "한국어 (대한민국)", "primary": true},
    "it-IT": {"tag": "it-IT", "name": "Italien (Italie)", "nativeName": "Italiano (Italia)", "primary": true },
    "it-CH": {"tag": "it-CH", "name": "Italien (Suisse)", "nativeName": "Italiano (Svizzera)", "primary": false},
    "nl-NL": {"tag": "nl-NL", "name": "Néerlandais (Pays-Bas)", "nativeName": "Nederlands (Nederland)", "primary": true},
    "nl-BE": {"tag": "nl-BE", "name": "Néerlandais (Belgique)", "nativeName": "Nederlands (België)", "primary": false},
    "pl-PL": {"tag": "pl-PL", "name": "Polonais (Pologne)", "nativeName": "Polski (Polska)", "primary": false},
    "vi-VN": {"tag": "vi-VN", "name": "Vietnamien (Vietnam)", "nativeName": "Tiếng Việt (Việt Nam)", "primary": false},
    "tr-TR": {"tag": "tr-TR", "name": "Turc (Turquie)", "nativeName": "Türkçe (Türkiye)", "primary": false},
    "th-TH": {"tag": "th-TH", "name": "Thaï (Thaïlande)", "nativeName": "ไทย (ประเทศไทย)", "primary": false},
    "el-GR": {"tag": "el-GR", "name": "Grec (Grèce)", "nativeName": "Ελληνικά (Ελλάδα)", "primary": false},
    "cs-CZ": {"tag": "cs-CZ", "name": "Tchèque (République tchèque)", "nativeName": "Čeština (Česká republika)", "primary": false},
    "sv-SE": {"tag": "sv-SE", "name": "Suédois (Suède)", "nativeName": "Svenska (Sverige)", "primary": false },
    "sv-FI": {"tag": "sv-FI", "name": "Suédois (Finlande)", "nativeName": "Svenska (Finland)", "primary": false},
    "hu-HU": {"tag": "hu-HU", "name": "Hongrois (Hongrie)", "nativeName": "Magyar (Magyarország)", "primary": false},
    "fi-FI": {"tag": "fi-FI", "name": "Finnois (Finlande)", "nativeName": "Suomi (Suomi)", "primary": false},
    "da-DK": {"tag": "da-DK", "name": "Danois (Danemark)", "nativeName": "Dansk (Danmark)", "primary": false},
    "nb-NO": {"tag": "nb-NO", "name": "Norvégien Bokmål (Norvège)", "nativeName": "Norsk Bokmål (Norge)", "primary": false},
    "nn-NO": {"tag": "nn-NO", "name": "Norvégien Nynorsk (Norvège)", "nativeName": "Norsk Nynorsk (Norge)", "primary": false},
    "he-IL": {"tag": "he-IL", "name": "Hébreu (Israël)", "nativeName": "עברית (ישראל)", "primary": false},
    "id-ID": {"tag": "id-ID", "name": "Indonésien (Indonésie)", "nativeName": "Bahasa Indonesia (Indonesia)", "primary": false},
    "ms-MY": {"tag": "ms-MY", "name": "Malais (Malaisie)", "nativeName": "Bahasa Melayu (Malaysia)", "primary": false},
    "ms-BN": {"tag": "ms-BN", "name": "Malais (Brunei)", "nativeName": "Bahasa Melayu (Brunei)", "primary": false},
    "ro-RO": {"tag": "ro-RO", "name": "Roumain (Roumanie)", "nativeName": "Română (România)", "primary": false},
    "bg-BG": {"tag": "bg-BG", "name": "Bulgare (Bulgarie)", "nativeName": "Български (България)", "primary": false},
    "uk-UA": {"tag": "uk-UA", "name": "Ukrainien (Ukraine)", "nativeName": "Українська (Україна)", "primary": false},
    "sk-SK": {"tag": "sk-SK", "name": "Slovaque (Slovaquie)", "nativeName": "Slovenčina (Slovensko)", "primary": false},
    "sl-SI": {"tag": "sl-SI", "name": "Slovène (Slovénie)", "nativeName": "Slovenščina (Slovenija)", "primary": false},
    "hr-HR": {"tag": "hr-HR", "name": "Croate (Croatie)", "nativeName": "Hrvatski (Hrvatska)", "primary": false},
    "ca-ES": {"tag": "ca-ES", "name": "Catalan (Catalogne)", "nativeName": "Català (Catalunya)", "primary": false},
    "lt-LT": {"tag": "lt-LT", "name": "Lituanien (Lituanie)", "nativeName": "Lietuvių (Lietuva)", "primary": false},
    "lv-LV": {"tag": "lv-LV", "name": "Letton (Lettonie)", "nativeName": "Latviešu (Latvija)", "primary": false},
    "et-EE": {"tag": "et-EE", "name": "Estonien (Estonie)", "nativeName": "Eesti (Eesti)", "primary": false},
    "sq-AL": {"tag": "sq-AL", "name": "Albanais (Albanie)", "nativeName": "Shqip (Shqipëri)", "primary": false},
    "mk-MK": {"tag": "mk-MK", "name": "Macédonien (Macédoine du Nord)", "nativeName": "Македонски (Македонија)", "primary": false},
    "be-BY": {"tag": "be-BY", "name": "Biélorusse (Biélorussie)", "nativeName": "Беларуская (Беларусь)", "primary": false},
    "is-IS": {"tag": "is-IS", "name": "Islandais (Islande)", "nativeName": "Íslenska (Ísland)", "primary": false},
    "gl-ES": {"tag": "gl-ES", "name": "Galicien (Galice)", "nativeName": "Galego (Galicia)", "primary": false},
    "eu-ES": {"tag": "eu-ES", "name": "Basque (Pays basque)", "nativeName": "Euskara (Euskal Herria)", "primary": false},
    "af-ZA": {"tag": "af-ZA", "name": "Afrikaans (Afrique du Sud)", "nativeName": "Afrikaans (Suid-Afrika)", "primary": false},
    "sw-KE": {"tag": "sw-KE", "name": "Swahili (Kenya)", "nativeName": "Kiswahili (Kenya)", "primary": false},
    "ta-IN": {"tag": "ta-IN", "name": "Tamoul (Inde)", "nativeName": "தமிழ் (இந்தியா)", "primary": false},
    "te-IN": {"tag": "te-IN", "name": "Télougou (Inde)", "nativeName": "తెలుగు (భారతదేశం)", "primary": false},
    "kn-IN": {"tag": "kn-IN", "name": "Kannada (Inde)", "nativeName": "ಕನ್ನಡ (ಭಾರತ)", "primary": false},
    "mr-IN": {"tag": "mr-IN", "name": "Marathi (Inde)", "nativeName": "मराठी (भारत)", "primary": false},
    "gu-IN": {"tag": "gu-IN", "name": "Gujarati (Inde)", "nativeName": "ગુજરાતી (ભારત)", "primary": false},
    "pa-IN": {"tag": "pa-IN", "name": "Pendjabi (Inde)", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)", "primary": false},
    "kok-IN": {"tag": "kok-IN", "name": "Konkani (Inde)", "nativeName": "कोंकणी (भारत)", "primary": false},
    "sa-IN": {"tag": "sa-IN", "name": "Sanskrit (Inde)", "nativeName": "संस्कृत (भारत)", "primary": false},
    "ur-PK": {"tag": "ur-PK", "name": "Ourdou (Pakistan)", "nativeName": "اردو (پاکستان)", "primary": false},
    "fa-IR": {"tag": "fa-IR", "name": "Persan (Iran)", "nativeName": "فارسی (ایران)", "primary": false},
    "syr-SY": {"tag": "syr-SY", "name": "Syriaque (Syrie)", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)", "primary": false},
    "div-MV": {"tag": "div-MV", "name": "Dhivehi (Maldives)", "nativeName": "ދިވެހި (މޯލްޑިވްސް)", "primary": false},
    "ka-GE": {"tag": "ka-GE", "name": "Géorgien (Géorgie)", "nativeName": "ქართული (საქართველო)", "primary": false},      
}

const { getTag, getTags, getPrimaryTags } = createTagUtils(tags)
export {
    getTag, getTags,getPrimaryTags
}
export * from './types'    