import { createTagUtils } from './utils'

export const tags = {
    "zh-CN": {"tag": "zh-CN", "name": "चीनी (सरलीकृत)", "nativeName": "简体中文", "primary": true },
    "zh-TW": {"tag": "zh-TW", "name": "चीनी (पारंपरिक - ताइवान)", "nativeName": "繁體中文(中國臺灣)", "primary": false},
    "zh-HK": {"tag": "zh-HK", "name": "चीनी (पारंपरिक - हांगकांग)", "nativeName": "繁體中文(中國香港)", "primary": false},
    "zh-MO": {"tag": "zh-MO", "name": "चीनी (पारंपरिक - मकाऊ)", "nativeName": "繁體中文(中國澳門)", "primary": false},
    "zh-SG": {"tag": "zh-SG", "name": "चीनी (सरलीकृत - सिंगापुर)", "nativeName": "简体中文(新加坡)", "primary": false},      
    "zh-CHS": {"tag": "zh-CHS", "name": "चीनी (सरलीकृत)", "nativeName": "简体中文", "primary": false},
    "zh-CHT": {"tag": "zh-CHT", "name": "चीनी (पारंपरिक)", "nativeName": "繁體中文(Traditional Chinese)", "primary": false},
    "en-US": {"tag": "en-US", "name": "अंग्रेज़ी (संयुक्त राज्य अमेरिका)", "nativeName": "English (United States)", "primary": true },
    "en-GB": {"tag": "en-GB", "name": "अंग्रेज़ी (यूनाइटेड किंगडम)", "nativeName": "English (United Kingdom)", "primary": false},
    "en-CA": {"tag": "en-CA", "name": "अंग्रेज़ी (कनाडा)", "nativeName": "English (Canada)", "primary": false},
    "en-AU": {"tag": "en-AU", "name": "अंग्रेज़ी (ऑस्ट्रेलिया)", "nativeName": "English (Australia)", "primary": false},
    "en-IN": {"tag": "en-IN", "name": "अंग्रेज़ी (भारत)", "nativeName": "English (India)", "primary": false},
    "en-ZA": {"tag": "en-ZA", "name": "अंग्रेज़ी (दक्षिण अफ्रीका)", "nativeName": "English (South Africa)", "primary": false},
    "en-NZ": {"tag": "en-NZ", "name": "अंग्रेज़ी (न्यूजीलैंड)", "nativeName": "English (New Zealand)", "primary": false},
    "en-IE": {"tag": "en-IE", "name": "अंग्रेज़ी (आयरलैंड)", "nativeName": "English (Ireland)", "primary": false},
    "en-PH": {"tag": "en-PH", "name": "अंग्रेज़ी (फिलीपींस)", "nativeName": "English (Philippines)", "primary": false},
    "en-ZW": {"tag": "en-ZW", "name": "अंग्रेज़ी (जिम्बाब्वे)", "nativeName": "English (Zimbabwe)", "primary": false},
    "en-BZ": {"tag": "en-BZ", "name": "अंग्रेज़ी (बेलीज़)", "nativeName": "English (Belize)", "primary": false},
    "en-CB": {"tag": "en-CB", "name": "अंग्रेज़ी (कैरेबियन)", "nativeName": "English (Caribbean)", "primary": false},
    "en-JM": {"tag": "en-JM", "name": "अंग्रेज़ी (जमैका)", "nativeName": "English (Jamaica)", "primary": false},
    "en-TT": {"tag": "en-TT", "name": "अंग्रेज़ी (त्रिनिदाद और टोबैगो)", "nativeName": "English (Trinidad and Tobago)", "primary": false},
    "en-NG": {"tag": "en-NG", "name": "अंग्रेज़ी (नाइजीरिया)", "nativeName": "English (Nigeria)", "primary": false},
    "en-UG": {"tag": "en-UG", "name": "अंग्रेज़ी (युगांडा)", "nativeName": "English (Uganda)", "primary": false},
    "hi-IN": {"tag": "hi-IN", "name": "हिंदी (भारत)", "nativeName": "हिन्दी (Hindi)", "primary": false},
    "es-ES": {"tag": "es-ES", "name": "स्पैनिश (स्पेन)", "nativeName": "Español (España)", "primary": true },
    "es-MX": {"tag": "es-MX", "name": "स्पैनिश (मेक्सिको)", "nativeName": "Español (México)", "primary": false},
    "es-AR": {"tag": "es-AR", "name": "स्पैनिश (अर्जेंटीना)", "nativeName": "Español (Argentina)", "primary": false},
    "es-CO": {"tag": "es-CO", "name": "स्पैनिश (कोलंबिया)", "nativeName": "Español (Colombia)", "primary": false},
    "es-PE": {"tag": "es-PE", "name": "स्पैनिश (पेरू)", "nativeName": "Español (Perú)", "primary": false},
    "es-VE": {"tag": "es-VE", "name": "स्पैनिश (वेनेजुएला)", "nativeName": "Español (Venezuela)", "primary": false},
    "es-CL": {"tag": "es-CL", "name": "स्पैनिश (चिली)", "nativeName": "Español (Chile)", "primary": false},
    "es-EC": {"tag": "es-EC", "name": "स्पैनिश (इक्वाडोर)", "nativeName": "Español (Ecuador)", "primary": false},
    "es-GT": {"tag": "es-GT", "name": "स्पैनिश (ग्वाटेमाला)", "nativeName": "Español (Guatemala)", "primary": false},
    "es-CU": {"tag": "es-CU", "name": "स्पैनिश (क्यूबा)", "nativeName": "Español (Cuba)", "primary": false},
    "es-BO": {"tag": "es-BO", "name": "स्पैनिश (बोलिविया)", "nativeName": "Español (Bolivia)", "primary": false},
    "es-DO": {"tag": "es-DO", "name": "स्पैनिश (डोमिनिकन गणराज्य)", "nativeName": "Español (República Dominicana)", "primary": false},
    "es-HN": {"tag": "es-HN", "name": "स्पैनिश (होंडुरास)", "nativeName": "Español (Honduras)", "primary": false},
    "es-PY": {"tag": "es-PY", "name": "स्पैनिश (पाराग्वे)", "nativeName": "Español (Paraguay)", "primary": false},
    "es-SV": {"tag": "es-SV", "name": "स्पैनिश (एल साल्वाडोर)", "nativeName": "Español (El Salvador)", "primary": false},
    "es-NI": {"tag": "es-NI", "name": "स्पैनिश (निकारागुआ)", "nativeName": "Español (Nicaragua)", "primary": false},
    "es-PR": {"tag": "es-PR", "name": "स्पैनिश (पोर्टो रिको)", "nativeName": "Español (Puerto Rico)", "primary": false},
    "es-UY": {"tag": "es-UY", "name": "स्पैनिश (उरुग्वे)", "nativeName": "Español (Uruguay)", "primary": false},
    "es-PA": {"tag": "es-PA", "name": "स्पैनिश (पनामा)", "nativeName": "Español (Panamá)", "primary": false},
    "es-CR": {"tag": "es-CR", "name": "स्पैनिश (कोस्टा रिका)", "nativeName": "Español (Costa Rica)", "primary": false},
    "ar-EG": {"tag": "ar-EG", "name": "अरबी (मिस्र)", "nativeName": "العربية (مصر)", "primary": true },
    "ar-SA": {"tag": "ar-SA", "name": "अरबी (सऊदी अरब)", "nativeName": "العربية (السعودية)", "primary": false},
    "ar-DZ": {"tag": "ar-DZ", "name": "अरबी (अल्जीरिया)", "nativeName": "العربية (الجزائر)", "primary": false},
    "ar-MA": {"tag": "ar-MA", "name": "अरबी (मोरक्को)", "nativeName": "العربية (المغرب)", "primary": false},
    "ar-IQ": {"tag": "ar-IQ", "name": "अरबी (इराक)", "nativeName": "العربية (العراق)", "primary": false},
    "ar-SD": {"tag": "ar-SD", "name": "अरबी (सूडान)", "nativeName": "العربية (السودان)", "primary": false},
    "ar-YE": {"tag": "ar-YE", "name": "अरबी (यमन)", "nativeName": "العربية (اليمن)", "primary": false},
    "ar-SY": {"tag": "ar-SY", "name": "अरबी (सीरिया)", "nativeName": "العربية (سوريا)", "primary": false},
    "ar-TN": {"tag": "ar-TN", "name": "अरबी (ट्यूनीशिया)", "nativeName": "العربية (تونس)", "primary": false},
    "ar-LY": {"tag": "ar-LY", "name": "अरबी (लीबिया)", "nativeName": "العربية (ليبيا)", "primary": false},
    "ar-JO": {"tag": "ar-JO", "name": "अरबी (जॉर्डन)", "nativeName": "العربية (الأردن)", "primary": false},
    "ar-LB": {"tag": "ar-LB", "name": "अरबी (लेबनान)", "nativeName": "العربية (لبنان)", "primary": false},
    "ar-KW": {"tag": "ar-KW", "name": "अरबी (कुवैत)", "nativeName": "العربية (الكويت)", "primary": false},
    "ar-AE": {"tag": "ar-AE", "name": "अरबी (संयुक्त अरब अमीरात)", "nativeName": "العربية (الإمارات)", "primary": false},
    "ar-BH": {"tag": "ar-BH", "name": "अरबी (बहरीन)", "nativeName": "العربية (البحرين)", "primary": false},
    "ar-QA": {"tag": "ar-QA", "name": "अरबी (कतर)", "nativeName": "العربية (قطر)", "primary": false},
    "ar-OM": {"tag": "ar-OM", "name": "अरबी (ओमान)", "nativeName": "العربية (عمان)", "primary": false},
    "pt-BR": {"tag": "pt-BR", "name": "पुर्तगाली (ब्राजील)", "nativeName": "Português (Brasil)", "primary": false},
    "pt-PT": {"tag": "pt-PT", "name": "पुर्तगाली (पुर्तगाल)", "nativeName": "Português (Portugal)", "primary": true },
    "ru-RU": {"tag": "ru-RU", "name": "रूसी (रूस)", "nativeName": "Русский (Россия)", "primary": true },
    "ja-JP": {"tag": "ja-JP", "name": "जापानी (जापान)", "nativeName": "日本語 (日本)", "primary": true },
    "de-DE": {"tag": "de-DE", "name": "जर्मन (जर्मनी)", "nativeName": "Deutsch (Deutschland)", "primary": true },
    "de-AT": {"tag": "de-AT", "name": "जर्मन (ऑस्ट्रिया)", "nativeName": "Deutsch (Österreich)", "primary": false},
    "de-CH": {"tag": "de-CH", "name": "जर्मन (स्विट्जरलैंड)", "nativeName": "Deutsch (Schweiz)", "primary": false},
    "fr-FR": {"tag": "fr-FR", "name": "फ्रेंच (फ्रांस)", "nativeName": "Français (France)", "primary": true },
    "fr-CA": {"tag": "fr-CA", "name": "फ्रेंच (कनाडा)", "nativeName": "Français (Canada)", "primary": false},
    "fr-BE": {"tag": "fr-BE", "name": "फ्रेंच (बेल्जियम)", "nativeName": "Français (Belgique)", "primary": false},
    "fr-CH": {"tag": "fr-CH", "name": "फ्रेंच (स्विट्जरलैंड)", "nativeName": "Français (Suisse)", "primary": false},
    "fr-LU": {"tag": "fr-LU", "name": "फ्रेंच (लक्जमबर्ग)", "nativeName": "Français (Luxembourg)", "primary": false},
    "fr-MC": {"tag": "fr-MC", "name": "फ्रेंच (मोनाको)", "nativeName": "Français (Monaco)", "primary": false},
    "fr-CD": {"tag": "fr-CD", "name": "फ्रेंच (कांगो लोकतांत्रिक गणराज्य)", "nativeName": "Français (République démocratique du Congo)", "primary": false},
    "ko-KR": {"tag": "ko-KR", "name": "कोरियाई (दक्षिण कोरिया)", "nativeName": "한국어 (대한민국)", "primary": true},
    "ko-KP": {"tag": "ko-KP", "name": "कोरियाई (उत्तर कोरिया)", "nativeName": "한국어 (조선민주주인민공화국)", "primary": false},
    "it-IT": {"tag": "it-IT", "name": "इटालियन (इटली)", "nativeName": "Italiano (Italia)", "primary": true },
    "it-CH": {"tag": "it-CH", "name": "इटालियन (स्विट्जरलैंड)", "nativeName": "Italiano (Svizzera)", "primary": false},
    "nl-NL": {"tag": "nl-NL", "name": "डच (नीदरलैंड)", "nativeName": "Nederlands (Nederland)", "primary": true},
    "nl-BE": {"tag": "nl-BE", "name": "डच (बेल्जियम)", "nativeName": "Nederlands (België)", "primary": false},
    "bn-BD": {"tag": "bn-BD", "name": "बंगाली (बांग्लादेश)", "nativeName": "বাংলা (বাংলাদেশ)", "primary": false},
    "pl-PL": {"tag": "pl-PL", "name": "पोलिश (पोलैंड)", "nativeName": "Polski (Polska)", "primary": false},
    "vi-VN": {"tag": "vi-VN", "name": "वियतनामी (वियतनाम)", "nativeName": "Tiếng Việt (Việt Nam)", "primary": false},
    "tr-TR": {"tag": "tr-TR", "name": "तुर्की (तुर्की)", "nativeName": "Türkçe (Türkiye)", "primary": false},
    "th-TH": {"tag": "th-TH", "name": "थाई (थाईलैंड)", "nativeName": "ไทย (ประเทศไทย)", "primary": false},
    "el-GR": {"tag": "el-GR", "name": "ग्रीक (ग्रीस)", "nativeName": "Ελληνικά (Ελλάδα)", "primary": false},
    "cs-CZ": {"tag": "cs-CZ", "name": "चेक (चेक गणराज्य)", "nativeName": "Čeština (Česká republika)", "primary": false},
    "sv-SE": {"tag": "sv-SE", "name": "स्वीडिश (स्वीडन)", "nativeName": "Svenska (Sverige)", "primary": false },
    "sv-FI": {"tag": "sv-FI", "name": "स्वीडिश (फिनलैंड)", "nativeName": "Svenska (Finland)", "primary": false},
    "hu-HU": {"tag": "hu-HU", "name": "हंगेरियन (हंगरी)", "nativeName": "Magyar (Magyarország)", "primary": false},
    "fi-FI": {"tag": "fi-FI", "name": "फिनिश (फिनलैंड)", "nativeName": "Suomi (Suomi)", "primary": false},
    "da-DK": {"tag": "da-DK", "name": "डेनिश (डेनमार्क)", "nativeName": "Dansk (Danmark)", "primary": false},
    "nb-NO": {"tag": "nb-NO", "name": "नॉर्वेजियन बोकमाल (नॉर्वे)", "nativeName": "Norsk Bokmål (Norge)", "primary": false},
    "nn-NO": {"tag": "nn-NO", "name": "नॉर्वेजियन न्योनोर्स्क (नॉर्वे)", "nativeName": "Norsk Nynorsk (Norge)", "primary": false},
    "he-IL": {"tag": "he-IL", "name": "हिब्रू (इजराइल)", "nativeName": "עברית (ישראל)", "primary": false},
    "id-ID": {"tag": "id-ID", "name": "इंडोनेशियाई (इंडोनेशिया)", "nativeName": "Bahasa Indonesia (Indonesia)", "primary": false},
    "ms-MY": {"tag": "ms-MY", "name": "मलय (मलेशिया)", "nativeName": "Bahasa Melayu (Malaysia)", "primary": false},
    "ms-BN": {"tag": "ms-BN", "name": "मलय (ब्रुनेई)", "nativeName": "Bahasa Melayu (Brunei)", "primary": false},
    "ro-RO": {"tag": "ro-RO", "name": "रोमानियाई (रोमानिया)", "nativeName": "Română (România)", "primary": false},
    "bg-BG": {"tag": "bg-BG", "name": "बल्गेरियाई (बल्गेरिया)", "nativeName": "Български (България)", "primary": false},
    "uk-UA": {"tag": "uk-UA", "name": "यूक्रेनी (यूक्रेन)", "nativeName": "Українська (Україна)", "primary": false},
    "sk-SK": {"tag": "sk-SK", "name": "स्लोवाक (स्लोवाकिया)", "nativeName": "Slovenčina (Slovensko)", "primary": false},
    "sl-SI": {"tag": "sl-SI", "name": "स्लोवेनियाई (स्लोवेनिया)", "nativeName": "Slovenščina (Slovenija)", "primary": false},
    "hr-HR": {"tag": "hr-HR", "name": "क्रोएशियाई (क्रोएशिया)", "nativeName": "Hrvatski (Hrvatska)", "primary": false},
    "ca-ES": {"tag": "ca-ES", "name": "कैटलन (कैटलोनिया)", "nativeName": "Català (Catalunya)", "primary": false},
    "lt-LT": {"tag": "lt-LT", "name": "लिथुआनियाई (लिथुआनिया)", "nativeName": "Lietuvių (Lietuva)", "primary": false},
    "lv-LV": {"tag": "lv-LV", "name": "लातवियाई (लातविया)", "nativeName": "Latviešu (Latvija)", "primary": false},
    "et-EE": {"tag": "et-EE", "name": "एस्टोनियाई (एस्टोनिया)", "nativeName": "Eesti (Eesti)", "primary": false},        
    "sq-AL": {"tag": "sq-AL", "name": "अल्बानियाई (अल्बानिया)", "nativeName": "Shqip (Shqipëri)", "primary": false},
    "mk-MK": {"tag": "mk-MK", "name": "मैसेडोनियाई (उत्तरी मैसेडोनिया)", "nativeName": "Македонски (Македонија)", "primary": false},
    "be-BY": {"tag": "be-BY", "name": "बेलारूसी (बेलारूस)", "nativeName": "Беларуская (Беларусь)", "primary": false},
    "is-IS": {"tag": "is-IS", "name": "आइसलैंडिक (आइसलैंड)", "nativeName": "Íslenska (Ísland)", "primary": false},
    "gl-ES": {"tag": "gl-ES", "name": "गैलिशियन (गैलिशिया)", "nativeName": "Galego (Galicia)", "primary": false},
    "eu-ES": {"tag": "eu-ES", "name": "बास्क (बास्क देश)", "nativeName": "Euskara (Euskal Herria)", "primary": false},
    "af-ZA": {"tag": "af-ZA", "name": "अफ्रीकांस (दक्षिण अफ्रीका)", "nativeName": "Afrikaans (Suid-Afrika)", "primary": false},
    "sw-KE": {"tag": "sw-KE", "name": "स्वाहिली (केन्या)", "nativeName": "Kiswahili (Kenya)", "primary": false},
    "ta-IN": {"tag": "ta-IN", "name": "तमिल (भारत)", "nativeName": "தமிழ் (இந்தியா)", "primary": false},
    "te-IN": {"tag": "te-IN", "name": "तेलुगु (भारत)", "nativeName": "తెలుగు (భారతదేశం)", "primary": false},
    "kn-IN": {"tag": "kn-IN", "name": "कन्नड़ (भारत)", "nativeName": "ಕನ್ನಡ (ಭಾರತ)", "primary": false},
    "mr-IN": {"tag": "mr-IN", "name": "मराठी (भारत)", "nativeName": "मराठी (भारत)", "primary": false},
    "gu-IN": {"tag": "gu-IN", "name": "गुजराती (भारत)", "nativeName": "ગુજરાતી (ભારત)", "primary": false},
    "pa-IN": {"tag": "pa-IN", "name": "पंजाबी (भारत)", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)", "primary": false},
    "kok-IN": {"tag": "kok-IN", "name": "कोंकणी (भारत)", "nativeName": "कोंकणी (भारत)", "primary": false},
    "sa-IN": {"tag": "sa-IN", "name": "संस्कृत (भारत)", "nativeName": "संस्कृत (भारत)", "primary": false},
    "ur-PK": {"tag": "ur-PK", "name": "उर्दू (पाकिस्तान)", "nativeName": "اردو (پاکستان)", "primary": false},
    "fa-IR": {"tag": "fa-IR", "name": "फ़ारसी (ईरान)", "nativeName": "فارسی (ایران)", "primary": false},
    "syr-SY": {"tag": "syr-SY", "name": "सीरियाई (सीरिया)", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)", "primary": false},
    "div-MV": {"tag": "div-MV", "name": "दिहीवी (मालदीव)", "nativeName": "ދިވެހި (މޯލްޑިވްސް)", "primary": false},
    "ka-GE": {"tag": "ka-GE", "name": "जॉर्जियन (जॉर्जिया)", "nativeName": "ქართული (საქართველო)", "primary": false},
    "am-ET": {"tag": "am-ET", "name": "अम्हारिक (इथियोपिया)", "nativeName": "አማርኛ (ኢትዮጵያ)", "primary": false},
    "my-MM": {"tag": "my-MM", "name": "बर्मी (म्यांमार)", "nativeName": "မြန်မာ (မြန်မာ)", "primary": false}
}



const { getTag, getTags, getPrimaryTags } = createTagUtils(tags)
export {
    getTag, getTags,getPrimaryTags
}
export * from './types'    
