import { createTagUtils } from './utils'

export const tags = {
    "zh-CN": {"tag": "zh-CN", "name": "中国語（簡体字）", "nativeName": "简体中文", "default": true},
    "zh-TW": {"tag": "zh-TW", "name": "中国語（繁体字 - 台湾）", "nativeName": "繁體中文 (臺灣)"},
    "zh-HK": {"tag": "zh-HK", "name": "中国語（繁体字 - 香港）", "nativeName": "繁體中文（香港）"},
    "zh-MO": {"tag": "zh-MO", "name": "中国語（繁体字 - マカオ）", "nativeName": "繁體中文 (Traditional Chinese - Macau)"},
    "zh-SG": {"tag": "zh-SG", "name": "中国語（簡体字 - シンガポール）", "nativeName": "简体中文 (Simplified Chinese - Singapore)"},      
    "zh-CHS": {"tag": "zh-CHS", "name": "中国語（簡体字）", "nativeName": "简体中文"},
    "zh-CHT": {"tag": "zh-CHT", "name": "中国語（繁体字）", "nativeName": "繁體中文 (Traditional Chinese)"},
    "en-US": {"tag": "en-US", "name": "英語（アメリカ）", "nativeName": "English (United States)", "default": true},
    "en-GB": {"tag": "en-GB", "name": "英語（イギリス）", "nativeName": "English (United Kingdom)"},
    "en-CA": {"tag": "en-CA", "name": "英語（カナダ）", "nativeName": "English (Canada)"},
    "en-AU": {"tag": "en-AU", "name": "英語（オーストラリア）", "nativeName": "English (Australia)"},
    "en-IN": {"tag": "en-IN", "name": "英語（インド）", "nativeName": "English (India)"},
    "en-ZA": {"tag": "en-ZA", "name": "英語（南アフリカ）", "nativeName": "English (South Africa)"},
    "en-NZ": {"tag": "en-NZ", "name": "英語（ニュージーランド）", "nativeName": "English (New Zealand)"},
    "en-IE": {"tag": "en-IE", "name": "英語（アイルランド）", "nativeName": "English (Ireland)"},
    "en-PH": {"tag": "en-PH", "name": "英語（フィリピン）", "nativeName": "English (Philippines)"},
    "en-ZW": {"tag": "en-ZW", "name": "英語（ジンバブエ）", "nativeName": "English (Zimbabwe)"},
    "en-BZ": {"tag": "en-BZ", "name": "英語（ベリーズ）", "nativeName": "English (Belize)"},
    "en-CB": {"tag": "en-CB", "name": "英語（カリブ海地域）", "nativeName": "English (Caribbean)"},
    "en-JM": {"tag": "en-JM", "name": "英語（ジャマイカ）", "nativeName": "English (Jamaica)"},
    "en-TT": {"tag": "en-TT", "name": "英語（トリニダード・トバゴ）", "nativeName": "English (Trinidad and Tobago)"},
    "hi-IN": {"tag": "hi-IN", "name": "ヒンディー語（インド）", "nativeName": "हिन्दी (Hindi)"},
    "es-ES": {"tag": "es-ES", "name": "スペイン語（スペイン）", "nativeName": "Español (España)", "default": true},
    "es-MX": {"tag": "es-MX", "name": "スペイン語（メキシコ）", "nativeName": "Español (México)"},
    "es-AR": {"tag": "es-AR", "name": "スペイン語（アルゼンチン）", "nativeName": "Español (Argentina)"},
    "es-CO": {"tag": "es-CO", "name": "スペイン語（コロンビア）", "nativeName": "Español (Colombia)"},
    "es-PE": {"tag": "es-PE", "name": "スペイン語（ペルー）", "nativeName": "Español (Perú)"},
    "es-VE": {"tag": "es-VE", "name": "スペイン語（ベネズエラ）", "nativeName": "Español (Venezuela)"},
    "es-CL": {"tag": "es-CL", "name": "スペイン語（チリ）", "nativeName": "Español (Chile)"},
    "es-EC": {"tag": "es-EC", "name": "スペイン語（エクアドル）", "nativeName": "Español (Ecuador)"},
    "es-GT": {"tag": "es-GT", "name": "スペイン語（グアテマラ）", "nativeName": "Español (Guatemala)"},
    "es-CU": {"tag": "es-CU", "name": "スペイン語（キューバ）", "nativeName": "Español (Cuba)"},
    "es-BO": {"tag": "es-BO", "name": "スペイン語（ボリビア）", "nativeName": "Español (Bolivia)"},
    "es-DO": {"tag": "es-DO", "name": "スペイン語（ドミニカ共和国）", "nativeName": "Español (República Dominicana)"},
    "es-HN": {"tag": "es-HN", "name": "スペイン語（ホンジュラス）", "nativeName": "Español (Honduras)"},
    "es-PY": {"tag": "es-PY", "name": "スペイン語（パラグアイ）", "nativeName": "Español (Paraguay)"},
    "es-SV": {"tag": "es-SV", "name": "スペイン語（エルサルバドル）", "nativeName": "Español (El Salvador)"},
    "es-NI": {"tag": "es-NI", "name": "スペイン語（ニカラグア）", "nativeName": "Español (Nicaragua)"},
    "es-PR": {"tag": "es-PR", "name": "スペイン語（プエルトリコ）", "nativeName": "Español (Puerto Rico)"},
    "es-UY": {"tag": "es-UY", "name": "スペイン語（ウルグアイ）", "nativeName": "Español (Uruguay)"},
    "es-PA": {"tag": "es-PA", "name": "スペイン語（パナマ）", "nativeName": "Español (Panamá)"},
    "es-CR": {"tag": "es-CR", "name": "スペイン語（コスタリカ）", "nativeName": "Español (Costa Rica)"},
    "ar-EG": {"tag": "ar-EG", "name": "アラビア語（エジプト）", "nativeName": "العربية (مصر)", "default": true},
    "ar-SA": {"tag": "ar-SA", "name": "アラビア語（サウジアラビア）", "nativeName": "العربية (السعودية)"},
    "ar-DZ": {"tag": "ar-DZ", "name": "アラビア語（アルジェリア）", "nativeName": "العربية (الجزائر)"},
    "ar-MA": {"tag": "ar-MA", "name": "アラビア語（モロッコ）", "nativeName": "العربية (المغرب)"},
    "ar-IQ": {"tag": "ar-IQ", "name": "アラビア語（イラク）", "nativeName": "العربية (العراق)"},
    "ar-SD": {"tag": "ar-SD", "name": "アラビア語（スーダン）", "nativeName": "العربية (السودان)"},
    "ar-YE": {"tag": "ar-YE", "name": "アラビア語（イエメン）", "nativeName": "العربية (اليمن)"}, 
    "ar-SY": {"tag": "ar-SY", "name": "アラビア語（シリア）", "nativeName": "العربية (سوريا)"},
    "ar-TN": {"tag": "ar-TN", "name": "アラビア語（チュニジア）", "nativeName": "العربية (تونس)"},
    "ar-LY": {"tag": "ar-LY", "name": "アラビア語（リビア）", "nativeName": "العربية (ليبيا)"},
    "ar-JO": {"tag": "ar-JO", "name": "アラビア語（ヨルダン）", "nativeName": "العربية (الأردن)"},
    "ar-LB": {"tag": "ar-LB", "name": "アラビア語（レバノン）", "nativeName": "العربية (لبنان)"},
    "ar-KW": {"tag": "ar-KW", "name": "アラビア語（クウェート）", "nativeName": "العربية (الكويت)"},
    "ar-AE": {"tag": "ar-AE", "name": "アラビア語（アラブ首長国連邦）", "nativeName": "العربية (الإمارات)"},
    "ar-BH": {"tag": "ar-BH", "name": "アラビア語（バーレーン）", "nativeName": "العربية (البحرين)"},
    "ar-QA": {"tag": "ar-QA", "name": "アラビア語（カタール）", "nativeName": "العربية (قطر)"},
    "ar-OM": {"tag": "ar-OM", "name": "アラビア語（オマーン）", "nativeName": "العربية (عمان)"},
    "pt-BR": {"tag": "pt-BR", "name": "ポルトガル語（ブラジル）", "nativeName": "Português (Brasil)"},
    "pt-PT": {"tag": "pt-PT", "name": "ポルトガル語（ポルトガル）", "nativeName": "Português (Portugal)", "default": true},
    "ru-RU": {"tag": "ru-RU", "name": "ロシア語（ロシア）", "nativeName": "Русский (Россия)", "default": true},
    "ja-JP": {"tag": "ja-JP", "name": "日本語（日本）", "nativeName": "日本語 (日本)", "default": true},
    "de-DE": {"tag": "de-DE", "name": "ドイツ語（ドイツ）", "nativeName": "Deutsch (Deutschland)", "default": true},
    "de-AT": {"tag": "de-AT", "name": "ドイツ語（オーストリア）", "nativeName": "Deutsch (Österreich)"},
    "de-CH": {"tag": "de-CH", "name": "ドイツ語（スイス）", "nativeName": "Deutsch (Schweiz)"},
    "fr-FR": {"tag": "fr-FR", "name": "フランス語（フランス）", "nativeName": "Français (France)", "default": true},
    "fr-CA": {"tag": "fr-CA", "name": "フランス語（カナダ）", "nativeName": "Français (Canada)"},
    "fr-BE": {"tag": "fr-BE", "name": "フランス語（ベルギー）", "nativeName": "Français (Belgique)"},
    "fr-CH": {"tag": "fr-CH", "name": "フランス語（スイス）", "nativeName": "Français (Suisse)"},
    "fr-LU": {"tag": "fr-LU", "name": "フランス語（ルクセンブルク）", "nativeName": "Français (Luxembourg)"},
    "fr-MC": {"tag": "fr-MC", "name": "フランス語（モナコ）", "nativeName": "Français (Monaco)"},
    "ko-KR": {"tag": "ko-KR", "name": "韓国語（韓国）", "nativeName": "한국어 (대한민국)"},
    "it-IT": {"tag": "it-IT", "name": "イタリア語（イタリア）", "nativeName": "Italiano (Italia)", "default": true },
    "it-CH": {"tag": "it-CH", "name": "イタリア語（スイス）", "nativeName": "Italiano (Svizzera)"},
    "nl-NL": {"tag": "nl-NL", "name": "オランダ語（オランダ）", "nativeName": "Nederlands (Nederland)"},
    "nl-BE": {"tag": "nl-BE", "name": "オランダ語（ベルギー）", "nativeName": "Nederlands (België)"},
    "pl-PL": {"tag": "pl-PL", "name": "ポーランド語（ポーランド）", "nativeName": "Polski (Polska)"},
    "vi-VN": {"tag": "vi-VN", "name": "ベトナム語（ベトナム）", "nativeName": "Tiếng Việt (Việt Nam)"},
    "tr-TR": {"tag": "tr-TR", "name": "トルコ語（トルコ）", "nativeName": "Türkçe (Türkiye)"},
    "th-TH": {"tag": "th-TH", "name": "タイ語（タイ）", "nativeName": "ไทย (ประเทศไทย)"},
    "el-GR": {"tag": "el-GR", "name": "ギリシャ語（ギリシャ）", "nativeName": "Ελληνικά (Ελλάδα)"},
    "cs-CZ": {"tag": "cs-CZ", "name": "チェコ語（チェコ）", "nativeName": "Čeština (Česká republika)"},
    "sv-SE": {"tag": "sv-SE", "name": "スウェーデン語（スウェーデン）", "nativeName": "Svenska (Sverige)", "default": true},
    "sv-FI": {"tag": "sv-FI", "name": "スウェーデン語（フィンランド）", "nativeName": "Svenska (Finland)"},
    "hu-HU": {"tag": "hu-HU", "name": "ハンガリー語（ハンガリー）", "nativeName": "Magyar (Magyarország)"},
    "fi-FI": {"tag": "fi-FI", "name": "フィンランド語（フィンランド）", "nativeName": "Suomi (Suomi)"},
    "da-DK": {"tag": "da-DK", "name": "デンマーク語（デンマーク）", "nativeName": "Dansk (Danmark)"},
    "nb-NO": {"tag": "nb-NO", "name": "ノルウェー語ブークモール（ノルウェー）", "nativeName": "Norsk Bokmål (Norge)"},
    "nn-NO": {"tag": "nn-NO", "name": "ノルウェー語ニーノシュク（ノルウェー）", "nativeName": "Norsk Nynorsk (Norge)"},
    "he-IL": {"tag": "he-IL", "name": "ヘブライ語（イスラエル）", "nativeName": "עברית (ישראל)"},
    "id-ID": {"tag": "id-ID", "name": "インドネシア語（インドネシア）", "nativeName": "Bahasa Indonesia (Indonesia)"},
    "ms-MY": {"tag": "ms-MY", "name": "マレー語（マレーシア）", "nativeName": "Bahasa Melayu (Malaysia)"},
    "ms-BN": {"tag": "ms-BN", "name": "マレー語（ブルネイ）", "nativeName": "Bahasa Melayu (Brunei)"},
    "ro-RO": {"tag": "ro-RO", "name": "ルーマニア語（ルーマニア）", "nativeName": "Română (România)"},
    "bg-BG": {"tag": "bg-BG", "name": "ブルガリア語（ブルガリア）", "nativeName": "Български (България)"},
    "uk-UA": {"tag": "uk-UA", "name": "ウクライナ語（ウクライナ）", "nativeName": "Українська (Україна)"},
    "sk-SK": {"tag": "sk-SK", "name": "スロバキア語（スロバキア）", "nativeName": "Slovenčina (Slovensko)"},
    "sl-SI": {"tag": "sl-SI", "name": "スロベニア語（スロベニア）", "nativeName": "Slovenščina (Slovenija)"},
    "hr-HR": {"tag": "hr-HR", "name": "クロアチア語（クロアチア）", "nativeName": "Hrvatski (Hrvatska)"},
    "ca-ES": {"tag": "ca-ES", "name": "カタルーニャ語（カタルーニャ）", "nativeName": "Català (Catalunya)"},
    "lt-LT": {"tag": "lt-LT", "name": "リトアニア語（リトアニア）", "nativeName": "Lietuvių (Lietuva)"},
    "lv-LV": {"tag": "lv-LV", "name": "ラトビア語（ラトビア）", "nativeName": "Latviešu (Latvija)"},
    "et-EE": {"tag": "et-EE", "name": "エストニア語（エストニア）", "nativeName": "Eesti (Eesti)"},
    "sq-AL": {"tag": "sq-AL", "name": "アルバニア語（アルバニア）", "nativeName": "Shqip (Shqipëri)"},
    "mk-MK": {"tag": "mk-MK", "name": "マケドニア語（北マケドニア）", "nativeName": "Македонски (Македонија)"},
    "be-BY": {"tag": "be-BY", "name": "ベラルーシ語（ベラルーシ）", "nativeName": "Беларуская (Беларусь)"},
    "is-IS": {"tag": "is-IS", "name": "アイスランド語（アイスランド）", "nativeName": "Íslenska (Ísland)"},
    "gl-ES": {"tag": "gl-ES", "name": "ガリシア語（ガリシア）", "nativeName": "Galego (Galicia)"},
    "eu-ES": {"tag": "eu-ES", "name": "バスク語（バスク地方）", "nativeName": "Euskara (Euskal Herria)"},
    "af-ZA": {"tag": "af-ZA", "name": "アフリカーンス語（南アフリカ）", "nativeName": "Afrikaans (Suid-Afrika)"},
    "sw-KE": {"tag": "sw-KE", "name": "スワヒリ語（ケニア）", "nativeName": "Kiswahili (Kenya)"},
    "ta-IN": {"tag": "ta-IN", "name": "タミル語（インド）", "nativeName": "தமிழ் (இந்தியா)"},
    "te-IN": {"tag": "te-IN", "name": "テルグ語（インド）", "nativeName": "తెలుగు (భారతదేశం)"},
    "kn-IN": {"tag": "kn-IN", "name": "カンナダ語（インド）", "nativeName": "ಕನ್ನಡ (ಭಾರತ)"},
    "mr-IN": {"tag": "mr-IN", "name": "マラーティー語（インド）", "nativeName": "मराठी (भारत)"},
    "gu-IN": {"tag": "gu-IN", "name": "グジャラート語（インド）", "nativeName": "ગુજરાતી (ભારત)"},
    "pa-IN": {"tag": "pa-IN", "name": "パンジャーブ語（インド）", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)"},
    "kok-IN": {"tag": "kok-IN", "name": "コンカニ語（インド）", "nativeName": "कोंकणी (भारत)"},
    "sa-IN": {"tag": "sa-IN", "name": "サンスクリット語（インド）", "nativeName": "संस्कृत (भारत)"},
    "ur-PK": {"tag": "ur-PK", "name": "ウルドゥー語（パキスタン）", "nativeName": "اردو (پاکستان)"},
    "fa-IR": {"tag": "fa-IR", "name": "ペルシア語（イラン）", "nativeName": "فارسی (ایران)"},
    "syr-SY": {"tag": "syr-SY", "name": "シリア語（シリア）", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)"},
    "div-MV": {"tag": "div-MV", "name": "ディベヒ語（モルディブ）", "nativeName": "ދިވެހި (މޯލްޑިވްސް)"},
    "ka-GE": {"tag": "ka-GE", "name": "グルジア語（ジョージア）", "nativeName": "ქართული (საქართველო)"},      
}

const { getTag, getTags, getDefaultTags } = createTagUtils(tags)
export {
    getTag, getTags,getDefaultTags
}
export * from './types'    