import { createTagUtils } from './utils'

export const tags = {
    "zh-CN": {"tag": "zh-CN", "name": "中国語（簡体字）", "nativeName": "简体中文", "primary": true},
    "zh-TW": {"tag": "zh-TW", "name": "中国語（繁体字 - 台湾）", "nativeName": "繁體中文(臺灣)", "primary": false},
    "zh-HK": {"tag": "zh-HK", "name": "中国語（繁体字 - 香港）", "nativeName": "繁體中文(香港)", "primary": false},
    "zh-MO": {"tag": "zh-MO", "name": "中国語（繁体字 - マカオ）", "nativeName": "繁體中文(Traditional Chinese - Macau)", "primary": false},
    "zh-SG": {"tag": "zh-SG", "name": "中国語（簡体字 - シンガポール）", "nativeName": "简体中文(Simplified Chinese - Singapore)", "primary": false},      
    "zh-CHS": {"tag": "zh-CHS", "name": "中国語（簡体字）", "nativeName": "简体中文", "primary": false},
    "zh-CHT": {"tag": "zh-CHT", "name": "中国語（繁体字）", "nativeName": "繁體中文(Traditional Chinese)", "primary": false},
    "en-US": {"tag": "en-US", "name": "英語（アメリカ）", "nativeName": "English (United States)", "primary": true },
    "en-GB": {"tag": "en-GB", "name": "英語（イギリス）", "nativeName": "English (United Kingdom)", "primary": false},
    "en-CA": {"tag": "en-CA", "name": "英語（カナダ）", "nativeName": "English (Canada)", "primary": false},
    "en-AU": {"tag": "en-AU", "name": "英語（オーストラリア）", "nativeName": "English (Australia)", "primary": false},
    "en-IN": {"tag": "en-IN", "name": "英語（インド）", "nativeName": "English (India)", "primary": false},
    "en-ZA": {"tag": "en-ZA", "name": "英語（南アフリカ）", "nativeName": "English (South Africa)", "primary": false},
    "en-NZ": {"tag": "en-NZ", "name": "英語（ニュージーランド）", "nativeName": "English (New Zealand)", "primary": false},
    "en-IE": {"tag": "en-IE", "name": "英語（アイルランド）", "nativeName": "English (Ireland)", "primary": false},
    "en-PH": {"tag": "en-PH", "name": "英語（フィリピン）", "nativeName": "English (Philippines)", "primary": false},
    "en-ZW": {"tag": "en-ZW", "name": "英語（ジンバブエ）", "nativeName": "English (Zimbabwe)", "primary": false},
    "en-BZ": {"tag": "en-BZ", "name": "英語（ベリーズ）", "nativeName": "English (Belize)", "primary": false},
    "en-CB": {"tag": "en-CB", "name": "英語（カリブ海地域）", "nativeName": "English (Caribbean)", "primary": false},
    "en-JM": {"tag": "en-JM", "name": "英語（ジャマイカ）", "nativeName": "English (Jamaica)", "primary": false},
    "en-TT": {"tag": "en-TT", "name": "英語（トリニダード・トバゴ）", "nativeName": "English (Trinidad and Tobago)", "primary": false},
    "hi-IN": {"tag": "hi-IN", "name": "ヒンディー語（インド）", "nativeName": "हिन्दी (Hindi)", "primary": false},
    "es-ES": {"tag": "es-ES", "name": "スペイン語（スペイン）", "nativeName": "Español (España)", "primary": true },
    "es-MX": {"tag": "es-MX", "name": "スペイン語（メキシコ）", "nativeName": "Español (México)", "primary": false},
    "es-AR": {"tag": "es-AR", "name": "スペイン語（アルゼンチン）", "nativeName": "Español (Argentina)", "primary": false},
    "es-CO": {"tag": "es-CO", "name": "スペイン語（コロンビア）", "nativeName": "Español (Colombia)", "primary": false},
    "es-PE": {"tag": "es-PE", "name": "スペイン語（ペルー）", "nativeName": "Español (Perú)", "primary": false},
    "es-VE": {"tag": "es-VE", "name": "スペイン語（ベネズエラ）", "nativeName": "Español (Venezuela)", "primary": false},
    "es-CL": {"tag": "es-CL", "name": "スペイン語（チリ）", "nativeName": "Español (Chile)", "primary": false},
    "es-EC": {"tag": "es-EC", "name": "スペイン語（エクアドル）", "nativeName": "Español (Ecuador)", "primary": false},
    "es-GT": {"tag": "es-GT", "name": "スペイン語（グアテマラ）", "nativeName": "Español (Guatemala)", "primary": false},
    "es-CU": {"tag": "es-CU", "name": "スペイン語（キューバ）", "nativeName": "Español (Cuba)", "primary": false},
    "es-BO": {"tag": "es-BO", "name": "スペイン語（ボリビア）", "nativeName": "Español (Bolivia)", "primary": false},
    "es-DO": {"tag": "es-DO", "name": "スペイン語（ドミニカ共和国）", "nativeName": "Español (República Dominicana)", "primary": false},
    "es-HN": {"tag": "es-HN", "name": "スペイン語（ホンジュラス）", "nativeName": "Español (Honduras)", "primary": false},
    "es-PY": {"tag": "es-PY", "name": "スペイン語（パラグアイ）", "nativeName": "Español (Paraguay)", "primary": false},
    "es-SV": {"tag": "es-SV", "name": "スペイン語（エルサルバドル）", "nativeName": "Español (El Salvador)", "primary": false},
    "es-NI": {"tag": "es-NI", "name": "スペイン語（ニカラグア）", "nativeName": "Español (Nicaragua)", "primary": false},
    "es-PR": {"tag": "es-PR", "name": "スペイン語（プエルトリコ）", "nativeName": "Español (Puerto Rico)", "primary": false},
    "es-UY": {"tag": "es-UY", "name": "スペイン語（ウルグアイ）", "nativeName": "Español (Uruguay)", "primary": false},
    "es-PA": {"tag": "es-PA", "name": "スペイン語（パナマ）", "nativeName": "Español (Panamá)", "primary": false},
    "es-CR": {"tag": "es-CR", "name": "スペイン語（コスタリカ）", "nativeName": "Español (Costa Rica)", "primary": false},
    "ar-EG": {"tag": "ar-EG", "name": "アラビア語（エジプト）", "nativeName": "العربية (مصر)", "primary": true },
    "ar-SA": {"tag": "ar-SA", "name": "アラビア語（サウジアラビア）", "nativeName": "العربية (السعودية)", "primary": false},
    "ar-DZ": {"tag": "ar-DZ", "name": "アラビア語（アルジェリア）", "nativeName": "العربية (الجزائر)", "primary": false},
    "ar-MA": {"tag": "ar-MA", "name": "アラビア語（モロッコ）", "nativeName": "العربية (المغرب)", "primary": false},
    "ar-IQ": {"tag": "ar-IQ", "name": "アラビア語（イラク）", "nativeName": "العربية (العراق)", "primary": false},
    "ar-SD": {"tag": "ar-SD", "name": "アラビア語（スーダン）", "nativeName": "العربية (السودان)", "primary": false},
    "ar-YE": {"tag": "ar-YE", "name": "アラビア語（イエメン）", "nativeName": "العربية (اليمن)", "primary": false}, 
    "ar-SY": {"tag": "ar-SY", "name": "アラビア語（シリア）", "nativeName": "العربية (سوريا)", "primary": false},
    "ar-TN": {"tag": "ar-TN", "name": "アラビア語（チュニジア）", "nativeName": "العربية (تونس)", "primary": false},
    "ar-LY": {"tag": "ar-LY", "name": "アラビア語（リビア）", "nativeName": "العربية (ليبيا)", "primary": false},
    "ar-JO": {"tag": "ar-JO", "name": "アラビア語（ヨルダン）", "nativeName": "العربية (الأردن)", "primary": false},
    "ar-LB": {"tag": "ar-LB", "name": "アラビア語（レバノン）", "nativeName": "العربية (لبنان)", "primary": false},
    "ar-KW": {"tag": "ar-KW", "name": "アラビア語（クウェート）", "nativeName": "العربية (الكويت)", "primary": false},
    "ar-AE": {"tag": "ar-AE", "name": "アラビア語（アラブ首長国連邦）", "nativeName": "العربية (الإمارات)", "primary": false},
    "ar-BH": {"tag": "ar-BH", "name": "アラビア語（バーレーン）", "nativeName": "العربية (البحرين)", "primary": false},
    "ar-QA": {"tag": "ar-QA", "name": "アラビア語（カタール）", "nativeName": "العربية (قطر)", "primary": false},
    "ar-OM": {"tag": "ar-OM", "name": "アラビア語（オマーン）", "nativeName": "العربية (عمان)", "primary": false},
    "pt-BR": {"tag": "pt-BR", "name": "ポルトガル語（ブラジル）", "nativeName": "Português (Brasil)", "primary": false},
    "pt-PT": {"tag": "pt-PT", "name": "ポルトガル語（ポルトガル）", "nativeName": "Português (Portugal)", "primary": true },
    "ru-RU": {"tag": "ru-RU", "name": "ロシア語（ロシア）", "nativeName": "Русский (Россия)", "primary": true },
    "ja-JP": {"tag": "ja-JP", "name": "日本語（日本）", "nativeName": "日本語 (日本)", "primary": true },
    "de-DE": {"tag": "de-DE", "name": "ドイツ語（ドイツ）", "nativeName": "Deutsch (Deutschland)", "primary": true },
    "de-AT": {"tag": "de-AT", "name": "ドイツ語（オーストリア）", "nativeName": "Deutsch (Österreich)", "primary": false},
    "de-CH": {"tag": "de-CH", "name": "ドイツ語（スイス）", "nativeName": "Deutsch (Schweiz)", "primary": false},
    "fr-FR": {"tag": "fr-FR", "name": "フランス語（フランス）", "nativeName": "Français (France)", "primary": true },
    "fr-CA": {"tag": "fr-CA", "name": "フランス語（カナダ）", "nativeName": "Français (Canada)", "primary": false},
    "fr-BE": {"tag": "fr-BE", "name": "フランス語（ベルギー）", "nativeName": "Français (Belgique)", "primary": false},
    "fr-CH": {"tag": "fr-CH", "name": "フランス語（スイス）", "nativeName": "Français (Suisse)", "primary": false},
    "fr-LU": {"tag": "fr-LU", "name": "フランス語（ルクセンブルク）", "nativeName": "Français (Luxembourg)", "primary": false},
    "fr-MC": {"tag": "fr-MC", "name": "フランス語（モナコ）", "nativeName": "Français (Monaco)", "primary": false},
    "ko-KR": {"tag": "ko-KR", "name": "韓国語（韓国）", "nativeName": "한국어 (대한민국)", "primary": true},
    "it-IT": {"tag": "it-IT", "name": "イタリア語（イタリア）", "nativeName": "Italiano (Italia)", "primary": true  },
    "it-CH": {"tag": "it-CH", "name": "イタリア語（スイス）", "nativeName": "Italiano (Svizzera)", "primary": false},
    "nl-NL": {"tag": "nl-NL", "name": "オランダ語（オランダ）", "nativeName": "Nederlands (Nederland)", "primary": true},
    "nl-BE": {"tag": "nl-BE", "name": "オランダ語（ベルギー）", "nativeName": "Nederlands (België)", "primary": false},
    "pl-PL": {"tag": "pl-PL", "name": "ポーランド語（ポーランド）", "nativeName": "Polski (Polska)", "primary": false},
    "vi-VN": {"tag": "vi-VN", "name": "ベトナム語（ベトナム）", "nativeName": "Tiếng Việt (Việt Nam)", "primary": false},
    "tr-TR": {"tag": "tr-TR", "name": "トルコ語（トルコ）", "nativeName": "Türkçe (Türkiye)", "primary": false},
    "th-TH": {"tag": "th-TH", "name": "タイ語（タイ）", "nativeName": "ไทย (ประเทศไทย)", "primary": false},
    "el-GR": {"tag": "el-GR", "name": "ギリシャ語（ギリシャ）", "nativeName": "Ελληνικά (Ελλάδα)", "primary": false},
    "cs-CZ": {"tag": "cs-CZ", "name": "チェコ語（チェコ）", "nativeName": "Čeština (Česká republika)", "primary": false},
    "sv-SE": {"tag": "sv-SE", "name": "スウェーデン語（スウェーデン）", "nativeName": "Svenska (Sverige)", "primary": false },
    "sv-FI": {"tag": "sv-FI", "name": "スウェーデン語（フィンランド）", "nativeName": "Svenska (Finland)", "primary": false},
    "hu-HU": {"tag": "hu-HU", "name": "ハンガリー語（ハンガリー）", "nativeName": "Magyar (Magyarország)", "primary": false},
    "fi-FI": {"tag": "fi-FI", "name": "フィンランド語（フィンランド）", "nativeName": "Suomi (Suomi)", "primary": false},
    "da-DK": {"tag": "da-DK", "name": "デンマーク語（デンマーク）", "nativeName": "Dansk (Danmark)", "primary": false},
    "nb-NO": {"tag": "nb-NO", "name": "ノルウェー語ブークモール（ノルウェー）", "nativeName": "Norsk Bokmål (Norge)", "primary": false},
    "nn-NO": {"tag": "nn-NO", "name": "ノルウェー語ニーノシュク（ノルウェー）", "nativeName": "Norsk Nynorsk (Norge)", "primary": false},
    "he-IL": {"tag": "he-IL", "name": "ヘブライ語（イスラエル）", "nativeName": "עברית (ישראל)", "primary": false},
    "id-ID": {"tag": "id-ID", "name": "インドネシア語（インドネシア）", "nativeName": "Bahasa Indonesia (Indonesia)", "primary": false},
    "ms-MY": {"tag": "ms-MY", "name": "マレー語（マレーシア）", "nativeName": "Bahasa Melayu (Malaysia)", "primary": false},
    "ms-BN": {"tag": "ms-BN", "name": "マレー語（ブルネイ）", "nativeName": "Bahasa Melayu (Brunei)", "primary": false},
    "ro-RO": {"tag": "ro-RO", "name": "ルーマニア語（ルーマニア）", "nativeName": "Română (România)", "primary": false},
    "bg-BG": {"tag": "bg-BG", "name": "ブルガリア語（ブルガリア）", "nativeName": "Български (България)", "primary": false},
    "uk-UA": {"tag": "uk-UA", "name": "ウクライナ語（ウクライナ）", "nativeName": "Українська (Україна)", "primary": false},
    "sk-SK": {"tag": "sk-SK", "name": "スロバキア語（スロバキア）", "nativeName": "Slovenčina (Slovensko)", "primary": false},
    "sl-SI": {"tag": "sl-SI", "name": "スロベニア語（スロベニア）", "nativeName": "Slovenščina (Slovenija)", "primary": false},
    "hr-HR": {"tag": "hr-HR", "name": "クロアチア語（クロアチア）", "nativeName": "Hrvatski (Hrvatska)", "primary": false},
    "ca-ES": {"tag": "ca-ES", "name": "カタルーニャ語（カタルーニャ）", "nativeName": "Català (Catalunya)", "primary": false},
    "lt-LT": {"tag": "lt-LT", "name": "リトアニア語（リトアニア）", "nativeName": "Lietuvių (Lietuva)", "primary": false},
    "lv-LV": {"tag": "lv-LV", "name": "ラトビア語（ラトビア）", "nativeName": "Latviešu (Latvija)", "primary": false},
    "et-EE": {"tag": "et-EE", "name": "エストニア語（エストニア）", "nativeName": "Eesti (Eesti)", "primary": false},
    "sq-AL": {"tag": "sq-AL", "name": "アルバニア語（アルバニア）", "nativeName": "Shqip (Shqipëri)", "primary": false},
    "mk-MK": {"tag": "mk-MK", "name": "マケドニア語（北マケドニア）", "nativeName": "Македонски (Македонија)", "primary": false},
    "be-BY": {"tag": "be-BY", "name": "ベラルーシ語（ベラルーシ）", "nativeName": "Беларуская (Беларусь)", "primary": false},
    "is-IS": {"tag": "is-IS", "name": "アイスランド語（アイスランド）", "nativeName": "Íslenska (Ísland)", "primary": false},
    "gl-ES": {"tag": "gl-ES", "name": "ガリシア語（ガリシア）", "nativeName": "Galego (Galicia)", "primary": false},
    "eu-ES": {"tag": "eu-ES", "name": "バスク語（バスク地方）", "nativeName": "Euskara (Euskal Herria)", "primary": false},
    "af-ZA": {"tag": "af-ZA", "name": "アフリカーンス語（南アフリカ）", "nativeName": "Afrikaans (Suid-Afrika)", "primary": false},
    "sw-KE": {"tag": "sw-KE", "name": "スワヒリ語（ケニア）", "nativeName": "Kiswahili (Kenya)", "primary": false},
    "ta-IN": {"tag": "ta-IN", "name": "タミル語（インド）", "nativeName": "தமிழ் (இந்தியா)", "primary": false},
    "te-IN": {"tag": "te-IN", "name": "テルグ語（インド）", "nativeName": "తెలుగు (భారతదేశం)", "primary": false},
    "kn-IN": {"tag": "kn-IN", "name": "カンナダ語（インド）", "nativeName": "ಕನ್ನಡ (ಭಾರತ)", "primary": false},
    "mr-IN": {"tag": "mr-IN", "name": "マラーティー語（インド）", "nativeName": "मराठी (भारत)", "primary": false},
    "gu-IN": {"tag": "gu-IN", "name": "グジャラート語（インド）", "nativeName": "ગુજરાતી (ભારત)", "primary": false},
    "pa-IN": {"tag": "pa-IN", "name": "パンジャーブ語（インド）", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)", "primary": false},
    "kok-IN": {"tag": "kok-IN", "name": "コンカニ語（インド）", "nativeName": "कोंकणी (भारत)", "primary": false},
    "sa-IN": {"tag": "sa-IN", "name": "サンスクリット語（インド）", "nativeName": "संस्कृत (भारत)", "primary": false},
    "ur-PK": {"tag": "ur-PK", "name": "ウルドゥー語（パキスタン）", "nativeName": "اردو (پاکستان)", "primary": false},
    "fa-IR": {"tag": "fa-IR", "name": "ペルシア語（イラン）", "nativeName": "فارسی (ایران)", "primary": false},
    "syr-SY": {"tag": "syr-SY", "name": "シリア語（シリア）", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)", "primary": false},
    "div-MV": {"tag": "div-MV", "name": "ディベヒ語（モルディブ）", "nativeName": "ދިވެހި (މޯލްޑިވްސް)", "primary": false},
    "ka-GE": {"tag": "ka-GE", "name": "グルジア語（ジョージア）", "nativeName": "ქართული (საქართველო)", "primary": false},      
}

const { getTag, getTags, getPrimaryTags } = createTagUtils(tags)
export {
    getTag, getTags,getPrimaryTags
}
export * from './types'    