import { createTagUtils } from './utils'

export const tags = {
        "zh-CN": {"tag": "zh-CN", "name": "Chinees (Vereenvoudigd)", "nativeName": "简体中文", "primary": true },
        "zh-TW": {"tag": "zh-TW", "name": "Chinees (Traditioneel - Taiwan)", "nativeName": "繁體中文(臺灣)", "primary": false },
        "zh-HK": {"tag": "zh-HK", "name": "Chinees (Traditioneel - Hong Kong)", "nativeName": "繁體中文(香港)", "primary": false },
        "zh-MO": {"tag": "zh-MO", "name": "Chinees (Traditioneel - Macau)", "nativeName": "繁體中文(Traditional Chinese - Macau)", "primary": false },
        "zh-SG": {"tag": "zh-SG", "name": "Chinees (Vereenvoudigd - Singapore)", "nativeName": "简体中文(Simplified Chinese - Singapore)", "primary": false },      
        "zh-CHS": {"tag": "zh-CHS", "name": "Chinees (Vereenvoudigd)", "nativeName": "简体中文", "primary": false },
        "zh-CHT": {"tag": "zh-CHT", "name": "Chinees (Traditioneel)", "nativeName": "繁體中文(Traditional Chinese)", "primary": false },
        "en-US": {"tag": "en-US", "name": "Engels (Verenigde Staten)", "nativeName": "English (United States)", "primary": true },
        "en-GB": {"tag": "en-GB", "name": "Engels (Verenigd Koninkrijk)", "nativeName": "English (United Kingdom)", "primary": false },
        "en-CA": {"tag": "en-CA", "name": "Engels (Canada)", "nativeName": "English (Canada)", "primary": false },
        "en-AU": {"tag": "en-AU", "name": "Engels (Australië)", "nativeName": "English (Australia)", "primary": false },
        "en-IN": {"tag": "en-IN", "name": "Engels (India)", "nativeName": "English (India)", "primary": false },
        "en-ZA": {"tag": "en-ZA", "name": "Engels (Zuid-Afrika)", "nativeName": "English (South Africa)", "primary": false },
        "en-NZ": {"tag": "en-NZ", "name": "Engels (Nieuw-Zeeland)", "nativeName": "English (New Zealand)", "primary": false },
        "en-IE": {"tag": "en-IE", "name": "Engels (Ierland)", "nativeName": "English (Ireland)", "primary": false },
        "en-PH": {"tag": "en-PH", "name": "Engels (Filipijnen)", "nativeName": "English (Philippines)", "primary": false },
        "en-ZW": {"tag": "en-ZW", "name": "Engels (Zimbabwe)", "nativeName": "English (Zimbabwe)", "primary": false },
        "en-BZ": {"tag": "en-BZ", "name": "Engels (Belize)", "nativeName": "English (Belize)", "primary": false },
        "en-CB": {"tag": "en-CB", "name": "Engels (Caribisch gebied)", "nativeName": "English (Caribbean)", "primary": false },
        "en-JM": {"tag": "en-JM", "name": "Engels (Jamaica)", "nativeName": "English (Jamaica)", "primary": false },
        "en-TT": {"tag": "en-TT", "name": "Engels (Trinidad en Tobago)", "nativeName": "English (Trinidad and Tobago)", "primary": false },
        "hi-IN": {"tag": "hi-IN", "name": "Hindi (India)", "nativeName": "हिन्दी (Hindi)", "primary": false },
        "es-ES": {"tag": "es-ES", "name": "Spaans (Spanje)", "nativeName": "Español (España)", "primary": true },
        "es-MX": {"tag": "es-MX", "name": "Spaans (Mexico)", "nativeName": "Español (México)", "primary": false },
        "es-AR": {"tag": "es-AR", "name": "Spaans (Argentinië)", "nativeName": "Español (Argentina)", "primary": false },
        "es-CO": {"tag": "es-CO", "name": "Spaans (Colombia)", "nativeName": "Español (Colombia)", "primary": false },
        "es-PE": {"tag": "es-PE", "name": "Spaans (Peru)", "nativeName": "Español (Perú)", "primary": false },
        "es-VE": {"tag": "es-VE", "name": "Spaans (Venezuela)", "nativeName": "Español (Venezuela)", "primary": false },
        "es-CL": {"tag": "es-CL", "name": "Spaans (Chili)", "nativeName": "Español (Chile)", "primary": false },
        "es-EC": {"tag": "es-EC", "name": "Spaans (Ecuador)", "nativeName": "Español (Ecuador)", "primary": false },
        "es-GT": {"tag": "es-GT", "name": "Spaans (Guatemala)", "nativeName": "Español (Guatemala)", "primary": false },
        "es-CU": {"tag": "es-CU", "name": "Spaans (Cuba)", "nativeName": "Español (Cuba)", "primary": false },
        "es-BO": {"tag": "es-BO", "name": "Spaans (Bolivia)", "nativeName": "Español (Bolivia)", "primary": false },
        "es-DO": {"tag": "es-DO", "name": "Spaans (Dominicaanse Republiek)", "nativeName": "Español (República Dominicana)", "primary": false },
        "es-HN": {"tag": "es-HN", "name": "Spaans (Honduras)", "nativeName": "Español (Honduras)", "primary": false },
        "es-PY": {"tag": "es-PY", "name": "Spaans (Paraguay)", "nativeName": "Español (Paraguay)", "primary": false },
        "es-SV": {"tag": "es-SV", "name": "Spaans (El Salvador)", "nativeName": "Español (El Salvador)", "primary": false },
        "es-NI": {"tag": "es-NI", "name": "Spaans (Nicaragua)", "nativeName": "Español (Nicaragua)", "primary": false },
        "es-PR": {"tag": "es-PR", "name": "Spaans (Puerto Rico)", "nativeName": "Español (Puerto Rico)", "primary": false },
        "es-UY": {"tag": "es-UY", "name": "Spaans (Uruguay)", "nativeName": "Español (Uruguay)", "primary": false },
        "es-PA": {"tag": "es-PA", "name": "Spaans (Panama)", "nativeName": "Español (Panamá)", "primary": false },
        "es-CR": {"tag": "es-CR", "name": "Spaans (Costa Rica)", "nativeName": "Español (Costa Rica)", "primary": false },
        "ar-EG": {"tag": "ar-EG", "name": "Arabisch (Egypte)", "nativeName": "العربية (مصر)", "primary": true },
        "ar-SA": {"tag": "ar-SA", "name": "Arabisch (Saoedi-Arabië)", "nativeName": "العربية (السعودية)", "primary": false },
        "ar-DZ": {"tag": "ar-DZ", "name": "Arabisch (Algerije)", "nativeName": "العربية (الجزائر)", "primary": false },
        "ar-MA": {"tag": "ar-MA", "name": "Arabisch (Marokko)", "nativeName": "العربية (المغرب)", "primary": false },
        "ar-IQ": {"tag": "ar-IQ", "name": "Arabisch (Irak)", "nativeName": "العربية (العراق)", "primary": false },
        "ar-SD": {"tag": "ar-SD", "name": "Arabisch (Soedan)", "nativeName": "العربية (السودان)", "primary": false },
        "ar-YE": {"tag": "ar-YE", "name": "Arabisch (Jemen)", "nativeName": "العربية (اليمن)", "primary": false },
        "ar-SY": {"tag": "ar-SY", "name": "Arabisch (Syrië)", "nativeName": "العربية (سوريا)", "primary": false },
        "ar-TN": {"tag": "ar-TN", "name": "Arabisch (Tunesië)", "nativeName": "العربية (تونس)", "primary": false },
        "ar-LY": {"tag": "ar-LY", "name": "Arabisch (Libië)", "nativeName": "العربية (ليبيا)", "primary": false },
        "ar-JO": {"tag": "ar-JO", "name": "Arabisch (Jordanië)", "nativeName": "العربية (الأردن)", "primary": false },
        "ar-LB": {"tag": "ar-LB", "name": "Arabisch (Libanon)", "nativeName": "العربية (لبنان)", "primary": false },
        "ar-KW": {"tag": "ar-KW", "name": "Arabisch (Koeweit)", "nativeName": "العربية (الكويت)", "primary": false },
        "ar-AE": {"tag": "ar-AE", "name": "Arabisch (Verenigde Arabische Emiraten)", "nativeName": "العربية (الإمارات)", "primary": false },
        "ar-BH": {"tag": "ar-BH", "name": "Arabisch (Bahrein)", "nativeName": "العربية (البحرين)", "primary": false },
        "ar-QA": {"tag": "ar-QA", "name": "Arabisch (Qatar)", "nativeName": "العربية (قطر)", "primary": false },
        "ar-OM": {"tag": "ar-OM", "name": "Arabisch (Oman)", "nativeName": "العربية (عمان)", "primary": false },
        "pt-BR": {"tag": "pt-BR", "name": "Portugees (Brazilië)", "nativeName": "Português (Brasil)", "primary": false },
        "pt-PT": {"tag": "pt-PT", "name": "Portugees (Portugal)", "nativeName": "Português (Portugal)", "primary": true },
        "ru-RU": {"tag": "ru-RU", "name": "Russisch (Rusland)", "nativeName": "Русский (Россия)", "primary": true },
        "ja-JP": {"tag": "ja-JP", "name": "Japans (Japan)", "nativeName": "日本語 (日本)", "primary": true },
        "de-DE": {"tag": "de-DE", "name": "Duits (Duitsland)", "nativeName": "Deutsch (Deutschland)", "primary": true },
        "de-AT": {"tag": "de-AT", "name": "Duits (Oostenrijk)", "nativeName": "Deutsch (Österreich)", "primary": false },
        "de-CH": {"tag": "de-CH", "name": "Duits (Zwitserland)", "nativeName": "Deutsch (Schweiz)", "primary": false },
        "fr-FR": {"tag": "fr-FR", "name": "Frans (Frankrijk)", "nativeName": "Français (France)", "primary": true },
        "fr-CA": {"tag": "fr-CA", "name": "Frans (Canada)", "nativeName": "Français (Canada)", "primary": false },
        "fr-BE": {"tag": "fr-BE", "name": "Frans (België)", "nativeName": "Français (Belgique)", "primary": false },
        "fr-CH": {"tag": "fr-CH", "name": "Frans (Zwitserland)", "nativeName": "Français (Suisse)", "primary": false },
        "fr-LU": {"tag": "fr-LU", "name": "Frans (Luxemburg)", "nativeName": "Français (Luxembourg)", "primary": false },
        "fr-MC": {"tag": "fr-MC", "name": "Frans (Monaco)", "nativeName": "Français (Monaco)", "primary": false },
        "ko-KR": {"tag": "ko-KR", "name": "Koreaans (Zuid-Korea)", "nativeName": "한국어 (대한민국)", "primary": true },
        "it-IT": {"tag": "it-IT", "name": "Italiaans (Italië)", "nativeName": "Italiano (Italia)", "primary": true },
        "it-CH": {"tag": "it-CH", "name": "Italiaans (Zwitserland)", "nativeName": "Italiano (Svizzera)", "primary": false },
        "nl-NL": {"tag": "nl-NL", "name": "Nederlands (Nederland)", "nativeName": "Nederlands (Nederland)", "primary": true },
        "nl-BE": {"tag": "nl-BE", "name": "Nederlands (België)", "nativeName": "Nederlands (België)", "primary": false },
        "pl-PL": {"tag": "pl-PL", "name": "Pools (Polen)", "nativeName": "Polski (Polska)", "primary": false },
        "vi-VN": {"tag": "vi-VN", "name": "Vietnamees (Vietnam)", "nativeName": "Tiếng Việt (Việt Nam)", "primary": false },
        "tr-TR": {"tag": "tr-TR", "name": "Turks (Turkije)", "nativeName": "Türkçe (Türkiye)", "primary": false },
        "th-TH": {"tag": "th-TH", "name": "Thai (Thailand)", "nativeName": "ไทย (ประเทศไทย)", "primary": false },
        "el-GR": {"tag": "el-GR", "name": "Grieks (Griekenland)", "nativeName": "Ελληνικά (Ελλάδα)", "primary": false },
        "cs-CZ": {"tag": "cs-CZ", "name": "Tsjechisch (Tsjechië)", "nativeName": "Čeština (Česká republika)", "primary": false },
        "sv-SE": {"tag": "sv-SE", "name": "Zweeds (Zweden)", "nativeName": "Svenska (Sverige)", "primary": false },
        "sv-FI": {"tag": "sv-FI", "name": "Zweeds (Finland)", "nativeName": "Svenska (Finland)", "primary": false },
        "hu-HU": {"tag": "hu-HU", "name": "Hongaars (Hongarije)", "nativeName": "Magyar (Magyarország)", "primary": false },
        "fi-FI": {"tag": "fi-FI", "name": "Fins (Finland)", "nativeName": "Suomi (Suomi)", "primary": false },
        "da-DK": {"tag": "da-DK", "name": "Deens (Denemarken)", "nativeName": "Dansk (Danmark)", "primary": false },
        "nb-NO": {"tag": "nb-NO", "name": "Noors Bokmål (Noorwegen)", "nativeName": "Norsk Bokmål (Norge)", "primary": false },
        "nn-NO": {"tag": "nn-NO", "name": "Noors Nynorsk (Noorwegen)", "nativeName": "Norsk Nynorsk (Norge)", "primary": false },
        "he-IL": {"tag": "he-IL", "name": "Hebreeuws (Israël)", "nativeName": "עברית (ישראל)", "primary": false },
        "id-ID": {"tag": "id-ID", "name": "Indonesisch (Indonesië)", "nativeName": "Bahasa Indonesia (Indonesia)", "primary": false },
        "ms-MY": {"tag": "ms-MY", "name": "Maleis (Maleisië)", "nativeName": "Bahasa Melayu (Malaysia)", "primary": false },
        "ms-BN": {"tag": "ms-BN", "name": "Maleis (Brunei)", "nativeName": "Bahasa Melayu (Brunei)", "primary": false },
        "ro-RO": {"tag": "ro-RO", "name": "Roemeens (Roemenië)", "nativeName": "Română (România)", "primary": false },
        "bg-BG": {"tag": "bg-BG", "name": "Bulgaars (Bulgarije)", "nativeName": "Български (България)", "primary": false },        
        "uk-UA": {"tag": "uk-UA", "name": "Oekraïens (Oekraïne)", "nativeName": "Українська (Україна)", "primary": false },
        "sk-SK": {"tag": "sk-SK", "name": "Slowaaks (Slowakije)", "nativeName": "Slovenčina (Slovensko)", "primary": false },
        "sl-SI": {"tag": "sl-SI", "name": "Sloveens (Slovenië)", "nativeName": "Slovenščina (Slovenija)", "primary": false },
        "hr-HR": {"tag": "hr-HR", "name": "Kroatisch (Kroatië)", "nativeName": "Hrvatski (Hrvatska)", "primary": false },
        "ca-ES": {"tag": "ca-ES", "name": "Catalaans (Catalonië)", "nativeName": "Català (Catalunya)", "primary": false },
        "lt-LT": {"tag": "lt-LT", "name": "Litouws (Litouwen)", "nativeName": "Lietuvių (Lietuva)", "primary": false },
        "lv-LV": {"tag": "lv-LV", "name": "Lets (Letland)", "nativeName": "Latviešu (Latvija)", "primary": false },
        "et-EE": {"tag": "et-EE", "name": "Estisch (Estland)", "nativeName": "Eesti (Eesti)", "primary": false },
        "sq-AL": {"tag": "sq-AL", "name": "Albanees (Albanië)", "nativeName": "Shqip (Shqipëri)", "primary": false },
        "mk-MK": {"tag": "mk-MK", "name": "Macedonisch (Noord-Macedonië)", "nativeName": "Македонски (Македонија)", "primary": false },
        "be-BY": {"tag": "be-BY", "name": "Wit-Russisch (Wit-Rusland)", "nativeName": "Беларуская (Беларусь)", "primary": false },
        "is-IS": {"tag": "is-IS", "name": "IJslands (IJsland)", "nativeName": "Íslenska (Ísland)", "primary": false },
        "gl-ES": {"tag": "gl-ES", "name": "Galicisch (Galicië)", "nativeName": "Galego (Galicia)", "primary": false },
        "eu-ES": {"tag": "eu-ES", "name": "Baskisch (Baskenland)", "nativeName": "Euskara (Euskal Herria)", "primary": false },
        "af-ZA": {"tag": "af-ZA", "name": "Afrikaans (Zuid-Afrika)", "nativeName": "Afrikaans (Suid-Afrika)", "primary": false },
        "sw-KE": {"tag": "sw-KE", "name": "Swahili (Kenia)", "nativeName": "Kiswahili (Kenya)", "primary": false },
        "ta-IN": {"tag": "ta-IN", "name": "Tamil (India)", "nativeName": "தமிழ் (இந்தியா)", "primary": false },
        "te-IN": {"tag": "te-IN", "name": "Telugu (India)", "nativeName": "తెలుగు (భారతదేశం)", "primary": false },
        "kn-IN": {"tag": "kn-IN", "name": "Kannada (India)", "nativeName": "ಕನ್ನಡ (ಭಾರತ)", "primary": false },
        "mr-IN": {"tag": "mr-IN", "name": "Marathi (India)", "nativeName": "मराठी (भारत)", "primary": false },
        "gu-IN": {"tag": "gu-IN", "name": "Gujarati (India)", "nativeName": "ગુજરાતી (ભારત)", "primary": false },
        "pa-IN": {"tag": "pa-IN", "name": "Punjabi (India)", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)", "primary": false },
        "kok-IN": {"tag": "kok-IN", "name": "Konkani (India)", "nativeName": "कोंकणी (भारत)", "primary": false },
        "sa-IN": {"tag": "sa-IN", "name": "Sanskriet (India)", "nativeName": "संस्कृत (भारत)", "primary": false },
        "ur-PK": {"tag": "ur-PK", "name": "Urdu (Pakistan)", "nativeName": "اردو (پاکستان)", "primary": false },
        "fa-IR": {"tag": "fa-IR", "name": "Perzisch (Iran)", "nativeName": "فارسی (ایران)", "primary": false },
        "syr-SY": {"tag": "syr-SY", "name": "Syrisch (Syrië)", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)", "primary": false },
        "div-MV": {"tag": "div-MV", "name": "Dhivehi (Maldiven)", "nativeName": "ދިވެހި (މޯލްޑިވްސް)", "primary": false },
        "ka-GE": {"tag": "ka-GE", "name": "Georgisch (Georgië)", "nativeName": "ქართული (საქართველო)", "primary": false },      
}


const { getTag, getTags, getPrimaryTags } = createTagUtils(tags)
export {
    getTag, getTags,getPrimaryTags
}
export * from './types'    