import { createTagUtils } from './utils'

export const tags = {
    "zh-CN": {"tag": "zh-CN", "name": "Chiński (uproszczony)", "nativeName": "简体中文", "primary": true },
    "zh-TW": {"tag": "zh-TW", "name": "Chiński (tradycyjny - Tajwan)", "nativeName": "繁體中文(中國臺灣)", "primary": false},
    "zh-HK": {"tag": "zh-HK", "name": "Chiński (tradycyjny - Hongkong)", "nativeName": "繁體中文(中國香港)", "primary": false},
    "zh-MO": {"tag": "zh-MO", "name": "Chiński (tradycyjny - Makau)", "nativeName": "繁體中文(中國澳門)", "primary": false},
    "zh-SG": {"tag": "zh-SG", "name": "Chiński (uproszczony - Singapur)", "nativeName": "简体中文(新加坡)", "primary": false},      
    "zh-CHS": {"tag": "zh-CHS", "name": "Chiński (uproszczony)", "nativeName": "简体中文", "primary": false},
    "zh-CHT": {"tag": "zh-CHT", "name": "Chiński (tradycyjny)", "nativeName": "繁體中文(Traditional Chinese)", "primary": false},
    "en-US": {"tag": "en-US", "name": "Angielski (Stany Zjednoczone)", "nativeName": "English (United States)", "primary": true },
    "en-GB": {"tag": "en-GB", "name": "Angielski (Wielka Brytania)", "nativeName": "English (United Kingdom)", "primary": false},
    "en-CA": {"tag": "en-CA", "name": "Angielski (Kanada)", "nativeName": "English (Canada)", "primary": false},
    "en-AU": {"tag": "en-AU", "name": "Angielski (Australia)", "nativeName": "English (Australia)", "primary": false},
    "en-IN": {"tag": "en-IN", "name": "Angielski (Indie)", "nativeName": "English (India)", "primary": false},
    "en-ZA": {"tag": "en-ZA", "name": "Angielski (Republika Południowej Afryki)", "nativeName": "English (South Africa)", "primary": false},
    "en-NZ": {"tag": "en-NZ", "name": "Angielski (Nowa Zelandia)", "nativeName": "English (New Zealand)", "primary": false},
    "en-IE": {"tag": "en-IE", "name": "Angielski (Irlandia)", "nativeName": "English (Ireland)", "primary": false},
    "en-PH": {"tag": "en-PH", "name": "Angielski (Filipiny)", "nativeName": "English (Philippines)", "primary": false},
    "en-ZW": {"tag": "en-ZW", "name": "Angielski (Zimbabwe)", "nativeName": "English (Zimbabwe)", "primary": false},
    "en-BZ": {"tag": "en-BZ", "name": "Angielski (Belize)", "nativeName": "English (Belize)", "primary": false},
    "en-CB": {"tag": "en-CB", "name": "Angielski (Karaiby)", "nativeName": "English (Caribbean)", "primary": false},
    "en-JM": {"tag": "en-JM", "name": "Angielski (Jamajka)", "nativeName": "English (Jamaica)", "primary": false},
    "en-TT": {"tag": "en-TT", "name": "Angielski (Trynidad i Tobago)", "nativeName": "English (Trinidad and Tobago)", "primary": false},
    "en-NG": {"tag": "en-NG", "name": "Angielski (Nigeria)", "nativeName": "English (Nigeria)", "primary": false},
    "en-UG": {"tag": "en-UG", "name": "Angielski (Uganda)", "nativeName": "English (Uganda)", "primary": false},
    "hi-IN": {"tag": "hi-IN", "name": "Hindi (Indie)", "nativeName": "हिन्दी (Hindi)", "primary": false},
    "es-ES": {"tag": "es-ES", "name": "Hiszpański (Hiszpania)", "nativeName": "Español (España)", "primary": true },
    "es-MX": {"tag": "es-MX", "name": "Hiszpański (Meksyk)", "nativeName": "Español (México)", "primary": false},
    "es-AR": {"tag": "es-AR", "name": "Hiszpański (Argentyna)", "nativeName": "Español (Argentina)", "primary": false},
    "es-CO": {"tag": "es-CO", "name": "Hiszpański (Kolumbia)", "nativeName": "Español (Colombia)", "primary": false},
    "es-PE": {"tag": "es-PE", "name": "Hiszpański (Peru)", "nativeName": "Español (Perú)", "primary": false},
    "es-VE": {"tag": "es-VE", "name": "Hiszpański (Wenezuela)", "nativeName": "Español (Venezuela)", "primary": false},
    "es-CL": {"tag": "es-CL", "name": "Hiszpański (Chile)", "nativeName": "Español (Chile)", "primary": false},
    "es-EC": {"tag": "es-EC", "name": "Hiszpański (Ekwador)", "nativeName": "Español (Ecuador)", "primary": false},
    "es-GT": {"tag": "es-GT", "name": "Hiszpański (Gwatemala)", "nativeName": "Español (Guatemala)", "primary": false},
    "es-CU": {"tag": "es-CU", "name": "Hiszpański (Kuba)", "nativeName": "Español (Cuba)", "primary": false},
    "es-BO": {"tag": "es-BO", "name": "Hiszpański (Boliwia)", "nativeName": "Español (Bolivia)", "primary": false},
    "es-DO": {"tag": "es-DO", "name": "Hiszpański (Dominikana)", "nativeName": "Español (República Dominicana)", "primary": false},
    "es-HN": {"tag": "es-HN", "name": "Hiszpański (Honduras)", "nativeName": "Español (Honduras)", "primary": false},
    "es-PY": {"tag": "es-PY", "name": "Hiszpański (Paragwaj)", "nativeName": "Español (Paraguay)", "primary": false},
    "es-SV": {"tag": "es-SV", "name": "Hiszpański (Salwador)", "nativeName": "Español (El Salvador)", "primary": false},
    "es-NI": {"tag": "es-NI", "name": "Hiszpański (Nikaragua)", "nativeName": "Español (Nicaragua)", "primary": false},
    "es-PR": {"tag": "es-PR", "name": "Hiszpański (Portoryko)", "nativeName": "Español (Puerto Rico)", "primary": false},
    "es-UY": {"tag": "es-UY", "name": "Hiszpański (Urugwaj)", "nativeName": "Español (Uruguay)", "primary": false},
    "es-PA": {"tag": "es-PA", "name": "Hiszpański (Panama)", "nativeName": "Español (Panamá)", "primary": false},
    "es-CR": {"tag": "es-CR", "name": "Hiszpański (Kostaryka)", "nativeName": "Español (Costa Rica)", "primary": false},
    "ar-EG": {"tag": "ar-EG", "name": "Arabski (Egipt)", "nativeName": "العربية (مصر)", "primary": true },
    "ar-SA": {"tag": "ar-SA", "name": "Arabski (Arabia Saudyjska)", "nativeName": "العربية (السعودية)", "primary": false},
    "ar-DZ": {"tag": "ar-DZ", "name": "Arabski (Algieria)", "nativeName": "العربية (الجزائر)", "primary": false},
    "ar-MA": {"tag": "ar-MA", "name": "Arabski (Maroko)", "nativeName": "العربية (المغرب)", "primary": false},
    "ar-IQ": {"tag": "ar-IQ", "name": "Arabski (Irak)", "nativeName": "العربية (العراق)", "primary": false},
    "ar-SD": {"tag": "ar-SD", "name": "Arabski (Sudan)", "nativeName": "العربية (السودان)", "primary": false},
    "ar-YE": {"tag": "ar-YE", "name": "Arabski (Jemen)", "nativeName": "العربية (اليمن)", "primary": false},
    "ar-SY": {"tag": "ar-SY", "name": "Arabski (Syria)", "nativeName": "العربية (سوريا)", "primary": false},
    "ar-TN": {"tag": "ar-TN", "name": "Arabski (Tunezja)", "nativeName": "العربية (تونس)", "primary": false},
    "ar-LY": {"tag": "ar-LY", "name": "Arabski (Libia)", "nativeName": "العربية (ليبيا)", "primary": false},
    "ar-JO": {"tag": "ar-JO", "name": "Arabski (Jordania)", "nativeName": "العربية (الأردن)", "primary": false},
    "ar-LB": {"tag": "ar-LB", "name": "Arabski (Liban)", "nativeName": "العربية (لبنان)", "primary": false},
    "ar-KW": {"tag": "ar-KW", "name": "Arabski (Kuwejt)", "nativeName": "العربية (الكويت)", "primary": false},
    "ar-AE": {"tag": "ar-AE", "name": "Arabski (Zjednoczone Emiraty Arabskie)", "nativeName": "العربية (الإمارات)", "primary": false},
    "ar-BH": {"tag": "ar-BH", "name": "Arabski (Bahrajn)", "nativeName": "العربية (البحرين)", "primary": false},
    "ar-QA": {"tag": "ar-QA", "name": "Arabski (Katar)", "nativeName": "العربية (قطر)", "primary": false},
    "ar-OM": {"tag": "ar-OM", "name": "Arabski (Oman)", "nativeName": "العربية (عمان)", "primary": false},
    "pt-BR": {"tag": "pt-BR", "name": "Portugalski (Brazylia)", "nativeName": "Português (Brasil)", "primary": false},
    "pt-PT": {"tag": "pt-PT", "name": "Portugalski (Portugalia)", "nativeName": "Português (Portugal)", "primary": true },
    "ru-RU": {"tag": "ru-RU", "name": "Rosyjski (Rosja)", "nativeName": "Русский (Россия)", "primary": true },
    "ja-JP": {"tag": "ja-JP", "name": "Japoński (Japonia)", "nativeName": "日本語 (日本)", "primary": true },
    "de-DE": {"tag": "de-DE", "name": "Niemiecki (Niemcy)", "nativeName": "Deutsch (Deutschland)", "primary": true },
    "de-AT": {"tag": "de-AT", "name": "Niemiecki (Austria)", "nativeName": "Deutsch (Österreich)", "primary": false},
    "de-CH": {"tag": "de-CH", "name": "Niemiecki (Szwajcaria)", "nativeName": "Deutsch (Schweiz)", "primary": false},
    "fr-FR": {"tag": "fr-FR", "name": "Francuski (Francja)", "nativeName": "Français (France)", "primary": true },
    "fr-CA": {"tag": "fr-CA", "name": "Francuski (Kanada)", "nativeName": "Français (Canada)", "primary": false},
    "fr-BE": {"tag": "fr-BE", "name": "Francuski (Belgia)", "nativeName": "Français (Belgique)", "primary": false},
    "fr-CH": {"tag": "fr-CH", "name": "Francuski (Szwajcaria)", "nativeName": "Français (Suisse)", "primary": false},
    "fr-LU": {"tag": "fr-LU", "name": "Francuski (Luksemburg)", "nativeName": "Français (Luxembourg)", "primary": false},
    "fr-MC": {"tag": "fr-MC", "name": "Francuski (Monako)", "nativeName": "Français (Monaco)", "primary": false},
    "fr-CD": {"tag": "fr-CD", "name": "Francuski (Demokratyczna Republika Konga)", "nativeName": "Français (République démocratique du Congo)", "primary": false},
    "ko-KR": {"tag": "ko-KR", "name": "Koreański (Korea Południowa)", "nativeName": "한국어 (대한민국)", "primary": true},
    "ko-KP": {"tag": "ko-KP", "name": "Koreański (Korea Północna)", "nativeName": "한국어 (조선민주주인민공화국)", "primary": false},
    "it-IT": {"tag": "it-IT", "name": "Włoski (Włochy)", "nativeName": "Italiano (Italia)", "primary": true },
    "it-CH": {"tag": "it-CH", "name": "Włoski (Szwajcaria)", "nativeName": "Italiano (Svizzera)", "primary": false},
    "nl-NL": {"tag": "nl-NL", "name": "Niderlandzki (Holandia)", "nativeName": "Nederlands (Nederland)", "primary": true},
    "nl-BE": {"tag": "nl-BE", "name": "Niderlandzki (Belgia)", "nativeName": "Nederlands (België)", "primary": false},
    "bn-BD": {"tag": "bn-BD", "name": "Bengalski (Bangladesz)", "nativeName": "বাংলা (বাংলাদেশ)", "primary": false},
    "pl-PL": {"tag": "pl-PL", "name": "Polski (Polska)", "nativeName": "Polski (Polska)", "primary": false},
    "vi-VN": {"tag": "vi-VN", "name": "Wietnamski (Wietnam)", "nativeName": "Tiếng Việt (Việt Nam)", "primary": false},
    "tr-TR": {"tag": "tr-TR", "name": "Turecki (Turcja)", "nativeName": "Türkçe (Türkiye)", "primary": false},
    "th-TH": {"tag": "th-TH", "name": "Tajski (Tajlandia)", "nativeName": "ไทย (ประเทศไทย)", "primary": false},
    "el-GR": {"tag": "el-GR", "name": "Grecki (Grecja)", "nativeName": "Ελληνικά (Ελλάδα)", "primary": false},
    "cs-CZ": {"tag": "cs-CZ", "name": "Czeski (Czechy)", "nativeName": "Čeština (Česká republika)", "primary": false},
    "sv-SE": {"tag": "sv-SE", "name": "Szwedzki (Szwecja)", "nativeName": "Svenska (Sverige)", "primary": false },
    "sv-FI": {"tag": "sv-FI", "name": "Szwedzki (Finlandia)", "nativeName": "Svenska (Finland)", "primary": false},
    "hu-HU": {"tag": "hu-HU", "name": "Węgierski (Węgry)", "nativeName": "Magyar (Magyarország)", "primary": false},
    "fi-FI": {"tag": "fi-FI", "name": "Fiński (Finlandia)", "nativeName": "Suomi (Suomi)", "primary": false},
    "da-DK": {"tag": "da-DK", "name": "Duński (Dania)", "nativeName": "Dansk (Danmark)", "primary": false},
    "nb-NO": {"tag": "nb-NO", "name": "Norweski Bokmål (Norwegia)", "nativeName": "Norsk Bokmål (Norge)", "primary": false},
    "nn-NO": {"tag": "nn-NO", "name": "Norweski Nynorsk (Norwegia)", "nativeName": "Norsk Nynorsk (Norge)", "primary": false},
    "he-IL": {"tag": "he-IL", "name": "Hebrajski (Izrael)", "nativeName": "עברית (ישראל)", "primary": false},
    "id-ID": {"tag": "id-ID", "name": "Indonezyjski (Indonezja)", "nativeName": "Bahasa Indonesia (Indonesia)", "primary": false},
    "ms-MY": {"tag": "ms-MY", "name": "Malajski (Malezja)", "nativeName": "Bahasa Melayu (Malaysia)", "primary": false},
    "ms-BN": {"tag": "ms-BN", "name": "Malajski (Brunei)", "nativeName": "Bahasa Melayu (Brunei)", "primary": false},
    "ro-RO": {"tag": "ro-RO", "name": "Rumuński (Rumunia)", "nativeName": "Română (România)", "primary": false},
    "bg-BG": {"tag": "bg-BG", "name": "Bułgarski (Bułgaria)", "nativeName": "Български (България)", "primary": false},
    "uk-UA": {"tag": "uk-UA", "name": "Ukraiński (Ukraina)", "nativeName": "Українська (Україна)", "primary": false},
    "sk-SK": {"tag": "sk-SK", "name": "Słowacki (Słowacja)", "nativeName": "Slovenčina (Slovensko)", "primary": false},
    "sl-SI": {"tag": "sl-SI", "name": "Słoweński (Słowenia)", "nativeName": "Slovenščina (Slovenija)", "primary": false},
    "hr-HR": {"tag": "hr-HR", "name": "Chorwacki (Chorwacja)", "nativeName": "Hrvatski (Hrvatska)", "primary": false},
    "ca-ES": {"tag": "ca-ES", "name": "Kataloński (Katalonia)", "nativeName": "Català (Catalunya)", "primary": false},
    "lt-LT": {"tag": "lt-LT", "name": "Litewski (Litwa)", "nativeName": "Lietuvių (Lietuva)", "primary": false},
    "lv-LV": {"tag": "lv-LV", "name": "Łotewski (Łotwa)", "nativeName": "Latviešu (Latvija)", "primary": false},
    "et-EE": {"tag": "et-EE", "name": "Estoński (Estonia)", "nativeName": "Eesti (Eesti)", "primary": false},        
    "sq-AL": {"tag": "sq-AL", "name": "Albański (Albania)", "nativeName": "Shqip (Shqipëri)", "primary": false},
    "mk-MK": {"tag": "mk-MK", "name": "Macedoński (Macedonia Północna)", "nativeName": "Македонски (Македонија)", "primary": false},
    "be-BY": {"tag": "be-BY", "name": "Białoruski (Białoruś)", "nativeName": "Беларуская (Беларусь)", "primary": false},
    "is-IS": {"tag": "is-IS", "name": "Islandzki (Islandia)", "nativeName": "Íslenska (Ísland)", "primary": false},
    "gl-ES": {"tag": "gl-ES", "name": "Galicyjski (Galicja)", "nativeName": "Galego (Galicia)", "primary": false},
    "eu-ES": {"tag": "eu-ES", "name": "Baskijski (Kraj Basków)", "nativeName": "Euskara (Euskal Herria)", "primary": false},
    "af-ZA": {"tag": "af-ZA", "name": "Afrikaans (Republika Południowej Afryki)", "nativeName": "Afrikaans (Suid-Afrika)", "primary": false},
    "sw-KE": {"tag": "sw-KE", "name": "Suahili (Kenia)", "nativeName": "Kiswahili (Kenya)", "primary": false},
    "ta-IN": {"tag": "ta-IN", "name": "Tamilski (Indie)", "nativeName": "தமிழ் (இந்தியா)", "primary": false},
    "te-IN": {"tag": "te-IN", "name": "Telugu (Indie)", "nativeName": "తెలుగు (భారతదేశం)", "primary": false},
    "kn-IN": {"tag": "kn-IN", "name": "Kannada (Indie)", "nativeName": "ಕನ್ನಡ (ಭಾರತ)", "primary": false},
    "mr-IN": {"tag": "mr-IN", "name": "Marathi (Indie)", "nativeName": "मराठी (भारत)", "primary": false},
    "gu-IN": {"tag": "gu-IN", "name": "Gudżarati (Indie)", "nativeName": "ગુજરાતી (ભારત)", "primary": false},
    "pa-IN": {"tag": "pa-IN", "name": "Pendżabski (Indie)", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)", "primary": false},
    "kok-IN": {"tag": "kok-IN", "name": "Konkani (Indie)", "nativeName": "कोंकणी (भारत)", "primary": false},
    "sa-IN": {"tag": "sa-IN", "name": "Sanskryt (Indie)", "nativeName": "संस्कृत (भारत)", "primary": false},
    "ur-PK": {"tag": "ur-PK", "name": "Urdu (Pakistan)", "nativeName": "اردو (پاکستان)", "primary": false},
    "fa-IR": {"tag": "fa-IR", "name": "Perski (Iran)", "nativeName": "فارسی (ایران)", "primary": false},
    "syr-SY": {"tag": "syr-SY", "name": "Syryjski (Syria)", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)", "primary": false},
    "div-MV": {"tag": "div-MV", "name": "Malediwski (Malediwy)", "nativeName": "ދިވެހި (މޯލްޑިވްސް)", "primary": false},
    "ka-GE": {"tag": "ka-GE", "name": "Gruziński (Gruzja)", "nativeName": "ქართული (საქართველო)", "primary": false},
    "am-ET": {"tag": "am-ET", "name": "Amharski (Etiopia)", "nativeName": "አማርኛ (ኢትዮጵያ)", "primary": false},
    "my-MM": {"tag": "my-MM", "name": "Birmański (Mjanma)", "nativeName": "မြန်မာ (မြန်မာ)", "primary": false}
}



const { getTag, getTags, getPrimaryTags } = createTagUtils(tags)
export {
    getTag, getTags,getPrimaryTags
}
export * from './types'    
