import { createTagUtils } from './utils'

export const tags = {
    "zh-CN": {"tag": "zh-CN", "name": "Китайский (упрощенный)", "nativeName": "简体中文", "default": true},
    "zh-TW": {"tag": "zh-TW", "name": "Китайский (традиционный - Тайвань)", "nativeName": "繁體中文 (臺灣)"},
    "zh-HK": {"tag": "zh-HK", "name": "Китайский (традиционный - Гонконг)", "nativeName": "繁體中文（香港）"},
    "zh-MO": {"tag": "zh-MO", "name": "Китайский (традиционный - Макао)", "nativeName": "繁體中文 (Traditional Chinese - Macau)"},
    "zh-SG": {"tag": "zh-SG", "name": "Китайский (упрощенный - Сингапур)", "nativeName": "简体中文 (Simplified Chinese - Singapore)"},      
    "zh-CHS": {"tag": "zh-CHS", "name": "Китайский (упрощенный)", "nativeName": "简体中文"},
    "zh-CHT": {"tag": "zh-CHT", "name": "Китайский (традиционный)", "nativeName": "繁體中文 (Traditional Chinese)"},
    "en-US": {"tag": "en-US", "name": "Английский (США)", "nativeName": "English (United States)", "default": true},
    "en-GB": {"tag": "en-GB", "name": "Английский (Великобритания)", "nativeName": "English (United Kingdom)"},
    "en-CA": {"tag": "en-CA", "name": "Английский (Канада)", "nativeName": "English (Canada)"},
    "en-AU": {"tag": "en-AU", "name": "Английский (Австралия)", "nativeName": "English (Australia)"},
    "en-IN": {"tag": "en-IN", "name": "Английский (Индия)", "nativeName": "English (India)"},
    "en-ZA": {"tag": "en-ZA", "name": "Английский (Южная Африка)", "nativeName": "English (South Africa)"},
    "en-NZ": {"tag": "en-NZ", "name": "Английский (Новая Зеландия)", "nativeName": "English (New Zealand)"},
    "en-IE": {"tag": "en-IE", "name": "Английский (Ирландия)", "nativeName": "English (Ireland)"},
    "en-PH": {"tag": "en-PH", "name": "Английский (Филиппины)", "nativeName": "English (Philippines)"},
    "en-ZW": {"tag": "en-ZW", "name": "Английский (Зимбабве)", "nativeName": "English (Zimbabwe)"},
    "en-BZ": {"tag": "en-BZ", "name": "Английский (Белиз)", "nativeName": "English (Belize)"},
    "en-CB": {"tag": "en-CB", "name": "Английский (Карибский бассейн)", "nativeName": "English (Caribbean)"},
    "en-JM": {"tag": "en-JM", "name": "Английский (Ямайка)", "nativeName": "English (Jamaica)"},
    "en-TT": {"tag": "en-TT", "name": "Английский (Тринидад и Тобаго)", "nativeName": "English (Trinidad and Tobago)"},
    "hi-IN": {"tag": "hi-IN", "name": "Хинди (Индия)", "nativeName": "हिन्दी (Hindi)"},
    "es-ES": {"tag": "es-ES", "name": "Испанский (Испания)", "nativeName": "Español (España)", "default": true},
    "es-MX": {"tag": "es-MX", "name": "Испанский (Мексика)", "nativeName": "Español (México)"},
    "es-AR": {"tag": "es-AR", "name": "Испанский (Аргентина)", "nativeName": "Español (Argentina)"},
    "es-CO": {"tag": "es-CO", "name": "Испанский (Колумбия)", "nativeName": "Español (Colombia)"},
    "es-PE": {"tag": "es-PE", "name": "Испанский (Перу)", "nativeName": "Español (Perú)"},
    "es-VE": {"tag": "es-VE", "name": "Испанский (Венесуэла)", "nativeName": "Español (Venezuela)"},
    "es-CL": {"tag": "es-CL", "name": "Испанский (Чили)", "nativeName": "Español (Chile)"},
    "es-EC": {"tag": "es-EC", "name": "Испанский (Эквадор)", "nativeName": "Español (Ecuador)"},
    "es-GT": {"tag": "es-GT", "name": "Испанский (Гватемала)", "nativeName": "Español (Guatemala)"},
    "es-CU": {"tag": "es-CU", "name": "Испанский (Куба)", "nativeName": "Español (Cuba)"},
    "es-BO": {"tag": "es-BO", "name": "Испанский (Боливия)", "nativeName": "Español (Bolivia)"},
    "es-DO": {"tag": "es-DO", "name": "Испанский (Доминиканская Республика)", "nativeName": "Español (República Dominicana)"},
    "es-HN": {"tag": "es-HN", "name": "Испанский (Гондурас)", "nativeName": "Español (Honduras)"},
    "es-PY": {"tag": "es-PY", "name": "Испанский (Парагвай)", "nativeName": "Español (Paraguay)"},
    "es-SV": {"tag": "es-SV", "name": "Испанский (Сальвадор)", "nativeName": "Español (El Salvador)"},
    "es-NI": {"tag": "es-NI", "name": "Испанский (Никарагуа)", "nativeName": "Español (Nicaragua)"},
    "es-PR": {"tag": "es-PR", "name": "Испанский (Пуэрто-Рико)", "nativeName": "Español (Puerto Rico)"},
    "es-UY": {"tag": "es-UY", "name": "Испанский (Уругвай)", "nativeName": "Español (Uruguay)"},
    "es-PA": {"tag": "es-PA", "name": "Испанский (Панама)", "nativeName": "Español (Panamá)"},
    "es-CR": {"tag": "es-CR", "name": "Испанский (Коста-Рика)", "nativeName": "Español (Costa Rica)"},
    "ar-EG": {"tag": "ar-EG", "name": "Арабский (Египет)", "nativeName": "العربية (مصر)", "default": true},
    "ar-SA": {"tag": "ar-SA", "name": "Арабский (Саудовская Аравия)", "nativeName": "العربية (السعودية)"},
    "ar-DZ": {"tag": "ar-DZ", "name": "Арабский (Алжир)", "nativeName": "العربية (الجزائر)"},
    "ar-MA": {"tag": "ar-MA", "name": "Арабский (Марокко)", "nativeName": "العربية (المغرب)"},
    "ar-IQ": {"tag": "ar-IQ", "name": "Арабский (Ирак)", "nativeName": "العربية (العراق)"},
    "ar-SD": {"tag": "ar-SD", "name": "Арабский (Судан)", "nativeName": "العربية (السودان)"},
    "ar-YE": {"tag": "ar-YE", "name": "Арабский (Йемен)", "nativeName": "العربية (اليمن)"},
    "ar-SY": {"tag": "ar-SY", "name": "Арабский (Сирия)", "nativeName": "العربية (سوريا)"},
    "ar-TN": {"tag": "ar-TN", "name": "Арабский (Тунис)", "nativeName": "العربية (تونس)"},
    "ar-LY": {"tag": "ar-LY", "name": "Арабский (Ливия)", "nativeName": "العربية (ليبيا)"},
    "ar-JO": {"tag": "ar-JO", "name": "Арабский (Иордания)", "nativeName": "العربية (الأردن)"},
    "ar-LB": {"tag": "ar-LB", "name": "Арабский (Ливан)", "nativeName": "العربية (لبنان)"},
    "ar-KW": {"tag": "ar-KW", "name": "Арабский (Кувейт)", "nativeName": "العربية (الكويت)"},
    "ar-AE": {"tag": "ar-AE", "name": "Арабский (ОАЭ)", "nativeName": "العربية (الإمارات)"},
    "ar-BH": {"tag": "ar-BH", "name": "Арабский (Бахрейн)", "nativeName": "العربية (البحرين)"},
    "ar-QA": {"tag": "ar-QA", "name": "Арабский (Катар)", "nativeName": "العربية (قطر)"},
    "ar-OM": {"tag": "ar-OM", "name": "Арабский (Оман)", "nativeName": "العربية (عمان)"},
    "pt-BR": {"tag": "pt-BR", "name": "Португальский (Бразилия)", "nativeName": "Português (Brasil)"},
    "pt-PT": {"tag": "pt-PT", "name": "Португальский (Португалия)", "nativeName": "Português (Portugal)", "default": true},
    "ru-RU": {"tag": "ru-RU", "name": "Русский (Россия)", "nativeName": "Русский (Россия)", "default": true},
    "ja-JP": {"tag": "ja-JP", "name": "Японский (Япония)", "nativeName": "日本語 (日本)", "default": true},
    "de-DE": {"tag": "de-DE", "name": "Немецкий (Германия)", "nativeName": "Deutsch (Deutschland)", "default": true},
    "de-AT": {"tag": "de-AT", "name": "Немецкий (Австрия)", "nativeName": "Deutsch (Österreich)"},
    "de-CH": {"tag": "de-CH", "name": "Немецкий (Швейцария)", "nativeName": "Deutsch (Schweiz)"},
    "fr-FR": {"tag": "fr-FR", "name": "Французский (Франция)", "nativeName": "Français (France)", "default": true},
    "fr-CA": {"tag": "fr-CA", "name": "Французский (Канада)", "nativeName": "Français (Canada)"},
    "fr-BE": {"tag": "fr-BE", "name": "Французский (Бельгия)", "nativeName": "Français (Belgique)"},
    "fr-CH": {"tag": "fr-CH", "name": "Французский (Швейцария)", "nativeName": "Français (Suisse)"},
    "fr-LU": {"tag": "fr-LU", "name": "Французский (Люксембург)", "nativeName": "Français (Luxembourg)"},
    "fr-MC": {"tag": "fr-MC", "name": "Французский (Монако)", "nativeName": "Français (Monaco)"},
    "ko-KR": {"tag": "ko-KR", "name": "Корейский (Южная Корея)", "nativeName": "한국어 (대한민국)"},
    "it-IT": {"tag": "it-IT", "name": "Итальянский (Италия)", "nativeName": "Italiano (Italia)", "default": true },
    "it-CH": {"tag": "it-CH", "name": "Итальянский (Швейцария)", "nativeName": "Italiano (Svizzera)"},
    "nl-NL": {"tag": "nl-NL", "name": "Нидерландский (Нидерланды)", "nativeName": "Nederlands (Nederland)"},
    "nl-BE": {"tag": "nl-BE", "name": "Нидерландский (Бельгия)", "nativeName": "Nederlands (België)"},
    "pl-PL": {"tag": "pl-PL", "name": "Польский (Польша)", "nativeName": "Polski (Polska)"},
    "vi-VN": {"tag": "vi-VN", "name": "Вьетнамский (Вьетнам)", "nativeName": "Tiếng Việt (Việt Nam)"},
    "tr-TR": {"tag": "tr-TR", "name": "Турецкий (Турция)", "nativeName": "Türkçe (Türkiye)"},
    "th-TH": {"tag": "th-TH", "name": "Тайский (Таиланд)", "nativeName": "ไทย (ประเทศไทย)"},
    "el-GR": {"tag": "el-GR", "name": "Греческий (Греция)", "nativeName": "Ελληνικά (Ελλάδα)"},
    "cs-CZ": {"tag": "cs-CZ", "name": "Чешский (Чехия)", "nativeName": "Čeština (Česká republika)"},
    "sv-SE": {"tag": "sv-SE", "name": "Шведский (Швеция)", "nativeName": "Svenska (Sverige)", "default": true},
    "sv-FI": {"tag": "sv-FI", "name": "Шведский (Финляндия)", "nativeName": "Svenska (Finland)"},
    "hu-HU": {"tag": "hu-HU", "name": "Венгерский (Венгрия)", "nativeName": "Magyar (Magyarország)"},
    "fi-FI": {"tag": "fi-FI", "name": "Финский (Финляндия)", "nativeName": "Suomi (Suomi)"},
    "da-DK": {"tag": "da-DK", "name": "Датский (Дания)", "nativeName": "Dansk (Danmark)"},
    "nb-NO": {"tag": "nb-NO", "name": "Норвежский букмол (Норвегия)", "nativeName": "Norsk Bokmål (Norge)"},
    "nn-NO": {"tag": "nn-NO", "name": "Норвежский нюнорск (Норвегия)", "nativeName": "Norsk Nynorsk (Norge)"},
    "he-IL": {"tag": "he-IL", "name": "Иврит (Израиль)", "nativeName": "עברית (ישראל)"},
    "id-ID": {"tag": "id-ID", "name": "Индонезийский (Индонезия)", "nativeName": "Bahasa Indonesia (Indonesia)"},
    "ms-MY": {"tag": "ms-MY", "name": "Малайский (Малайзия)", "nativeName": "Bahasa Melayu (Malaysia)"},
    "ms-BN": {"tag": "ms-BN", "name": "Малайский (Бруней)", "nativeName": "Bahasa Melayu (Brunei)"},
    "ro-RO": {"tag": "ro-RO", "name": "Румынский (Румыния)", "nativeName": "Română (România)"},
    "bg-BG": {"tag": "bg-BG", "name": "Болгарский (Болгария)", "nativeName": "Български (България)"},
    "uk-UA": {"tag": "uk-UA", "name": "Украинский (Украина)", "nativeName": "Українська (Україна)"},
    "sk-SK": {"tag": "sk-SK", "name": "Словацкий (Словакия)", "nativeName": "Slovenčina (Slovensko)"},
    "sl-SI": {"tag": "sl-SI", "name": "Словенский (Словения)", "nativeName": "Slovenščina (Slovenija)"},        
    "hr-HR": {"tag": "hr-HR", "name": "Хорватский (Хорватия)", "nativeName": "Hrvatski (Hrvatska)"},
    "ca-ES": {"tag": "ca-ES", "name": "Каталанский (Каталония)", "nativeName": "Català (Catalunya)"},
    "lt-LT": {"tag": "lt-LT", "name": "Литовский (Литва)", "nativeName": "Lietuvių (Lietuva)"},
    "lv-LV": {"tag": "lv-LV", "name": "Латышский (Латвия)", "nativeName": "Latviešu (Latvija)"},
    "et-EE": {"tag": "et-EE", "name": "Эстонский (Эстония)", "nativeName": "Eesti (Eesti)"},
    "sq-AL": {"tag": "sq-AL", "name": "Албанский (Албания)", "nativeName": "Shqip (Shqipëri)"},
    "mk-MK": {"tag": "mk-MK", "name": "Македонский (Северная Македония)", "nativeName": "Македонски (Македонија)"},
    "be-BY": {"tag": "be-BY", "name": "Белорусский (Беларусь)", "nativeName": "Беларуская (Беларусь)"},
    "is-IS": {"tag": "is-IS", "name": "Исландский (Исландия)", "nativeName": "Íslenska (Ísland)"},
    "gl-ES": {"tag": "gl-ES", "name": "Галисийский (Галисия)", "nativeName": "Galego (Galicia)"},
    "eu-ES": {"tag": "eu-ES", "name": "Баскский (Страна Басков)", "nativeName": "Euskara (Euskal Herria)"},
    "af-ZA": {"tag": "af-ZA", "name": "Африкаанс (Южная Африка)", "nativeName": "Afrikaans (Suid-Afrika)"},
    "sw-KE": {"tag": "sw-KE", "name": "Суахили (Кения)", "nativeName": "Kiswahili (Kenya)"},
    "ta-IN": {"tag": "ta-IN", "name": "Тамильский (Индия)", "nativeName": "தமிழ் (இந்தியா)"},
    "te-IN": {"tag": "te-IN", "name": "Телугу (Индия)", "nativeName": "తెలుగు (భారతదేశం)"},
    "kn-IN": {"tag": "kn-IN", "name": "Каннада (Индия)", "nativeName": "ಕನ್ನಡ (ಭಾರತ)"},
    "mr-IN": {"tag": "mr-IN", "name": "Маратхи (Индия)", "nativeName": "मराठी (भारत)"},
    "gu-IN": {"tag": "gu-IN", "name": "Гуджарати (Индия)", "nativeName": "ગુજરાતી (ભારત)"},
    "pa-IN": {"tag": "pa-IN", "name": "Панджаби (Индия)", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)"},
    "kok-IN": {"tag": "kok-IN", "name": "Конкани (Индия)", "nativeName": "कोंकणी (भारत)"},
    "sa-IN": {"tag": "sa-IN", "name": "Санскрит (Индия)", "nativeName": "संस्कृत (भारत)"},
    "ur-PK": {"tag": "ur-PK", "name": "Урду (Пакистан)", "nativeName": "اردو (پاکستان)"},
    "fa-IR": {"tag": "fa-IR", "name": "Персидский (Иран)", "nativeName": "فارسی (ایران)"},
    "syr-SY": {"tag": "syr-SY", "name": "Сирийский (Сирия)", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)"},
    "div-MV": {"tag": "div-MV", "name": "Дивехи (Мальдивы)", "nativeName": "ދިވެހި (މޯލްޑިވްސް)"},
    "ka-GE": {"tag": "ka-GE", "name": "Грузинский (Грузия)", "nativeName": "ქართული (საქართველო)"},      
}


const { getTag, getTags, getDefaultTags } = createTagUtils(tags)
export {
    getTag, getTags,getDefaultTags 
}
export * from './types'    