import { createTagUtils } from './utils'

export const tags = {
    "zh-CN": {"tag": "zh-CN", "name": "จีน (ตัวย่อ)", "nativeName": "简体中文", "primary": true },
    "zh-TW": {"tag": "zh-TW", "name": "จีน (ตัวเต็ม - ไต้หวัน)", "nativeName": "繁體中文(中國臺灣)", "primary": false},
    "zh-HK": {"tag": "zh-HK", "name": "จีน (ตัวเต็ม - ฮ่องกง)", "nativeName": "繁體中文(中國香港)", "primary": false},
    "zh-MO": {"tag": "zh-MO", "name": "จีน (ตัวเต็ม - มาเก๊า)", "nativeName": "繁體中文(中國澳門)", "primary": false},
    "zh-SG": {"tag": "zh-SG", "name": "จีน (ตัวย่อ - สิงคโปร์)", "nativeName": "简体中文(新加坡)", "primary": false},      
    "zh-CHS": {"tag": "zh-CHS", "name": "จีน (ตัวย่อ)", "nativeName": "简体中文", "primary": false},
    "zh-CHT": {"tag": "zh-CHT", "name": "จีน (ตัวเต็ม)", "nativeName": "繁體中文(Traditional Chinese)", "primary": false},
    "en-US": {"tag": "en-US", "name": "อังกฤษ (สหรัฐอเมริกา)", "nativeName": "English (United States)", "primary": true },
    "en-GB": {"tag": "en-GB", "name": "อังกฤษ (สหราชอาณาจักร)", "nativeName": "English (United Kingdom)", "primary": false},
    "en-CA": {"tag": "en-CA", "name": "อังกฤษ (แคนาดา)", "nativeName": "English (Canada)", "primary": false},
    "en-AU": {"tag": "en-AU", "name": "อังกฤษ (ออสเตรเลีย)", "nativeName": "English (Australia)", "primary": false},
    "en-IN": {"tag": "en-IN", "name": "อังกฤษ (อินเดีย)", "nativeName": "English (India)", "primary": false},
    "en-ZA": {"tag": "en-ZA", "name": "อังกฤษ (แอฟริกาใต้)", "nativeName": "English (South Africa)", "primary": false},
    "en-NZ": {"tag": "en-NZ", "name": "อังกฤษ (นิวซีแลนด์)", "nativeName": "English (New Zealand)", "primary": false},
    "en-IE": {"tag": "en-IE", "name": "อังกฤษ (ไอร์แลนด์)", "nativeName": "English (Ireland)", "primary": false},
    "en-PH": {"tag": "en-PH", "name": "อังกฤษ (ฟิลิปปินส์)", "nativeName": "English (Philippines)", "primary": false},
    "en-ZW": {"tag": "en-ZW", "name": "อังกฤษ (ซิมบับเว)", "nativeName": "English (Zimbabwe)", "primary": false},
    "en-BZ": {"tag": "en-BZ", "name": "อังกฤษ (เบลีซ)", "nativeName": "English (Belize)", "primary": false},
    "en-CB": {"tag": "en-CB", "name": "อังกฤษ (แคริบเบียน)", "nativeName": "English (Caribbean)", "primary": false},
    "en-JM": {"tag": "en-JM", "name": "อังกฤษ (จาเมกา)", "nativeName": "English (Jamaica)", "primary": false},
    "en-TT": {"tag": "en-TT", "name": "อังกฤษ (ตรินิแดดและโตเบโก)", "nativeName": "English (Trinidad and Tobago)", "primary": false},
    "en-NG": {"tag": "en-NG", "name": "อังกฤษ (ไนจีเรีย)", "nativeName": "English (Nigeria)", "primary": false},
    "en-UG": {"tag": "en-UG", "name": "อังกฤษ (ยูกันดา)", "nativeName": "English (Uganda)", "primary": false},
    "hi-IN": {"tag": "hi-IN", "name": "ฮินดี (อินเดีย)", "nativeName": "हिन्दी (Hindi)", "primary": false},
    "es-ES": {"tag": "es-ES", "name": "สเปน (สเปน)", "nativeName": "Español (España)", "primary": true },
    "es-MX": {"tag": "es-MX", "name": "สเปน (เม็กซิโก)", "nativeName": "Español (México)", "primary": false},
    "es-AR": {"tag": "es-AR", "name": "สเปน (อาร์เจนตินา)", "nativeName": "Español (Argentina)", "primary": false},
    "es-CO": {"tag": "es-CO", "name": "สเปน (โคลอมเบีย)", "nativeName": "Español (Colombia)", "primary": false},
    "es-PE": {"tag": "es-PE", "name": "สเปน (เปรู)", "nativeName": "Español (Perú)", "primary": false},
    "es-VE": {"tag": "es-VE", "name": "สเปน (เวเนซุเอลา)", "nativeName": "Español (Venezuela)", "primary": false},
    "es-CL": {"tag": "es-CL", "name": "สเปน (ชิลี)", "nativeName": "Español (Chile)", "primary": false},
    "es-EC": {"tag": "es-EC", "name": "สเปน (เอกวาดอร์)", "nativeName": "Español (Ecuador)", "primary": false},
    "es-GT": {"tag": "es-GT", "name": "สเปน (กัวเตมาลา)", "nativeName": "Español (Guatemala)", "primary": false},
    "es-CU": {"tag": "es-CU", "name": "สเปน (คิวบา)", "nativeName": "Español (Cuba)", "primary": false},
    "es-BO": {"tag": "es-BO", "name": "สเปน (โบลิเวีย)", "nativeName": "Español (Bolivia)", "primary": false},
    "es-DO": {"tag": "es-DO", "name": "สเปน (สาธารณรัฐโดมินิกัน)", "nativeName": "Español (República Dominicana)", "primary": false},
    "es-HN": {"tag": "es-HN", "name": "สเปน (ฮอนดูรัส)", "nativeName": "Español (Honduras)", "primary": false},
    "es-PY": {"tag": "es-PY", "name": "สเปน (ปารากวัย)", "nativeName": "Español (Paraguay)", "primary": false},
    "es-SV": {"tag": "es-SV", "name": "สเปน (เอลซัลวาดอร์)", "nativeName": "Español (El Salvador)", "primary": false},
    "es-NI": {"tag": "es-NI", "name": "สเปน (นิการากัว)", "nativeName": "Español (Nicaragua)", "primary": false},
    "es-PR": {"tag": "es-PR", "name": "สเปน (เปอร์โตริโก)", "nativeName": "Español (Puerto Rico)", "primary": false},
    "es-UY": {"tag": "es-UY", "name": "สเปน (อุรุกวัย)", "nativeName": "Español (Uruguay)", "primary": false},
    "es-PA": {"tag": "es-PA", "name": "สเปน (ปานามา)", "nativeName": "Español (Panamá)", "primary": false},
    "es-CR": {"tag": "es-CR", "name": "สเปน (คอสตาริกา)", "nativeName": "Español (Costa Rica)", "primary": false},
    "ar-EG": {"tag": "ar-EG", "name": "อาหรับ (อียิปต์)", "nativeName": "العربية (مصر)", "primary": true },
    "ar-SA": {"tag": "ar-SA", "name": "อาหรับ (ซาอุดีอาระเบีย)", "nativeName": "العربية (السعودية)", "primary": false},
    "ar-DZ": {"tag": "ar-DZ", "name": "อาหรับ (แอลจีเรีย)", "nativeName": "العربية (الجزائر)", "primary": false},
    "ar-MA": {"tag": "ar-MA", "name": "อาหรับ (โมร็อกโก)", "nativeName": "العربية (المغرب)", "primary": false},
    "ar-IQ": {"tag": "ar-IQ", "name": "อาหรับ (อิรัก)", "nativeName": "العربية (العراق)", "primary": false},
    "ar-SD": {"tag": "ar-SD", "name": "อาหรับ (ซูดาน)", "nativeName": "العربية (السودان)", "primary": false},
    "ar-YE": {"tag": "ar-YE", "name": "อาหรับ (เยเมน)", "nativeName": "العربية (اليمن)", "primary": false},
    "ar-SY": {"tag": "ar-SY", "name": "อาหรับ (ซีเรีย)", "nativeName": "العربية (سوريا)", "primary": false},
    "ar-TN": {"tag": "ar-TN", "name": "อาหรับ (ตูนิเซีย)", "nativeName": "العربية (تونس)", "primary": false},
    "ar-LY": {"tag": "ar-LY", "name": "อาหรับ (ลิเบีย)", "nativeName": "العربية (ليبيا)", "primary": false},
    "ar-JO": {"tag": "ar-JO", "name": "อาหรับ (จอร์แดน)", "nativeName": "العربية (الأردن)", "primary": false},
    "ar-LB": {"tag": "ar-LB", "name": "อาหรับ (เลบานอน)", "nativeName": "العربية (لبنان)", "primary": false},
    "ar-KW": {"tag": "ar-KW", "name": "อาหรับ (คูเวต)", "nativeName": "العربية (الكويت)", "primary": false},
    "ar-AE": {"tag": "ar-AE", "name": "อาหรับ (สหรัฐอาหรับเอมิเรตส์)", "nativeName": "العربية (الإمارات)", "primary": false},
    "ar-BH": {"tag": "ar-BH", "name": "อาหรับ (บาห์เรน)", "nativeName": "العربية (البحرين)", "primary": false},
    "ar-QA": {"tag": "ar-QA", "name": "อาหรับ (กาตาร์)", "nativeName": "العربية (قطر)", "primary": false},
    "ar-OM": {"tag": "ar-OM", "name": "อาหรับ (โอมาน)", "nativeName": "العربية (عمان)", "primary": false},
    "pt-BR": {"tag": "pt-BR", "name": "โปรตุเกส (บราซิล)", "nativeName": "Português (Brasil)", "primary": false},
    "pt-PT": {"tag": "pt-PT", "name": "โปรตุเกส (โปรตุเกส)", "nativeName": "Português (Portugal)", "primary": true },
    "ru-RU": {"tag": "ru-RU", "name": "รัสเซีย (รัสเซีย)", "nativeName": "Русский (Россия)", "primary": true },
    "ja-JP": {"tag": "ja-JP", "name": "ญี่ปุ่น (ญี่ปุ่น)", "nativeName": "日本語 (日本)", "primary": true },
    "de-DE": {"tag": "de-DE", "name": "เยอรมัน (เยอรมนี)", "nativeName": "Deutsch (Deutschland)", "primary": true },
    "de-AT": {"tag": "de-AT", "name": "เยอรมัน (ออสเตรีย)", "nativeName": "Deutsch (Österreich)", "primary": false},
    "de-CH": {"tag": "de-CH", "name": "เยอรมัน (สวิตเซอร์แลนด์)", "nativeName": "Deutsch (Schweiz)", "primary": false},
    "fr-FR": {"tag": "fr-FR", "name": "ฝรั่งเศส (ฝรั่งเศส)", "nativeName": "Français (France)", "primary": true },
    "fr-CA": {"tag": "fr-CA", "name": "ฝรั่งเศส (แคนาดา)", "nativeName": "Français (Canada)", "primary": false},
    "fr-BE": {"tag": "fr-BE", "name": "ฝรั่งเศส (เบลเยียม)", "nativeName": "Français (Belgique)", "primary": false},
    "fr-CH": {"tag": "fr-CH", "name": "ฝรั่งเศส (สวิตเซอร์แลนด์)", "nativeName": "Français (Suisse)", "primary": false},
    "fr-LU": {"tag": "fr-LU", "name": "ฝรั่งเศส (ลักเซมเบิร์ก)", "nativeName": "Français (Luxembourg)", "primary": false},
    "fr-MC": {"tag": "fr-MC", "name": "ฝรั่งเศส (โมนาโก)", "nativeName": "Français (Monaco)", "primary": false},
    "fr-CD": {"tag": "fr-CD", "name": "ฝรั่งเศส (สาธารณรัฐประชาธิปไตยคองโก)", "nativeName": "Français (République démocratique du Congo)", "primary": false},
    "ko-KR": {"tag": "ko-KR", "name": "เกาหลี (เกาหลีใต้)", "nativeName": "한국어 (대한민국)", "primary": true},
    "ko-KP": {"tag": "ko-KP", "name": "เกาหลี (เกาหลีเหนือ)", "nativeName": "한국어 (조선민주주인민공화국)", "primary": false},
    "it-IT": {"tag": "it-IT", "name": "อิตาลี (อิตาลี)", "nativeName": "Italiano (Italia)", "primary": true },
    "it-CH": {"tag": "it-CH", "name": "อิตาลี (สวิตเซอร์แลนด์)", "nativeName": "Italiano (Svizzera)", "primary": false},
    "nl-NL": {"tag": "nl-NL", "name": "ดัตช์ (เนเธอร์แลนด์)", "nativeName": "Nederlands (Nederland)", "primary": true},
    "nl-BE": {"tag": "nl-BE", "name": "ดัตช์ (เบลเยียม)", "nativeName": "Nederlands (België)", "primary": false},
    "bn-BD": {"tag": "bn-BD", "name": "เบงกาลี (บังกลาเทศ)", "nativeName": "বাংলা (বাংলাদেশ)", "primary": false},
    "pl-PL": {"tag": "pl-PL", "name": "โปแลนด์ (โปแลนด์)", "nativeName": "Polski (Polska)", "primary": false},
    "vi-VN": {"tag": "vi-VN", "name": "เวียดนาม (เวียดนาม)", "nativeName": "Tiếng Việt (Việt Nam)", "primary": false},
    "tr-TR": {"tag": "tr-TR", "name": "ตุรกี (ตุรกี)", "nativeName": "Türkçe (Türkiye)", "primary": false},
    "th-TH": {"tag": "th-TH", "name": "ไทย (ประเทศไทย)", "nativeName": "ไทย (ประเทศไทย)", "primary": false},
    "el-GR": {"tag": "el-GR", "name": "กรีก (กรีซ)", "nativeName": "Ελληνικά (Ελλάδα)", "primary": false},
    "cs-CZ": {"tag": "cs-CZ", "name": "เช็ก (สาธารณรัฐเช็ก)", "nativeName": "Čeština (Česká republika)", "primary": false},
    "sv-SE": {"tag": "sv-SE", "name": "สวีเดน (สวีเดน)", "nativeName": "Svenska (Sverige)", "primary": false },
    "sv-FI": {"tag": "sv-FI", "name": "สวีเดน (ฟินแลนด์)", "nativeName": "Svenska (Finland)", "primary": false},
    "hu-HU": {"tag": "hu-HU", "name": "ฮังการี (ฮังการี)", "nativeName": "Magyar (Magyarország)", "primary": false},
    "fi-FI": {"tag": "fi-FI", "name": "ฟินแลนด์ (ฟินแลนด์)", "nativeName": "Suomi (Suomi)", "primary": false},
    "da-DK": {"tag": "da-DK", "name": "เดนมาร์ก (เดนมาร์ก)", "nativeName": "Dansk (Danmark)", "primary": false},
    "nb-NO": {"tag": "nb-NO", "name": "นอร์เวย์ บุคมอล (นอร์เวย์)", "nativeName": "Norsk Bokmål (Norge)", "primary": false},
    "nn-NO": {"tag": "nn-NO", "name": "นอร์เวย์ นือนอร์สก์ (นอร์เวย์)", "nativeName": "Norsk Nynorsk (Norge)", "primary": false},
    "he-IL": {"tag": "he-IL", "name": "ฮีบรู (อิสราเอล)", "nativeName": "עברית (ישראל)", "primary": false},
    "id-ID": {"tag": "id-ID", "name": "อินโดนีเซีย (อินโดนีเซีย)", "nativeName": "Bahasa Indonesia (Indonesia)", "primary": false},
    "ms-MY": {"tag": "ms-MY", "name": "มาเลย์ (มาเลเซีย)", "nativeName": "Bahasa Melayu (Malaysia)", "primary": false},
    "ms-BN": {"tag": "ms-BN", "name": "มาเลย์ (บรูไน)", "nativeName": "Bahasa Melayu (Brunei)", "primary": false},
    "ro-RO": {"tag": "ro-RO", "name": "โรมาเนีย (โรมาเนีย)", "nativeName": "Română (România)", "primary": false},
    "bg-BG": {"tag": "bg-BG", "name": "บัลแกเรีย (บัลแกเรีย)", "nativeName": "Български (България)", "primary": false},
    "uk-UA": {"tag": "uk-UA", "name": "ยูเครน (ยูเครน)", "nativeName": "Українська (Україна)", "primary": false},
    "sk-SK": {"tag": "sk-SK", "name": "สโลวัก (สโลวาเกีย)", "nativeName": "Slovenčina (Slovensko)", "primary": false},
    "sl-SI": {"tag": "sl-SI", "name": "สโลวีเนีย (สโลวีเนีย)", "nativeName": "Slovenščina (Slovenija)", "primary": false},
    "hr-HR": {"tag": "hr-HR", "name": "โครเอเชีย (โครเอเชีย)", "nativeName": "Hrvatski (Hrvatska)", "primary": false},
    "ca-ES": {"tag": "ca-ES", "name": "คาตาลัน (คาตาโลเนีย)", "nativeName": "Català (Catalunya)", "primary": false},
    "lt-LT": {"tag": "lt-LT", "name": "ลิทัวเนีย (ลิทัวเนีย)", "nativeName": "Lietuvių (Lietuva)", "primary": false},
    "lv-LV": {"tag": "lv-LV", "name": "ลัตเวีย (ลัตเวีย)", "nativeName": "Latviešu (Latvija)", "primary": false},
    "et-EE": {"tag": "et-EE", "name": "เอสโตเนีย (เอสโตเนีย)", "nativeName": "Eesti (Eesti)", "primary": false},        
    "sq-AL": {"tag": "sq-AL", "name": "แอลเบเนีย (แอลเบเนีย)", "nativeName": "Shqip (Shqipëri)", "primary": false},
    "mk-MK": {"tag": "mk-MK", "name": "มาซิโดเนีย (มาซิโดเนียเหนือ)", "nativeName": "Македонски (Македонија)", "primary": false},
    "be-BY": {"tag": "be-BY", "name": "เบลารุส (เบลารุส)", "nativeName": "Беларуская (Беларусь)", "primary": false},
    "is-IS": {"tag": "is-IS", "name": "ไอซ์แลนด์ (ไอซ์แลนด์)", "nativeName": "Íslenska (Ísland)", "primary": false},
    "gl-ES": {"tag": "gl-ES", "name": "กาลิเซีย (กาลิเซีย)", "nativeName": "Galego (Galicia)", "primary": false},
    "eu-ES": {"tag": "eu-ES", "name": "บาสก์ (ประเทศบาสก์)", "nativeName": "Euskara (Euskal Herria)", "primary": false},
    "af-ZA": {"tag": "af-ZA", "name": "แอฟริกานส์ (แอฟริกาใต้)", "nativeName": "Afrikaans (Suid-Afrika)", "primary": false},
    "sw-KE": {"tag": "sw-KE", "name": "สวาฮีลี (เคนยา)", "nativeName": "Kiswahili (Kenya)", "primary": false},
    "ta-IN": {"tag": "ta-IN", "name": "ทมิฬ (อินเดีย)", "nativeName": "தமிழ் (இந்தியா)", "primary": false},
    "te-IN": {"tag": "te-IN", "name": "เตลูกู (อินเดีย)", "nativeName": "తెలుగు (భారతదేశం)", "primary": false},
    "kn-IN": {"tag": "kn-IN", "name": "กันนาดา (อินเดีย)", "nativeName": "ಕನ್ನಡ (ಭಾರತ)", "primary": false},
    "mr-IN": {"tag": "mr-IN", "name": "มราฐี (อินเดีย)", "nativeName": "मराठी (भारत)", "primary": false},
    "gu-IN": {"tag": "gu-IN", "name": "คุชราต (อินเดีย)", "nativeName": "ગુજરાતી (ભારત)", "primary": false},
    "pa-IN": {"tag": "pa-IN", "name": "ปัญจาบ (อินเดีย)", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)", "primary": false},
    "kok-IN": {"tag": "kok-IN", "name": "กอนกณี (อินเดีย)", "nativeName": "कोंकणी (भारत)", "primary": false},
    "sa-IN": {"tag": "sa-IN", "name": "สันสกฤต (อินเดีย)", "nativeName": "संस्कृत (भारत)", "primary": false},
    "ur-PK": {"tag": "ur-PK", "name": "อูรดู (ปากีสถาน)", "nativeName": "اردو (پاکستان)", "primary": false},
    "fa-IR": {"tag": "fa-IR", "name": "เปอร์เซีย (อิหร่าน)", "nativeName": "فارسی (ایران)", "primary": false},
    "syr-SY": {"tag": "syr-SY", "name": "ซีเรีย (ซีเรีย)", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)", "primary": false},
    "div-MV": {"tag": "div-MV", "name": "ดิเวหิ (มัลดีฟส์)", "nativeName": "ދިވެހި (މޯލްޑިވްސް)", "primary": false},
    "ka-GE": {"tag": "ka-GE", "name": "จอร์เจีย (จอร์เจีย)", "nativeName": "ქართული (საქართველო)", "primary": false},
    "am-ET": {"tag": "am-ET", "name": "อัมฮารา (เอธิโอเปีย)", "nativeName": "አማርኛ (ኢትዮጵያ)", "primary": false},
    "my-MM": {"tag": "my-MM", "name": "พม่า (เมียนมา)", "nativeName": "မြန်မာ (မြန်မာ)", "primary": false}
}



const { getTag, getTags, getPrimaryTags } = createTagUtils(tags)
export {
    getTag, getTags,getPrimaryTags
}
export * from './types'    
