import { createTagUtils } from "./utils";

export const tags = {
  "zh-CN": {
    tag: "zh-CN",
    name: "Basitleştirilmiş Çince",
    nativeName: "简体中文",
    primary: true,
  },
  "zh-TW": {
    tag: "zh-TW",
    name: "Geleneksel Çince (Tayvan)",
    nativeName: "繁體中文(臺灣)",
    primary: false,
  },
  "zh-HK": {
    tag: "zh-HK",
    name: "Geleneksel Çince (Hong Kong)",
    nativeName: "繁體中文(香港),",
    primary: false,
  },
  "zh-SG": {
    tag: "zh-SG",
    name: "Basitleştirilmiş Çince (Singapur)",
    nativeName: "简体中文(新加坡)",
    primary: false,
  },
  "zh-MO": {
    tag: "zh-MO",
    name: "Geleneksel Çince (Makao)",
    nativeName: "繁體中文(澳門)",
    primary: false,
  },
  "zh-CHS": {
    tag: "zh-CHS",
    name: "Basitleştirilmiş Çince",
    nativeName: "简体中文,",
    primary: false,
  },
  "zh-CHT": {
    tag: "zh-CHT",
    name: "Geleneksel Çince",
    nativeName: "繁體中文,",
    primary: false,
  },
  "en-US": {
    tag: "en-US",
    name: "İngilizce (Amerika Birleşik Devletleri)",
    nativeName: "English (United States)",
    primary: true,
  },
  "en-GB": {
    tag: "en-GB",
    name: "İngilizce (Birleşik Krallık)",
    nativeName: "English (United Kingdom)",
    primary: false,
  },
  "en-IN": {
    tag: "en-IN",
    name: "İngilizce (Hindistan)",
    nativeName: "English (India)",
    primary: false,
  },
  "en-CA": {
    tag: "en-CA",
    name: "İngilizce (Kanada)",
    nativeName: "English (Canada)",
    primary: false,
  },
  "en-AU": {
    tag: "en-AU",
    name: "İngilizce (Avustralya)",
    nativeName: "English (Australia)",
    primary: false,
  },
  "en-ZA": {
    tag: "en-ZA",
    name: "İngilizce (Güney Afrika)",
    nativeName: "English (South Africa)",
    primary: false,
  },
  "en-NZ": {
    tag: "en-NZ",
    name: "İngilizce (Yeni Zelanda)",
    nativeName: "English (New Zealand)",
    primary: false,
  },
  "en-IE": {
    tag: "en-IE",
    name: "İngilizce (İrlanda)",
    nativeName: "English (Ireland)",
    primary: false,
  },
  "en-PH": {
    tag: "en-PH",
    name: "İngilizce (Filipinler)",
    nativeName: "English (Philippines)",
    primary: false,
  },
  "en-ZW": {
    tag: "en-ZW",
    name: "İngilizce (Zimbabve)",
    nativeName: "English (Zimbabwe)",
    primary: false,
  },
  "en-BZ": {
    tag: "en-BZ",
    name: "İngilizce (Belize)",
    nativeName: "English (Belize)",
    primary: false,
  },
  "en-CB": {
    tag: "en-CB",
    name: "İngilizce (Karayipler)",
    nativeName: "English (Caribbean)",
    primary: false,
  },
  "en-JM": {
    tag: "en-JM",
    name: "İngilizce (Jamaika)",
    nativeName: "English (Jamaica)",
    primary: false,
  },
  "en-TT": {
    tag: "en-TT",
    name: "İngilizce (Trinidad ve Tobago)",
    nativeName: "English (Trinidad and Tobago)",
    primary: false,
  },
  "en-NG": {
    tag: "en-NG",
    name: "İngilizce (Nijerya)",
    nativeName: "English (Nigeria)",
    primary: false,
  },
  "en-UG": {
    tag: "en-UG",
    name: "İngilizce (Uganda)",
    nativeName: "English (Uganda)",
    primary: false,
  },
  "hi-IN": {
    tag: "hi-IN",
    name: "Hintçe",
    nativeName: "हिन्दी (Hindi)",
    primary: false,
  },
  "es-ES": {
    tag: "es-ES",
    name: "İspanyolca (İspanya)",
    nativeName: "Español (España)",
    primary: true,
  },
  "es-MX": {
    tag: "es-MX",
    name: "İspanyolca (Meksika)",
    nativeName: "Español (México)",
    primary: false,
  },
  "es-AR": {
    tag: "es-AR",
    name: "İspanyolca (Arjantin)",
    nativeName: "Español (Argentina)",
    primary: false,
  },
  "es-CO": {
    tag: "es-CO",
    name: "İspanyolca (Kolombiya)",
    nativeName: "Español (Colombia)",
    primary: false,
  },
  "es-PE": {
    tag: "es-PE",
    name: "İspanyolca (Peru)",
    nativeName: "Español (Perú)",
    primary: false,
  },
  "es-VE": {
    tag: "es-VE",
    name: "İspanyolca (Venezuela)",
    nativeName: "Español (Venezuela)",
    primary: false,
  },
  "es-CL": {
    tag: "es-CL",
    name: "İspanyolca (Şili)",
    nativeName: "Español (Chile)",
    primary: false,
  },
  "es-EC": {
    tag: "es-EC",
    name: "İspanyolca (Ekvador)",
    nativeName: "Español (Ecuador)",
    primary: false,
  },
  "es-GT": {
    tag: "es-GT",
    name: "İspanyolca (Guatemala)",
    nativeName: "Español (Guatemala)",
    primary: false,
  },
  "es-CU": {
    tag: "es-CU",
    name: "İspanyolca (Küba)",
    nativeName: "Español (Cuba)",
    primary: false,
  },
  "es-BO": {
    tag: "es-BO",
    name: "İspanyolca (Bolivya)",
    nativeName: "Español (Bolivia)",
    primary: false,
  },
  "es-DO": {
    tag: "es-DO",
    name: "İspanyolca (Dominikan Cumhuriyeti)",
    nativeName: "Español (República Dominicana)",
    primary: false,
  },
  "es-HN": {
    tag: "es-HN",
    name: "İspanyolca (Honduras)",
    nativeName: "Español (Honduras)",
    primary: false,
  },
  "es-PY": {
    tag: "es-PY",
    name: "İspanyolca (Paraguay)",
    nativeName: "Español (Paraguay)",
    primary: false,
  },
  "es-SV": {
    tag: "es-SV",
    name: "İspanyolca (El Salvador)",
    nativeName: "Español (El Salvador)",
    primary: false,
  },
  "es-NI": {
    tag: "es-NI",
    name: "İspanyolca (Nikaragua)",
    nativeName: "Español (Nicaragua)",
    primary: false,
  },
  "es-PR": {
    tag: "es-PR",
    name: "İspanyolca (Porto Riko)",
    nativeName: "Español (Puerto Rico)",
    primary: false,
  },
  "es-UY": {
    tag: "es-UY",
    name: "İspanyolca (Uruguay)",
    nativeName: "Español (Uruguay)",
    primary: false,
  },
  "es-PA": {
    tag: "es-PA",
    name: "İspanyolca (Panama)",
    nativeName: "Español (Panamá)",
    primary: false,
  },
  "es-CR": {
    tag: "es-CR",
    name: "İspanyolca (Kosta Rika)",
    nativeName: "Español (Costa Rica)",
    primary: false,
  },
  "ar-EG": {
    tag: "ar-EG",
    name: "Arapça (Mısır)",
    nativeName: "العربية (مصر)",
    primary: true,
  },
  "ar-SA": {
    tag: "ar-SA",
    name: "Arapça (Suudi Arabistan)",
    nativeName: "العربية (السعودية)",
    primary: false,
  },
  "ar-DZ": {
    tag: "ar-DZ",
    name: "Arapça (Cezayir)",
    nativeName: "العربية (الجزائر)",
    primary: false,
  },
  "ar-MA": {
    tag: "ar-MA",
    name: "Arapça (Fas)",
    nativeName: "العربية (المغرب)",
    primary: false,
  },
  "ar-IQ": {
    tag: "ar-IQ",
    name: "Arapça (Irak)",
    nativeName: "العربية (العراق)",
    primary: false,
  },
  "ar-SD": {
    tag: "ar-SD",
    name: "Arapça (Sudan)",
    nativeName: "العربية (السودان)",
    primary: false,
  },
  "ar-YE": {
    tag: "ar-YE",
    name: "Arapça (Yemen)",
    nativeName: "العربية (اليمن)",
    primary: false,
  },
  "ar-SY": {
    tag: "ar-SY",
    name: "Arapça (Suriye)",
    nativeName: "العربية (سوريا)",
    primary: false,
  },
  "ar-TN": {
    tag: "ar-TN",
    name: "Arapça (Tunus)",
    nativeName: "العربية (تونس)",
    primary: false,
  },
  "ar-LY": {
    tag: "ar-LY",
    name: "Arapça (Libya)",
    nativeName: "العربية (ليبيا)",
    primary: false,
  },
  "ar-JO": {
    tag: "ar-JO",
    name: "Arapça (Ürdün)",
    nativeName: "العربية (الأردن)",
    primary: false,
  },
  "ar-LB": {
    tag: "ar-LB",
    name: "Arapça (Lübnan)",
    nativeName: "العربية (لبنان)",
    primary: false,
  },
  "ar-KW": {
    tag: "ar-KW",
    name: "Arapça (Kuveyt)",
    nativeName: "العربية (الكويت)",
    primary: false,
  },
  "ar-AE": {
    tag: "ar-AE",
    name: "Arapça (Birleşik Arap Emirlikleri)",
    nativeName: "العربية (الإمارات)",
    primary: false,
  },
  "ar-BH": {
    tag: "ar-BH",
    name: "Arapça (Bahreyn)",
    nativeName: "العربية (البحرين)",
    primary: false,
  },
  "ar-QA": {
    tag: "ar-QA",
    name: "Arapça (Katar)",
    nativeName: "العربية (قطر)",
    primary: false,
  },
  "ar-OM": {
    tag: "ar-OM",
    name: "Arapça (Umman)",
    nativeName: "العربية (عمان)",
    primary: false,
  },
  "pt-BR": {
    tag: "pt-BR",
    name: "Portekizce (Brezilya)",
    nativeName: "Português (Brasil)",
    primary: false,
  },
  "pt-PT": {
    tag: "pt-PT",
    name: "Portekizce (Portekiz)",
    nativeName: "Português (Portugal)",
    primary: true,
  },
  "ru-RU": {
    tag: "ru-RU",
    name: "Rusça",
    nativeName: "Русский (Россия)",
    primary: true,
  },
  "ja-JP": {
    tag: "ja-JP",
    name: "Japonca",
    nativeName: "日本語 (日本)",
    primary: true,
  },
  "de-DE": {
    tag: "de-DE",
    name: "Almanca (Almanya)",
    nativeName: "Deutsch (Deutschland)",
    primary: true,
  },
  "de-AT": {
    tag: "de-AT",
    name: "Almanca (Avusturya)",
    nativeName: "Deutsch (Österreich)",
    primary: false,
  },
  "de-CH": {
    tag: "de-CH",
    name: "Almanca (İsviçre)",
    nativeName: "Deutsch (Schweiz)",
    primary: false,
  },
  "fr-FR": {
    tag: "fr-FR",
    name: "Fransızca (Fransa)",
    nativeName: "Français (France)",
    primary: true,
  },
  "fr-CA": {
    tag: "fr-CA",
    name: "Fransızca (Kanada)",
    nativeName: "Français (Canada)",
    primary: false,
  },
  "fr-BE": {
    tag: "fr-BE",
    name: "Fransızca (Belçika)",
    nativeName: "Français (Belgique)",
    primary: false,
  },
  "fr-CH": {
    tag: "fr-CH",
    name: "Fransızca (İsviçre)",
    nativeName: "Français (Suisse)",
    primary: false,
  },
  "fr-LU": {
    tag: "fr-LU",
    name: "Fransızca (Lüksemburg)",
    nativeName: "Français (Luxembourg)",
    primary: false,
  },
  "fr-MC": {
    tag: "fr-MC",
    name: "Fransızca (Monako)",
    nativeName: "Français (Monaco)",
    primary: false,
  },
  "fr-CD": {
    tag: "fr-CD",
    name: "Fransızca (Demokratik Kongo Cumhuriyeti)",
    nativeName: "Français (République démocratique du Congo)",
    primary: false,
  },
  "ko-KR": {
    tag: "ko-KR",
    name: "Korece (Güney Kore)",
    nativeName: "한국어 (대한민국)",
    primary: true,
  },
  "ko-KP": {
    tag: "ko-KP",
    name: "Korece (Kuzey Kore)",
    nativeName: "한국어 (조선민주주인민공화국)",
    primary: false,
  },
  "it-IT": {
    tag: "it-IT",
    name: "İtalyanca",
    nativeName: "Italiano (Italia)",
    primary: true,
  },
  "it-CH": {
    tag: "it-CH",
    name: "İtalyanca (İsviçre)",
    nativeName: "Italiano (Svizzera)",
    primary: false,
  },
  "nl-NL": {
    tag: "nl-NL",
    name: "Felemenkçe",
    nativeName: "Nederlands (Nederland)",
    primary: true,
  },
  "nl-BE": {
    tag: "nl-BE",
    name: "Felemenkçe (Belçika)",
    nativeName: "Nederlands (België)",
    primary: false,
  },
  "bn-BD": {
    tag: "bn-BD",
    name: "Bengalce (Bangladeş)",
    nativeName: "বাংলা (বাংলাদেশ)",
    primary: false,
  },
  "pl-PL": {
    tag: "pl-PL",
    name: "Lehçe",
    nativeName: "Polski (Polska)",
    primary: false,
  },
  "vi-VN": {
    tag: "vi-VN",
    name: "Vietnamca",
    nativeName: "Tiếng Việt (Việt Nam)",
    primary: false,
  },
  "tr-TR": {
    tag: "tr-TR",
    name: "Türkçe",
    nativeName: "Türkçe (Türkiye)",
    primary: true,
  },
  "th-TH": {
    tag: "th-TH",
    name: "Tayca",
    nativeName: "ไทย (ประเทศไทย)",
    primary: false,
  },
  "el-GR": {
    tag: "el-GR",
    name: "Yunanca",
    nativeName: "Ελληνικά (Ελλάδα)",
    primary: false,
  },
  "cs-CZ": {
    tag: "cs-CZ",
    name: "Çekçe",
    nativeName: "Čeština (Česká republika)",
    primary: false,
  },
  "sv-SE": {
    tag: "sv-SE",
    name: "İsveççe",
    nativeName: "Svenska (Sverige)",
    primary: false,
  },
  "sv-FI": {
    tag: "sv-FI",
    name: "İsveççe (Finlandiya)",
    nativeName: "Svenska (Finland)",
    primary: false,
  },
  "hu-HU": {
    tag: "hu-HU",
    name: "Macarca",
    nativeName: "Magyar (Magyarország)",
    primary: false,
  },
  "fi-FI": {
    tag: "fi-FI",
    name: "Fince",
    nativeName: "Suomi (Suomi)",
    primary: false,
  },
  "da-DK": {
    tag: "da-DK",
    name: "Danca",
    nativeName: "Dansk (Danmark)",
    primary: false,
  },
  "nb-NO": {
    tag: "nb-NO",
    name: "Norveççe (Bokmål)",
    nativeName: "Norsk Bokmål (Norge)",
    primary: false,
  },
  "nn-NO": {
    tag: "nn-NO",
    name: "Norveççe (Nynorsk)",
    nativeName: "Norsk Nynorsk (Norge)",
    primary: false,
  },
  "he-IL": {
    tag: "he-IL",
    name: "İbranice",
    nativeName: "עברית (ישראל)",
    primary: false,
  },
  "id-ID": {
    tag: "id-ID",
    name: "Endonezce",
    nativeName: "Bahasa Indonesia (Indonesia)",
    primary: false,
  },
  "ms-MY": {
    tag: "ms-MY",
    name: "Malayca (Malezya)",
    nativeName: "Bahasa Melayu (Malaysia)",
    primary: false,
  },
  "ms-BN": {
    tag: "ms-BN",
    name: "Malayca (Brunei)",
    nativeName: "Bahasa Melayu (Brunei)",
    primary: false,
  },
  "ro-RO": {
    tag: "ro-RO",
    name: "Rumence",
    nativeName: "Română (România)",
    primary: false,
  },
  "bg-BG": {
    tag: "bg-BG",
    name: "Bulgarca",
    nativeName: "Български (България)",
    primary: false,
  },
  "uk-UA": {
    tag: "uk-UA",
    name: "Ukraynaca",
    nativeName: "Українська (Україна)",
    primary: false,
  },
  "sk-SK": {
    tag: "sk-SK",
    name: "Slovakça",
    nativeName: "Slovenčina (Slovensko)",
    primary: false,
  },
  "sl-SI": {
    tag: "sl-SI",
    name: "Slovence",
    nativeName: "Slovenščina (Slovenija)",
    primary: false,
  },
  "hr-HR": {
    tag: "hr-HR",
    name: "Hırvatça",
    nativeName: "Hrvatski (Hrvatska)",
    primary: false,
  },
  "ca-ES": {
    tag: "ca-ES",
    name: "Katalanca",
    nativeName: "Català (Catalunya)",
    primary: false,
  },
  "lt-LT": {
    tag: "lt-LT",
    name: "Litvanca",
    nativeName: "Lietuvių (Lietuva)",
    primary: false,
  },
  "lv-LV": {
    tag: "lv-LV",
    name: "Letonca",
    nativeName: "Latviešu (Latvija)",
    primary: false,
  },
  "et-EE": {
    tag: "et-EE",
    name: "Estonca",
    nativeName: "Eesti (Eesti)",
    primary: false,
  },
  "sq-AL": {
    tag: "sq-AL",
    name: "Arnavutça",
    nativeName: "Shqip (Shqipëri)",
    primary: false,
  },
  "mk-MK": {
    tag: "mk-MK",
    name: "Makedonca",
    nativeName: "Македонски (Македонија)",
    primary: false,
  },
  "be-BY": {
    tag: "be-BY",
    name: "Belarusça",
    nativeName: "Беларуская (Беларусь)",
    primary: false,
  },
  "is-IS": {
    tag: "is-IS",
    name: "İzlandaca",
    nativeName: "Íslenska (Ísland)",
    primary: false,
  },
  "gl-ES": {
    tag: "gl-ES",
    name: "Galiçyaca",
    nativeName: "Galego (Galicia)",
    primary: false,
  },
  "eu-ES": {
    tag: "eu-ES",
    name: "Baskça",
    nativeName: "Euskara (Euskal Herria)",
    primary: false,
  },
  "af-ZA": {
    tag: "af-ZA",
    name: "Afrikaanca",
    nativeName: "Afrikaans (Suid-Afrika)",
    primary: false,
  },
  "sw-KE": {
    tag: "sw-KE",
    name: "Swahili",
    nativeName: "Kiswahili (Kenya)",
    primary: false,
  },
  "ta-IN": {
    tag: "ta-IN",
    name: "Tamilce",
    nativeName: "தமிழ் (இந்தியா)",
    primary: false,
  },
  "te-IN": {
    tag: "te-IN",
    name: "Telugu dili",
    nativeName: "తెలుగు (భారతదేశం)",
    primary: false,
  },
  "kn-IN": {
    tag: "kn-IN",
    name: "Kannada dili",
    nativeName: "ಕನ್ನಡ (ಭಾರತ)",
    primary: false,
  },
  "mr-IN": {
    tag: "mr-IN",
    name: "Marathi dili",
    nativeName: "मराठी (भारत)",
    primary: false,
  },
  "gu-IN": {
    tag: "gu-IN",
    name: "Gujarati dili",
    nativeName: "ગુજરાતી (ભારત)",
    primary: false,
  },
  "pa-IN": {
    tag: "pa-IN",
    name: "Pencap dili",
    nativeName: "ਪੰਜਾਬੀ (ਭਾਰਤ)",
    primary: false,
  },
  "kok-IN": {
    tag: "kok-IN",
    name: "Konkani dili",
    nativeName: "कोंकणी (भारत)",
    primary: false,
  },
  "sa-IN": {
    tag: "sa-IN",
    name: "Sanskritçe",
    nativeName: "संस्कृत (भारत)",
    primary: false,
  },
  "ur-PK": {
    tag: "ur-PK",
    name: "Urdu dili",
    nativeName: "اردو (پاکستان)",
    primary: false,
  },
  "fa-IR": {
    tag: "fa-IR",
    name: "Farsça",
    nativeName: "فارسی (ایران)",
    primary: false,
  },
  "syr-SY": {
    tag: "syr-SY",
    name: "Süryanice",
    nativeName: "ܣܘܪܝܝܐ (ܣܘܪܝܐ)",
    primary: false,
  },
  "div-MV": {
    tag: "div-MV",
    name: "Divehi dili",
    nativeName: "ދިވެހި (މޯލްޑިވްސް)",
    primary: false,
  },
  "ka-GE": {
    tag: "ka-GE",
    name: "Gürcüce",
    nativeName: "ქართული (საქართველო)",
    primary: false,
  },
  "am-ET": {
    tag: "am-ET",
    name: "Amharca",
    nativeName: "አማርኛ (ኢትዮጵያ)",
    primary: false,
  },
  "my-MM": {
    tag: "my-MM",
    name: "Birmanca",
    nativeName: "မြန်မာ (မြန်မာ)",
    primary: false,
  },
};

const { getTag, getTags, getPrimaryTags } = createTagUtils(tags);
export { getTag, getTags, getPrimaryTags };
export * from "./types";
