import { createTagUtils } from "./utils";

export const tags = {
  "zh-CN": {
    tag: "zh-CN",
    name: "Tiếng Trung giản thể",
    nativeName: "简体中文",
    primary: true,
  },
  "zh-TW": {
    tag: "zh-TW",
    name: "Tiếng Trung phồn thể (Đài Loan)",
    nativeName: "繁體中文(中國臺灣)",
    primary: false,
  },
  "zh-HK": {
    tag: "zh-HK",
    name: "Tiếng Trung phồn thể (Hồng Kông)",
    nativeName: "繁體中文(中國香港),",
    primary: false,
  },
  "zh-SG": {
    tag: "zh-SG",
    name: "Tiếng Trung giản thể (Singapore)",
    nativeName: "简体中文(新加坡)",
    primary: false,
  },
  "zh-MO": {
    tag: "zh-MO",
    name: "Tiếng Trung phồn thể (Macau)",
    nativeName: "繁體中文(中國澳門)",
    primary: false,
  },
  "zh-CHS": {
    tag: "zh-CHS",
    name: "Tiếng Trung giản thể",
    nativeName: "简体中文,",
    primary: false,
  },
  "zh-CHT": {
    tag: "zh-CHT",
    name: "Tiếng Trung phồn thể",
    nativeName: "繁體中文,",
    primary: false,
  },
  "en-US": {
    tag: "en-US",
    name: "Tiếng Anh (Hoa Kỳ)",
    nativeName: "English (United States)",
    primary: true,
  },
  "en-GB": {
    tag: "en-GB",
    name: "Tiếng Anh (Vương quốc Anh)",
    nativeName: "English (United Kingdom)",
    primary: false,
  },
  "en-IN": {
    tag: "en-IN",
    name: "Tiếng Anh (Ấn Độ)",
    nativeName: "English (India)",
    primary: false,
  },
  "en-CA": {
    tag: "en-CA",
    name: "Tiếng Anh (Canada)",
    nativeName: "English (Canada)",
    primary: false,
  },
  "en-AU": {
    tag: "en-AU",
    name: "Tiếng Anh (Úc)",
    nativeName: "English (Australia)",
    primary: false,
  },
  "en-ZA": {
    tag: "en-ZA",
    name: "Tiếng Anh (Nam Phi)",
    nativeName: "English (South Africa)",
    primary: false,
  },
  "en-NZ": {
    tag: "en-NZ",
    name: "Tiếng Anh (New Zealand)",
    nativeName: "English (New Zealand)",
    primary: false,
  },
  "en-IE": {
    tag: "en-IE",
    name: "Tiếng Anh (Ireland)",
    nativeName: "English (Ireland)",
    primary: false,
  },
  "en-PH": {
    tag: "en-PH",
    name: "Tiếng Anh (Philippines)",
    nativeName: "English (Philippines)",
    primary: false,
  },
  "en-ZW": {
    tag: "en-ZW",
    name: "Tiếng Anh (Zimbabwe)",
    nativeName: "English (Zimbabwe)",
    primary: false,
  },
  "en-BZ": {
    tag: "en-BZ",
    name: "Tiếng Anh (Belize)",
    nativeName: "English (Belize)",
    primary: false,
  },
  "en-CB": {
    tag: "en-CB",
    name: "Tiếng Anh (Caribbean)",
    nativeName: "English (Caribbean)",
    primary: false,
  },
  "en-JM": {
    tag: "en-JM",
    name: "Tiếng Anh (Jamaica)",
    nativeName: "English (Jamaica)",
    primary: false,
  },
  "en-TT": {
    tag: "en-TT",
    name: "Tiếng Anh (Trinidad và Tobago)",
    nativeName: "English (Trinidad and Tobago)",
    primary: false,
  },
  "en-NG": {
    tag: "en-NG",
    name: "Tiếng Anh (Nigeria)",
    nativeName: "English (Nigeria)",
    primary: false,
  },
  "en-UG": {
    tag: "en-UG",
    name: "Tiếng Anh (Uganda)",
    nativeName: "English (Uganda)",
    primary: false,
  },
  "hi-IN": {
    tag: "hi-IN",
    name: "Tiếng Hindi",
    nativeName: "हिन्दी (Hindi)",
    primary: false,
  },
  "es-ES": {
    tag: "es-ES",
    name: "Tiếng Tây Ban Nha (Tây Ban Nha)",
    nativeName: "Español (España)",
    primary: true,
  },
  "es-MX": {
    tag: "es-MX",
    name: "Tiếng Tây Ban Nha (Mexico)",
    nativeName: "Español (México)",
    primary: false,
  },
  "es-AR": {
    tag: "es-AR",
    name: "Tiếng Tây Ban Nha (Argentina)",
    nativeName: "Español (Argentina)",
    primary: false,
  },
  "es-CO": {
    tag: "es-CO",
    name: "Tiếng Tây Ban Nha (Colombia)",
    nativeName: "Español (Colombia)",
    primary: false,
  },
  "es-PE": {
    tag: "es-PE",
    name: "Tiếng Tây Ban Nha (Peru)",
    nativeName: "Español (Perú)",
    primary: false,
  },
  "es-VE": {
    tag: "es-VE",
    name: "Tiếng Tây Ban Nha (Venezuela)",
    nativeName: "Español (Venezuela)",
    primary: false,
  },
  "es-CL": {
    tag: "es-CL",
    name: "Tiếng Tây Ban Nha (Chile)",
    nativeName: "Español (Chile)",
    primary: false,
  },
  "es-EC": {
    tag: "es-EC",
    name: "Tiếng Tây Ban Nha (Ecuador)",
    nativeName: "Español (Ecuador)",
    primary: false,
  },
  "es-GT": {
    tag: "es-GT",
    name: "Tiếng Tây Ban Nha (Guatemala)",
    nativeName: "Español (Guatemala)",
    primary: false,
  },
  "es-CU": {
    tag: "es-CU",
    name: "Tiếng Tây Ban Nha (Cuba)",
    nativeName: "Español (Cuba)",
    primary: false,
  },
  "es-BO": {
    tag: "es-BO",
    name: "Tiếng Tây Ban Nha (Bolivia)",
    nativeName: "Español (Bolivia)",
    primary: false,
  },
  "es-DO": {
    tag: "es-DO",
    name: "Tiếng Tây Ban Nha (Cộng hòa Dominica)",
    nativeName: "Español (República Dominicana)",
    primary: false,
  },
  "es-HN": {
    tag: "es-HN",
    name: "Tiếng Tây Ban Nha (Honduras)",
    nativeName: "Español (Honduras)",
    primary: false,
  },
  "es-PY": {
    tag: "es-PY",
    name: "Tiếng Tây Ban Nha (Paraguay)",
    nativeName: "Español (Paraguay)",
    primary: false,
  },
  "es-SV": {
    tag: "es-SV",
    name: "Tiếng Tây Ban Nha (El Salvador)",
    nativeName: "Español (El Salvador)",
    primary: false,
  },
  "es-NI": {
    tag: "es-NI",
    name: "Tiếng Tây Ban Nha (Nicaragua)",
    nativeName: "Español (Nicaragua)",
    primary: false,
  },
  "es-PR": {
    tag: "es-PR",
    name: "Tiếng Tây Ban Nha (Puerto Rico)",
    nativeName: "Español (Puerto Rico)",
    primary: false,
  },
  "es-UY": {
    tag: "es-UY",
    name: "Tiếng Tây Ban Nha (Uruguay)",
    nativeName: "Español (Uruguay)",
    primary: false,
  },
  "es-PA": {
    tag: "es-PA",
    name: "Tiếng Tây Ban Nha (Panama)",
    nativeName: "Español (Panamá)",
    primary: false,
  },
  "es-CR": {
    tag: "es-CR",
    name: "Tiếng Tây Ban Nha (Costa Rica)",
    nativeName: "Español (Costa Rica)",
    primary: false,
  },
  "ar-EG": {
    tag: "ar-EG",
    name: "Tiếng Ả Rập (Ai Cập)",
    nativeName: "العربية (مصر)",
    primary: true,
  },
  "ar-SA": {
    tag: "ar-SA",
    name: "Tiếng Ả Rập (Saudi Arabia)",
    nativeName: "العربية (السعودية)",
    primary: false,
  },
  "ar-DZ": {
    tag: "ar-DZ",
    name: "Tiếng Ả Rập (Algeria)",
    nativeName: "العربية (الجزائر)",
    primary: false,
  },
  "ar-MA": {
    tag: "ar-MA",
    name: "Tiếng Ả Rập (Morocco)",
    nativeName: "العربية (المغرب)",
    primary: false,
  },
  "ar-IQ": {
    tag: "ar-IQ",
    name: "Tiếng Ả Rập (Iraq)",
    nativeName: "العربية (العراق)",
    primary: false,
  },
  "ar-SD": {
    tag: "ar-SD",
    name: "Tiếng Ả Rập (Sudan)",
    nativeName: "العربية (السودان)",
    primary: false,
  },
  "ar-YE": {
    tag: "ar-YE",
    name: "Tiếng Ả Rập (Yemen)",
    nativeName: "العربية (اليمن)",
    primary: false,
  },
  "ar-SY": {
    tag: "ar-SY",
    name: "Tiếng Ả Rập (Syria)",
    nativeName: "العربية (سوريا)",
    primary: false,
  },
  "ar-TN": {
    tag: "ar-TN",
    name: "Tiếng Ả Rập (Tunisia)",
    nativeName: "العربية (تونس)",
    primary: false,
  },
  "ar-LY": {
    tag: "ar-LY",
    name: "Tiếng Ả Rập (Libya)",
    nativeName: "العربية (ليبيا)",
    primary: false,
  },
  "ar-JO": {
    tag: "ar-JO",
    name: "Tiếng Ả Rập (Jordan)",
    nativeName: "العربية (الأردن)",
    primary: false,
  },
  "ar-LB": {
    tag: "ar-LB",
    name: "Tiếng Ả Rập (Lebanon)",
    nativeName: "العربية (لبنان)",
    primary: false,
  },
  "ar-KW": {
    tag: "ar-KW",
    name: "Tiếng Ả Rập (Kuwait)",
    nativeName: "العربية (الكويت)",
    primary: false,
  },
  "ar-AE": {
    tag: "ar-AE",
    name: "Tiếng Ả Rập (United Arab Emirates)",
    nativeName: "العربية (الإمارات)",
    primary: false,
  },
  "ar-BH": {
    tag: "ar-BH",
    name: "Tiếng Ả Rập (Bahrain)",
    nativeName: "العربية (البحرين)",
    primary: false,
  },
  "ar-QA": {
    tag: "ar-QA",
    name: "Tiếng Ả Rập (Qatar)",
    nativeName: "العربية (قطر)",
    primary: false,
  },
  "ar-OM": {
    tag: "ar-OM",
    name: "Tiếng Ả Rập (Oman)",
    nativeName: "العربية (عمان)",
    primary: false,
  },
  "pt-BR": {
    tag: "pt-BR",
    name: "Tiếng Bồ Đào Nha (Brazil)",
    nativeName: "Português (Brasil)",
    primary: false,
  },
  "pt-PT": {
    tag: "pt-PT",
    name: "Tiếng Bồ Đào Nha (Bồ Đào Nha)",
    nativeName: "Português (Portugal)",
    primary: true,
  },
  "ru-RU": {
    tag: "ru-RU",
    name: "Tiếng Nga",
    nativeName: "Русский (Россия)",
    primary: true,
  },
  "ja-JP": {
    tag: "ja-JP",
    name: "Tiếng Nhật",
    nativeName: "日本語 (日本)",
    primary: true,
  },
  "de-DE": {
    tag: "de-DE",
    name: "Tiếng Đức (Đức)",
    nativeName: "Deutsch (Deutschland)",
    primary: true,
  },
  "de-AT": {
    tag: "de-AT",
    name: "Tiếng Đức (Áo)",
    nativeName: "Deutsch (Österreich)",
    primary: false,
  },
  "de-CH": {
    tag: "de-CH",
    name: "Tiếng Đức (Thụy Sĩ)",
    nativeName: "Deutsch (Schweiz)",
    primary: false,
  },
  "fr-FR": {
    tag: "fr-FR",
    name: "Tiếng Pháp (Pháp)",
    nativeName: "Français (France)",
    primary: true,
  },
  "fr-CA": {
    tag: "fr-CA",
    name: "Tiếng Pháp (Canada)",
    nativeName: "Français (Canada)",
    primary: false,
  },
  "fr-BE": {
    tag: "fr-BE",
    name: "Tiếng Pháp (Bỉ)",
    nativeName: "Français (Belgique)",
    primary: false,
  },
  "fr-CH": {
    tag: "fr-CH",
    name: "Tiếng Pháp (Thụy Sĩ)",
    nativeName: "Français (Suisse)",
    primary: false,
  },
  "fr-LU": {
    tag: "fr-LU",
    name: "Tiếng Pháp (Luxembourg)",
    nativeName: "Français (Luxembourg)",
    primary: false,
  },
  "fr-MC": {
    tag: "fr-MC",
    name: "Tiếng Pháp (Monaco)",
    nativeName: "Français (Monaco)",
    primary: false,
  },
  "fr-CD": {
    tag: "fr-CD",
    name: "Tiếng Pháp (Cộng hòa Dân chủ Congo)",
    nativeName: "Français (République démocratique du Congo)",
    primary: false,
  },
  "ko-KR": {
    tag: "ko-KR",
    name: "Tiếng Hàn (Hàn Quốc)",
    nativeName: "한국어 (대한민국)",
    primary: true,
  },
  "ko-KP": {
    tag: "ko-KP",
    name: "Tiếng Hàn (Bắc Triều Tiên)",
    nativeName: "한국어 (조선민주주인민공화국)",
    primary: false,
  },
  "it-IT": {
    tag: "it-IT",
    name: "Tiếng Ý",
    nativeName: "Italiano (Italia)",
    primary: true,
  },
  "it-CH": {
    tag: "it-CH",
    name: "Tiếng Ý (Thụy Sĩ)",
    nativeName: "Italiano (Svizzera)",
    primary: false,
  },
  "nl-NL": {
    tag: "nl-NL",
    name: "Tiếng Hà Lan",
    nativeName: "Nederlands (Nederland)",
    primary: true,
  },
  "nl-BE": {
    tag: "nl-BE",
    name: "Tiếng Hà Lan (Bỉ)",
    nativeName: "Nederlands (België)",
    primary: false,
  },
  "bn-BD": {
    tag: "bn-BD",
    name: "Tiếng Bengal (Bangladesh)",
    nativeName: "বাংলা (বাংলাদেশ)",
    primary: false,
  },
  "pl-PL": {
    tag: "pl-PL",
    name: "Tiếng Ba Lan",
    nativeName: "Polski (Polska)",
    primary: false,
  },
  "vi-VN": {
    tag: "vi-VN",
    name: "Tiếng Việt",
    nativeName: "Tiếng Việt (Việt Nam)",
    primary: true,
  },
  "tr-TR": {
    tag: "tr-TR",
    name: "Tiếng Thổ Nhĩ Kỳ",
    nativeName: "Türkçe (Türkiye)",
    primary: false,
  },
  "th-TH": {
    tag: "th-TH",
    name: "Tiếng Thái",
    nativeName: "ไทย (ประเทศไทย)",
    primary: false,
  },
  "el-GR": {
    tag: "el-GR",
    name: "Tiếng Hy Lạp",
    nativeName: "Ελληνικά (Ελλάδα)",
    primary: false,
  },
  "cs-CZ": {
    tag: "cs-CZ",
    name: "Tiếng Séc",
    nativeName: "Čeština (Česká republika)",
    primary: false,
  },
  "sv-SE": {
    tag: "sv-SE",
    name: "Tiếng Thụy Điển",
    nativeName: "Svenska (Sverige)",
    primary: false,
  },
  "sv-FI": {
    tag: "sv-FI",
    name: "Tiếng Thụy Điển (Phần Lan)",
    nativeName: "Svenska (Finland)",
    primary: false,
  },
  "hu-HU": {
    tag: "hu-HU",
    name: "Tiếng Hungary",
    nativeName: "Magyar (Magyarország)",
    primary: false,
  },
  "fi-FI": {
    tag: "fi-FI",
    name: "Tiếng Phần Lan",
    nativeName: "Suomi (Suomi)",
    primary: false,
  },
  "da-DK": {
    tag: "da-DK",
    name: "Tiếng Đan Mạch",
    nativeName: "Dansk (Danmark)",
    primary: false,
  },
  "nb-NO": {
    tag: "nb-NO",
    name: "Tiếng Na Uy Bokmål",
    nativeName: "Norsk Bokmål (Norge)",
    primary: false,
  },
  "nn-NO": {
    tag: "nn-NO",
    name: "Tiếng Na Uy Nynorsk",
    nativeName: "Norsk Nynorsk (Norge)",
    primary: false,
  },
  "he-IL": {
    tag: "he-IL",
    name: "Tiếng Do Thái",
    nativeName: "עברית (ישראל)",
    primary: false,
  },
  "id-ID": {
    tag: "id-ID",
    name: "Tiếng Indonesia",
    nativeName: "Bahasa Indonesia (Indonesia)",
    primary: false,
  },
  "ms-MY": {
    tag: "ms-MY",
    name: "Tiếng Mã Lai (Malaysia)",
    nativeName: "Bahasa Melayu (Malaysia)",
    primary: false,
  },
  "ms-BN": {
    tag: "ms-BN",
    name: "Tiếng Mã Lai (Brunei)",
    nativeName: "Bahasa Melayu (Brunei)",
    primary: false,
  },
  "ro-RO": {
    tag: "ro-RO",
    name: "Tiếng Romania",
    nativeName: "Română (România)",
    primary: false,
  },
  "bg-BG": {
    tag: "bg-BG",
    name: "Tiếng Bulgaria",
    nativeName: "Български (България)",
    primary: false,
  },
  "uk-UA": {
    tag: "uk-UA",
    name: "Tiếng Ukraine",
    nativeName: "Українська (Україна)",
    primary: false,
  },
  "sk-SK": {
    tag: "sk-SK",
    name: "Tiếng Slovakia",
    nativeName: "Slovenčina (Slovensko)",
    primary: false,
  },
  "sl-SI": {
    tag: "sl-SI",
    name: "Tiếng Slovenia",
    nativeName: "Slovenščina (Slovenija)",
    primary: false,
  },
  "hr-HR": {
    tag: "hr-HR",
    name: "Tiếng Croatia",
    nativeName: "Hrvatski (Hrvatska)",
    primary: false,
  },
  "ca-ES": {
    tag: "ca-ES",
    name: "Tiếng Catalan",
    nativeName: "Català (Catalunya)",
    primary: false,
  },
  "lt-LT": {
    tag: "lt-LT",
    name: "Tiếng Lithuania",
    nativeName: "Lietuvių (Lietuva)",
    primary: false,
  },
  "lv-LV": {
    tag: "lv-LV",
    name: "Tiếng Latvia",
    nativeName: "Latviešu (Latvija)",
    primary: false,
  },
  "et-EE": {
    tag: "et-EE",
    name: "Tiếng Estonia",
    nativeName: "Eesti (Eesti)",
    primary: false,
  },
  "sq-AL": {
    tag: "sq-AL",
    name: "Tiếng Albania",
    nativeName: "Shqip (Shqipëri)",
    primary: false,
  },
  "mk-MK": {
    tag: "mk-MK",
    name: "Tiếng Macedonia",
    nativeName: "Македонски (Македонија)",
    primary: false,
  },
  "be-BY": {
    tag: "be-BY",
    name: "Tiếng Belarus",
    nativeName: "Беларуская (Беларусь)",
    primary: false,
  },
  "is-IS": {
    tag: "is-IS",
    name: "Tiếng Iceland",
    nativeName: "Íslenska (Ísland)",
    primary: false,
  },
  "gl-ES": {
    tag: "gl-ES",
    name: "Tiếng Galicia",
    nativeName: "Galego (Galicia)",
    primary: false,
  },
  "eu-ES": {
    tag: "eu-ES",
    name: "Tiếng Basque",
    nativeName: "Euskara (Euskal Herria)",
    primary: false,
  },
  "af-ZA": {
    tag: "af-ZA",
    name: "Tiếng Afrikaans",
    nativeName: "Afrikaans (Suid-Afrika)",
    primary: false,
  },
  "sw-KE": {
    tag: "sw-KE",
    name: "Tiếng Swahili",
    nativeName: "Kiswahili (Kenya)",
    primary: false,
  },
  "ta-IN": {
    tag: "ta-IN",
    name: "Tiếng Tamil",
    nativeName: "தமிழ் (இந்தியா)",
    primary: false,
  },
  "te-IN": {
    tag: "te-IN",
    name: "Tiếng Telugu",
    nativeName: "తెలుగు (భారతదేశం)",
    primary: false,
  },
  "kn-IN": {
    tag: "kn-IN",
    name: "Tiếng Kannada",
    nativeName: "ಕನ್ನಡ (ಭಾರತ)",
    primary: false,
  },
  "mr-IN": {
    tag: "mr-IN",
    name: "Tiếng Marathi",
    nativeName: "मराठी (भारत)",
    primary: false,
  },
  "gu-IN": {
    tag: "gu-IN",
    name: "Tiếng Gujarati",
    nativeName: "ગુજરાતી (ભારત)",
    primary: false,
  },
  "pa-IN": {
    tag: "pa-IN",
    name: "Tiếng Punjabi",
    nativeName: "ਪੰਜਾਬੀ (ਭਾਰਤ)",
    primary: false,
  },
  "kok-IN": {
    tag: "kok-IN",
    name: "Tiếng Konkani",
    nativeName: "कोंकणी (भारत)",
    primary: false,
  },
  "sa-IN": {
    tag: "sa-IN",
    name: "Tiếng Phạn",
    nativeName: "संस्कृत (भारत)",
    primary: false,
  },
  "ur-PK": {
    tag: "ur-PK",
    name: "Tiếng Urdu",
    nativeName: "اردو (پاکستان)",
    primary: false,
  },
  "fa-IR": {
    tag: "fa-IR",
    name: "Tiếng Ba Tư",
    nativeName: "فارسی (ایران)",
    primary: false,
  },
  "syr-SY": {
    tag: "syr-SY",
    name: "Tiếng Syria",
    nativeName: "ܣܘܪܝܝܐ (ܣܘܪܝܐ)",
    primary: false,
  },
  "div-MV": {
    tag: "div-MV",
    name: "Tiếng Divehi",
    nativeName: "ދިވެހި (މޯލްޑިވްސް)",
    primary: false,
  },
  "ka-GE": {
    tag: "ka-GE",
    name: "Tiếng Gruzia",
    nativeName: "ქართული (საქართველო)",
    primary: false,
  },
  "am-ET": {
    tag: "am-ET",
    name: "Tiếng Amharic",
    nativeName: "አማርኛ (ኢትዮጵያ)",
    primary: false,
  },
  "my-MM": {
    tag: "my-MM",
    name: "Tiếng Myanmar",
    nativeName: "မြန်မာ (မြန်မာ)",
    primary: false,
  },
};

const { getTag, getTags, getPrimaryTags } = createTagUtils(tags);
export { getTag, getTags, getPrimaryTags };
export * from "./types";
