import { createTagUtils } from './utils'

export const tags = {
    "zh-CN": {"tag": "zh-CN", "name": "简体中文", "nativeName": "简体中文", "default": true},
    "zh-TW": {"tag": "zh-TW", "name": "繁体中文（台湾）", "nativeName": "繁體中文 (臺灣)"},
    "zh-HK": {"tag": "zh-HK", "name": "繁体中文（香港）", "nativeName": "繁體中文（香港）"},
    "zh-SG": {"tag": "zh-SG", "name": "简体中文（新加坡）", "nativeName": "简体中文 (新加坡)"},
    "zh-MO": {"tag": "zh-MO", "name": "繁体中文（澳门）", "nativeName": "繁體中文 (澳門)"},
    "zh-CHS": {"tag": "zh-CHS", "name": "简体中文", "nativeName": "简体中文"},
    "zh-CHT": {"tag": "zh-CHT", "name": "繁体中文", "nativeName": "繁體中文"},
    "en-US": {"tag": "en-US", "name": "英语（美国）", "nativeName": "English (United States)", "default": true},
    "en-GB": {"tag": "en-GB", "name": "英语（英国）", "nativeName": "English (United Kingdom)"},
    "en-IN": {"tag": "en-IN", "name": "英语（印度）", "nativeName": "English (India)"},
    "en-CA": {"tag": "en-CA", "name": "英语（加拿大）", "nativeName": "English (Canada)"},
    "en-AU": {"tag": "en-AU", "name": "英语（澳大利亚）", "nativeName": "English (Australia)"},
    "en-ZA": {"tag": "en-ZA", "name": "英语（南非）", "nativeName": "English (South Africa)"},
    "en-NZ": {"tag": "en-NZ", "name": "英语（新西兰）", "nativeName": "English (New Zealand)"},
    "en-IE": {"tag": "en-IE", "name": "英语（爱尔兰）", "nativeName": "English (Ireland)"},
    "en-PH": {"tag": "en-PH", "name": "英语（菲律宾）", "nativeName": "English (Philippines)"},
    "en-ZW": {"tag": "en-ZW", "name": "英语（津巴布韦）", "nativeName": "English (Zimbabwe)"},
    "en-BZ": {"tag": "en-BZ", "name": "英语（伯利兹）", "nativeName": "English (Belize)"},
    "en-CB": {"tag": "en-CB", "name": "英语（加勒比地区）", "nativeName": "English (Caribbean)"},
    "en-JM": {"tag": "en-JM", "name": "英语（牙买加）", "nativeName": "English (Jamaica)"},
    "en-TT": {"tag": "en-TT", "name": "英语（特立尼达和多巴哥）", "nativeName": "English (Trinidad and Tobago)"},
    "hi-IN": {"tag": "hi-IN", "name": "印地语", "nativeName": "हिन्दी (Hindi)"},
    "es-ES": {"tag": "es-ES", "name": "西班牙语（西班牙）", "nativeName": "Español (España)", "default": true},
    "es-MX": {"tag": "es-MX", "name": "西班牙语（墨西哥）", "nativeName": "Español (México)"},
    "es-AR": {"tag": "es-AR", "name": "西班牙语（阿根廷）", "nativeName": "Español (Argentina)"},
    "es-CO": {"tag": "es-CO", "name": "西班牙语（哥伦比亚）", "nativeName": "Español (Colombia)"},
    "es-PE": {"tag": "es-PE", "name": "西班牙语（秘鲁）", "nativeName": "Español (Perú)"},
    "es-VE": {"tag": "es-VE", "name": "西班牙语（委内瑞拉）", "nativeName": "Español (Venezuela)"},
    "es-CL": {"tag": "es-CL", "name": "西班牙语（智利）", "nativeName": "Español (Chile)"},
    "es-EC": {"tag": "es-EC", "name": "西班牙语（厄瓜多尔）", "nativeName": "Español (Ecuador)"},
    "es-GT": {"tag": "es-GT", "name": "西班牙语（危地马拉）", "nativeName": "Español (Guatemala)"},
    "es-CU": {"tag": "es-CU", "name": "西班牙语（古巴）", "nativeName": "Español (Cuba)"},
    "es-BO": {"tag": "es-BO", "name": "西班牙语（玻利维亚）", "nativeName": "Español (Bolivia)"},
    "es-DO": {"tag": "es-DO", "name": "西班牙语（多米尼加共和国）", "nativeName": "Español (República Dominicana)"},
    "es-HN": {"tag": "es-HN", "name": "西班牙语（洪都拉斯）", "nativeName": "Español (Honduras)"},
    "es-PY": {"tag": "es-PY", "name": "西班牙语（巴拉圭）", "nativeName": "Español (Paraguay)"},
    "es-SV": {"tag": "es-SV", "name": "西班牙语（萨尔瓦多）", "nativeName": "Español (El Salvador)"},
    "es-NI": {"tag": "es-NI", "name": "西班牙语（尼加拉瓜）", "nativeName": "Español (Nicaragua)"},
    "es-PR": {"tag": "es-PR", "name": "西班牙语（波多黎各）", "nativeName": "Español (Puerto Rico)"},
    "es-UY": {"tag": "es-UY", "name": "西班牙语（乌拉圭）", "nativeName": "Español (Uruguay)"},
    "es-PA": {"tag": "es-PA", "name": "西班牙语（巴拿马）", "nativeName": "Español (Panamá)"},
    "es-CR": {"tag": "es-CR", "name": "西班牙语（哥斯达黎加）", "nativeName": "Español (Costa Rica)"},
    "ar-EG": {"tag": "ar-EG", "name": "阿拉伯语（埃及）", "nativeName": "العربية (مصر)", "default": true},
    "ar-SA": {"tag": "ar-SA", "name": "阿拉伯语（沙特阿拉伯）", "nativeName": "العربية (السعودية)"},
    "ar-DZ": {"tag": "ar-DZ", "name": "阿拉伯语（阿尔及利亚）", "nativeName": "العربية (الجزائر)"},
    "ar-MA": {"tag": "ar-MA", "name": "阿拉伯语（摩洛哥）", "nativeName": "العربية (المغرب)"},
    "ar-IQ": {"tag": "ar-IQ", "name": "阿拉伯语（伊拉克）", "nativeName": "العربية (العراق)"},
    "ar-SD": {"tag": "ar-SD", "name": "阿拉伯语（苏丹）", "nativeName": "العربية (السودان)"},
    "ar-YE": {"tag": "ar-YE", "name": "阿拉伯语（也门）", "nativeName": "العربية (اليمن)"},
    "ar-SY": {"tag": "ar-SY", "name": "阿拉伯语（叙利亚）", "nativeName": "العربية (سوريا)"},
    "ar-TN": {"tag": "ar-TN", "name": "阿拉伯语（突尼斯）", "nativeName": "العربية (تونس)"},
    "ar-LY": {"tag": "ar-LY", "name": "阿拉伯语（利比亚）", "nativeName": "العربية (ليبيا)"},
    "ar-JO": {"tag": "ar-JO", "name": "阿拉伯语（约旦）", "nativeName": "العربية (الأردن)"},
    "ar-LB": {"tag": "ar-LB", "name": "阿拉伯语（黎巴嫩）", "nativeName": "العربية (لبنان)"},
    "ar-KW": {"tag": "ar-KW", "name": "阿拉伯语（科威特）", "nativeName": "العربية (الكويت)"},
    "ar-AE": {"tag": "ar-AE", "name": "阿拉伯语（阿联酋）", "nativeName": "العربية (الإمارات)"},
    "ar-BH": {"tag": "ar-BH", "name": "阿拉伯语（巴林）", "nativeName": "العربية (البحرين)"},
    "ar-QA": {"tag": "ar-QA", "name": "阿拉伯语（卡塔尔）", "nativeName": "العربية (قطر)"},
    "ar-OM": {"tag": "ar-OM", "name": "阿拉伯语（阿曼）", "nativeName": "العربية (عمان)"},
    "pt-BR": {"tag": "pt-BR", "name": "葡萄牙语（巴西）", "nativeName": "Português (Brasil)"},
    "pt-PT": {"tag": "pt-PT", "name": "葡萄牙语（葡萄牙）", "nativeName": "Português (Portugal)", "default": true},
    "ru-RU": {"tag": "ru-RU", "name": "俄语", "nativeName": "Русский (Россия)", "default": true},
    "ja-JP": {"tag": "ja-JP", "name": "日语", "nativeName": "日本語 (日本)", "default": true},
    "de-DE": {"tag": "de-DE", "name": "德语（德国）", "nativeName": "Deutsch (Deutschland)", "default": true},
    "de-AT": {"tag": "de-AT", "name": "德语（奥地利）", "nativeName": "Deutsch (Österreich)"},
    "de-CH": {"tag": "de-CH", "name": "德语（瑞士）", "nativeName": "Deutsch (Schweiz)"},
    "fr-FR": {"tag": "fr-FR", "name": "法语（法国）", "nativeName": "Français (France)", "default": true},
    "fr-CA": {"tag": "fr-CA", "name": "法语（加拿大）", "nativeName": "Français (Canada)"},
    "fr-BE": {"tag": "fr-BE", "name": "法语（比利时）", "nativeName": "Français (Belgique)"},
    "fr-CH": {"tag": "fr-CH", "name": "法语（瑞士）", "nativeName": "Français (Suisse)"},
    "fr-LU": {"tag": "fr-LU", "name": "法语（卢森堡）", "nativeName": "Français (Luxembourg)"},
    "fr-MC": {"tag": "fr-MC", "name": "法语（摩纳哥）", "nativeName": "Français (Monaco)"},
    "ko-KR": {"tag": "ko-KR", "name": "韩语", "nativeName": "한국어 (대한민국)", "default": true},
    "it-IT": {"tag": "it-IT", "name": "意大利语", "nativeName": "Italiano (Italia)", "default": true},
    "it-CH": {"tag": "it-CH", "name": "意大利语（瑞士）", "nativeName": "Italiano (Svizzera)"},
    "nl-NL": {"tag": "nl-NL", "name": "荷兰语", "nativeName": "Nederlands (Nederland)", "default": true},
    "nl-BE": {"tag": "nl-BE", "name": "荷兰语（比利时）", "nativeName": "Nederlands (België)"},
    "pl-PL": {"tag": "pl-PL", "name": "波兰语", "nativeName": "Polski (Polska)"},
    "vi-VN": {"tag": "vi-VN", "name": "越南语", "nativeName": "Tiếng Việt (Việt Nam)"},
    "tr-TR": {"tag": "tr-TR", "name": "土耳其语", "nativeName": "Türkçe (Türkiye)"},
    "th-TH": {"tag": "th-TH", "name": "泰语", "nativeName": "ไทย (ประเทศไทย)"},
    "el-GR": {"tag": "el-GR", "name": "希腊语", "nativeName": "Ελληνικά (Ελλάδα)"},
    "cs-CZ": {"tag": "cs-CZ", "name": "捷克语", "nativeName": "Čeština (Česká republika)"},
    "sv-SE": {"tag": "sv-SE", "name": "瑞典语", "nativeName": "Svenska (Sverige)"},
    "sv-FI": {"tag": "sv-FI", "name": "瑞典语（芬兰）", "nativeName": "Svenska (Finland)"},
    "hu-HU": {"tag": "hu-HU", "name": "匈牙利语", "nativeName": "Magyar (Magyarország)"},
    "fi-FI": {"tag": "fi-FI", "name": "芬兰语", "nativeName": "Suomi (Suomi)"},
    "da-DK": {"tag": "da-DK", "name": "丹麦语", "nativeName": "Dansk (Danmark)"},
    "nb-NO": {"tag": "nb-NO", "name": "挪威博克马尔语", "nativeName": "Norsk Bokmål (Norge)"},
    "nn-NO": {"tag": "nn-NO", "name": "挪威尼诺斯克语", "nativeName": "Norsk Nynorsk (Norge)"},
    "he-IL": {"tag": "he-IL", "name": "希伯来语", "nativeName": "עברית (ישראל)"},
    "id-ID": {"tag": "id-ID", "name": "印度尼西亚语", "nativeName": "Bahasa Indonesia (Indonesia)"},
    "ms-MY": {"tag": "ms-MY", "name": "马来语（马来西亚）", "nativeName": "Bahasa Melayu (Malaysia)"},
    "ms-BN": {"tag": "ms-BN", "name": "马来语（文莱）", "nativeName": "Bahasa Melayu (Brunei)"},
    "ro-RO": {"tag": "ro-RO", "name": "罗马尼亚语", "nativeName": "Română (România)"},
    "bg-BG": {"tag": "bg-BG", "name": "保加利亚语", "nativeName": "Български (България)"},
    "uk-UA": {"tag": "uk-UA", "name": "乌克兰语", "nativeName": "Українська (Україна)"},
    "sk-SK": {"tag": "sk-SK", "name": "斯洛伐克语", "nativeName": "Slovenčina (Slovensko)"},
    "sl-SI": {"tag": "sl-SI", "name": "斯洛文尼亚语", "nativeName": "Slovenščina (Slovenija)"},
    "hr-HR": {"tag": "hr-HR", "name": "克罗地亚语", "nativeName": "Hrvatski (Hrvatska)"},
    "ca-ES": {"tag": "ca-ES", "name": "加泰罗尼亚语", "nativeName": "Català (Catalunya)"},
    "lt-LT": {"tag": "lt-LT", "name": "立陶宛语", "nativeName": "Lietuvių (Lietuva)"},
    "lv-LV": {"tag": "lv-LV", "name": "拉脱维亚语", "nativeName": "Latviešu (Latvija)"},
    "et-EE": {"tag": "et-EE", "name": "爱沙尼亚语", "nativeName": "Eesti (Eesti)"},
    "sq-AL": {"tag": "sq-AL", "name": "阿尔巴尼亚语", "nativeName": "Shqip (Shqipëri)"},
    "mk-MK": {"tag": "mk-MK", "name": "马其顿语", "nativeName": "Македонски (Македонија)"},
    "be-BY": {"tag": "be-BY", "name": "白俄罗斯语", "nativeName": "Беларуская (Беларусь)"},
    "is-IS": {"tag": "is-IS", "name": "冰岛语", "nativeName": "Íslenska (Ísland)"},
    "gl-ES": {"tag": "gl-ES", "name": "加利西亚语", "nativeName": "Galego (Galicia)"},
    "eu-ES": {"tag": "eu-ES", "name": "巴斯克语", "nativeName": "Euskara (Euskal Herria)"},
    "af-ZA": {"tag": "af-ZA", "name": "南非荷兰语", "nativeName": "Afrikaans (Suid-Afrika)"},
    "sw-KE": {"tag": "sw-KE", "name": "斯瓦希里语", "nativeName": "Kiswahili (Kenya)"},
    "ta-IN": {"tag": "ta-IN", "name": "泰米尔语", "nativeName": "தமிழ் (இந்தியா)"},
    "te-IN": {"tag": "te-IN", "name": "泰卢固语", "nativeName": "తెలుగు (భారతదేశం)"},
    "kn-IN": {"tag": "kn-IN", "name": "卡纳达语", "nativeName": "ಕನ್ನಡ (ಭಾರತ)"},
    "mr-IN": {"tag": "mr-IN", "name": "马拉地语", "nativeName": "मराठी (भारत)"},
    "gu-IN": {"tag": "gu-IN", "name": "古吉拉特语", "nativeName": "ગુજરાતી (ભારત)"},
    "pa-IN": {"tag": "pa-IN", "name": "旁遮普语", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)"},
    "kok-IN": {"tag": "kok-IN", "name": "孔卡尼语", "nativeName": "कोंकणी (भारत)"},
    "sa-IN": {"tag": "sa-IN", "name": "梵语", "nativeName": "संस्कृत (भारत)"},
    "ur-PK": {"tag": "ur-PK", "name": "乌尔都语", "nativeName": "اردو (پاکستان)"},
    "fa-IR": {"tag": "fa-IR", "name": "波斯语", "nativeName": "فارسی (ایران)"},
    "syr-SY": {"tag": "syr-SY", "name": "叙利亚语", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)"},
    "div-MV": {"tag": "div-MV", "name": "迪维希语", "nativeName": "ދިވެހި (މޯލްޑިވްސް)"},
    "ka-GE": {"tag": "ka-GE", "name": "格鲁吉亚语", "nativeName": "ქართული (საქართველო)"}
}
  

const { getTag, getTags } = createTagUtils(tags)
export {
    getTag, getTags
}

export * from './types'    
export * from './types'    