import { createTagUtils } from './utils'

export const tags = {
    "zh-CN": {"tag": "zh-CN", "name": "简体中文", "nativeName": "简体中文", "primary": true },
    "zh-TW": {"tag": "zh-TW", "name": "繁体中文(台湾)", "nativeName": "繁體中文(臺灣)", "primary": false },
    "zh-HK": {"tag": "zh-HK", "name": "繁体中文(香港)", "nativeName": "繁體中文(香港),", "primary": false },
    "zh-SG": {"tag": "zh-SG", "name": "简体中文(新加坡)", "nativeName": "简体中文(新加坡)", "primary": false },
    "zh-MO": {"tag": "zh-MO", "name": "繁体中文(澳门)", "nativeName": "繁體中文(澳門)", "primary": false },
    "zh-CHS": {"tag": "zh-CHS", "name": "简体中文", "nativeName": "简体中文,", "primary": false },
    "zh-CHT": {"tag": "zh-CHT", "name": "繁体中文", "nativeName": "繁體中文,", "primary": false },
    "en-US": {"tag": "en-US", "name": "英语(美国)", "nativeName": "English (United States)", "primary": true  },
    "en-GB": {"tag": "en-GB", "name": "英语(英国)", "nativeName": "English (United Kingdom)", "primary": false },
    "en-IN": {"tag": "en-IN", "name": "英语(印度)", "nativeName": "English (India)", "primary": false },
    "en-CA": {"tag": "en-CA", "name": "英语(加拿大)", "nativeName": "English (Canada)", "primary": false },
    "en-AU": {"tag": "en-AU", "name": "英语(澳大利亚)", "nativeName": "English (Australia)", "primary": false },
    "en-ZA": {"tag": "en-ZA", "name": "英语(南非)", "nativeName": "English (South Africa)", "primary": false },
    "en-NZ": {"tag": "en-NZ", "name": "英语(新西兰)", "nativeName": "English (New Zealand)", "primary": false },
    "en-IE": {"tag": "en-IE", "name": "英语(爱尔兰)", "nativeName": "English (Ireland)", "primary": false },
    "en-PH": {"tag": "en-PH", "name": "英语(菲律宾)", "nativeName": "English (Philippines)", "primary": false },
    "en-ZW": {"tag": "en-ZW", "name": "英语(津巴布韦)", "nativeName": "English (Zimbabwe)", "primary": false },
    "en-BZ": {"tag": "en-BZ", "name": "英语(伯利兹)", "nativeName": "English (Belize)", "primary": false },
    "en-CB": {"tag": "en-CB", "name": "英语(加勒比地区)", "nativeName": "English (Caribbean)", "primary": false },
    "en-JM": {"tag": "en-JM", "name": "英语(牙买加)", "nativeName": "English (Jamaica)", "primary": false },
    "en-TT": {"tag": "en-TT", "name": "英语(特立尼达和多巴哥)", "nativeName": "English (Trinidad and Tobago)", "primary": false },
    "hi-IN": {"tag": "hi-IN", "name": "印地语", "nativeName": "हिन्दी (Hindi)", "primary": false },
    "es-ES": {"tag": "es-ES", "name": "西班牙语(西班牙)", "nativeName": "Español (España)", "primary": true  },
    "es-MX": {"tag": "es-MX", "name": "西班牙语(墨西哥)", "nativeName": "Español (México)", "primary": false },
    "es-AR": {"tag": "es-AR", "name": "西班牙语(阿根廷)", "nativeName": "Español (Argentina)", "primary": false },
    "es-CO": {"tag": "es-CO", "name": "西班牙语(哥伦比亚)", "nativeName": "Español (Colombia)", "primary": false },
    "es-PE": {"tag": "es-PE", "name": "西班牙语(秘鲁)", "nativeName": "Español (Perú)", "primary": false },
    "es-VE": {"tag": "es-VE", "name": "西班牙语(委内瑞拉)", "nativeName": "Español (Venezuela)", "primary": false },
    "es-CL": {"tag": "es-CL", "name": "西班牙语(智利)", "nativeName": "Español (Chile)", "primary": false },
    "es-EC": {"tag": "es-EC", "name": "西班牙语(厄瓜多尔)", "nativeName": "Español (Ecuador)", "primary": false },
    "es-GT": {"tag": "es-GT", "name": "西班牙语(危地马拉)", "nativeName": "Español (Guatemala)", "primary": false },
    "es-CU": {"tag": "es-CU", "name": "西班牙语(古巴)", "nativeName": "Español (Cuba)", "primary": false },
    "es-BO": {"tag": "es-BO", "name": "西班牙语(玻利维亚)", "nativeName": "Español (Bolivia)", "primary": false },
    "es-DO": {"tag": "es-DO", "name": "西班牙语(多米尼加共和国)", "nativeName": "Español (República Dominicana)", "primary": false },
    "es-HN": {"tag": "es-HN", "name": "西班牙语(洪都拉斯)", "nativeName": "Español (Honduras)", "primary": false },
    "es-PY": {"tag": "es-PY", "name": "西班牙语(巴拉圭)", "nativeName": "Español (Paraguay)", "primary": false },
    "es-SV": {"tag": "es-SV", "name": "西班牙语(萨尔瓦多)", "nativeName": "Español (El Salvador)", "primary": false },
    "es-NI": {"tag": "es-NI", "name": "西班牙语(尼加拉瓜)", "nativeName": "Español (Nicaragua)", "primary": false },
    "es-PR": {"tag": "es-PR", "name": "西班牙语(波多黎各)", "nativeName": "Español (Puerto Rico)", "primary": false },
    "es-UY": {"tag": "es-UY", "name": "西班牙语(乌拉圭)", "nativeName": "Español (Uruguay)", "primary": false },
    "es-PA": {"tag": "es-PA", "name": "西班牙语(巴拿马)", "nativeName": "Español (Panamá)", "primary": false },
    "es-CR": {"tag": "es-CR", "name": "西班牙语(哥斯达黎加)", "nativeName": "Español (Costa Rica)", "primary": false },
    "ar-EG": {"tag": "ar-EG", "name": "阿拉伯语(埃及)", "nativeName": "العربية (مصر)", "primary": true  },
    "ar-SA": {"tag": "ar-SA", "name": "阿拉伯语(沙特阿拉伯)", "nativeName": "العربية (السعودية)", "primary": false },
    "ar-DZ": {"tag": "ar-DZ", "name": "阿拉伯语(阿尔及利亚)", "nativeName": "العربية (الجزائر)", "primary": false },
    "ar-MA": {"tag": "ar-MA", "name": "阿拉伯语(摩洛哥)", "nativeName": "العربية (المغرب)", "primary": false },
    "ar-IQ": {"tag": "ar-IQ", "name": "阿拉伯语(伊拉克)", "nativeName": "العربية (العراق)", "primary": false },
    "ar-SD": {"tag": "ar-SD", "name": "阿拉伯语(苏丹)", "nativeName": "العربية (السودان)", "primary": false },
    "ar-YE": {"tag": "ar-YE", "name": "阿拉伯语(也门)", "nativeName": "العربية (اليمن)", "primary": false },
    "ar-SY": {"tag": "ar-SY", "name": "阿拉伯语(叙利亚)", "nativeName": "العربية (سوريا)", "primary": false },
    "ar-TN": {"tag": "ar-TN", "name": "阿拉伯语(突尼斯)", "nativeName": "العربية (تونس)", "primary": false },
    "ar-LY": {"tag": "ar-LY", "name": "阿拉伯语(利比亚)", "nativeName": "العربية (ليبيا)", "primary": false },
    "ar-JO": {"tag": "ar-JO", "name": "阿拉伯语(约旦)", "nativeName": "العربية (الأردن)", "primary": false },
    "ar-LB": {"tag": "ar-LB", "name": "阿拉伯语(黎巴嫩)", "nativeName": "العربية (لبنان)", "primary": false },
    "ar-KW": {"tag": "ar-KW", "name": "阿拉伯语(科威特)", "nativeName": "العربية (الكويت)", "primary": false },
    "ar-AE": {"tag": "ar-AE", "name": "阿拉伯语(阿联酋)", "nativeName": "العربية (الإمارات)", "primary": false },
    "ar-BH": {"tag": "ar-BH", "name": "阿拉伯语(巴林)", "nativeName": "العربية (البحرين)", "primary": false },
    "ar-QA": {"tag": "ar-QA", "name": "阿拉伯语(卡塔尔)", "nativeName": "العربية (قطر)", "primary": false },
    "ar-OM": {"tag": "ar-OM", "name": "阿拉伯语(阿曼)", "nativeName": "العربية (عمان)", "primary": false },
    "pt-BR": {"tag": "pt-BR", "name": "葡萄牙语(巴西)", "nativeName": "Português (Brasil)", "primary": false },
    "pt-PT": {"tag": "pt-PT", "name": "葡萄牙语(葡萄牙)", "nativeName": "Português (Portugal)", "primary": true  },
    "ru-RU": {"tag": "ru-RU", "name": "俄语", "nativeName": "Русский (Россия)", "primary": true  },
    "ja-JP": {"tag": "ja-JP", "name": "日语", "nativeName": "日本語 (日本)", "primary": true  },
    "de-DE": {"tag": "de-DE", "name": "德语(德国)", "nativeName": "Deutsch (Deutschland)", "primary": true  },
    "de-AT": {"tag": "de-AT", "name": "德语(奥地利)", "nativeName": "Deutsch (Österreich)", "primary": false },
    "de-CH": {"tag": "de-CH", "name": "德语(瑞士)", "nativeName": "Deutsch (Schweiz)", "primary": false },
    "fr-FR": {"tag": "fr-FR", "name": "法语(法国)", "nativeName": "Français (France)", "primary": true  },
    "fr-CA": {"tag": "fr-CA", "name": "法语(加拿大)", "nativeName": "Français (Canada)", "primary": false },
    "fr-BE": {"tag": "fr-BE", "name": "法语(比利时)", "nativeName": "Français (Belgique)", "primary": false },
    "fr-CH": {"tag": "fr-CH", "name": "法语(瑞士)", "nativeName": "Français (Suisse)", "primary": false },
    "fr-LU": {"tag": "fr-LU", "name": "法语(卢森堡)", "nativeName": "Français (Luxembourg)", "primary": false },
    "fr-MC": {"tag": "fr-MC", "name": "法语(摩纳哥)", "nativeName": "Français (Monaco)", "primary": false },
    "ko-KR": {"tag": "ko-KR", "name": "韩语", "nativeName": "한국어 (대한민국)", "primary": true  },
    "it-IT": {"tag": "it-IT", "name": "意大利语", "nativeName": "Italiano (Italia)", "primary": true  },
    "it-CH": {"tag": "it-CH", "name": "意大利语(瑞士)", "nativeName": "Italiano (Svizzera)", "primary": false },
    "nl-NL": {"tag": "nl-NL", "name": "荷兰语", "nativeName": "Nederlands (Nederland)", "primary": true  },
    "nl-BE": {"tag": "nl-BE", "name": "荷兰语(比利时)", "nativeName": "Nederlands (België)", "primary": false },
    "pl-PL": {"tag": "pl-PL", "name": "波兰语", "nativeName": "Polski (Polska)", "primary": false },
    "vi-VN": {"tag": "vi-VN", "name": "越南语", "nativeName": "Tiếng Việt (Việt Nam)", "primary": false },
    "tr-TR": {"tag": "tr-TR", "name": "土耳其语", "nativeName": "Türkçe (Türkiye)", "primary": false },
    "th-TH": {"tag": "th-TH", "name": "泰语", "nativeName": "ไทย (ประเทศไทย)", "primary": false },
    "el-GR": {"tag": "el-GR", "name": "希腊语", "nativeName": "Ελληνικά (Ελλάδα)", "primary": false },
    "cs-CZ": {"tag": "cs-CZ", "name": "捷克语", "nativeName": "Čeština (Česká republika)", "primary": false },
    "sv-SE": {"tag": "sv-SE", "name": "瑞典语", "nativeName": "Svenska (Sverige)", "primary": false  },
    "sv-FI": {"tag": "sv-FI", "name": "瑞典语(芬兰)", "nativeName": "Svenska (Finland)", "primary": false },
    "hu-HU": {"tag": "hu-HU", "name": "匈牙利语", "nativeName": "Magyar (Magyarország)", "primary": false },
    "fi-FI": {"tag": "fi-FI", "name": "芬兰语", "nativeName": "Suomi (Suomi)", "primary": false },
    "da-DK": {"tag": "da-DK", "name": "丹麦语", "nativeName": "Dansk (Danmark)", "primary": false },
    "nb-NO": {"tag": "nb-NO", "name": "挪威博克马尔语", "nativeName": "Norsk Bokmål (Norge)", "primary": false },
    "nn-NO": {"tag": "nn-NO", "name": "挪威尼诺斯克语", "nativeName": "Norsk Nynorsk (Norge)", "primary": false },
    "he-IL": {"tag": "he-IL", "name": "希伯来语", "nativeName": "עברית (ישראל)", "primary": false },
    "id-ID": {"tag": "id-ID", "name": "印度尼西亚语", "nativeName": "Bahasa Indonesia (Indonesia)", "primary": false },
    "ms-MY": {"tag": "ms-MY", "name": "马来语(马来西亚)", "nativeName": "Bahasa Melayu (Malaysia)", "primary": false },
    "ms-BN": {"tag": "ms-BN", "name": "马来语(文莱)", "nativeName": "Bahasa Melayu (Brunei)", "primary": false },
    "ro-RO": {"tag": "ro-RO", "name": "罗马尼亚语", "nativeName": "Română (România)", "primary": false },
    "bg-BG": {"tag": "bg-BG", "name": "保加利亚语", "nativeName": "Български (България)", "primary": false },
    "uk-UA": {"tag": "uk-UA", "name": "乌克兰语", "nativeName": "Українська (Україна)", "primary": false },
    "sk-SK": {"tag": "sk-SK", "name": "斯洛伐克语", "nativeName": "Slovenčina (Slovensko)", "primary": false },
    "sl-SI": {"tag": "sl-SI", "name": "斯洛文尼亚语", "nativeName": "Slovenščina (Slovenija)", "primary": false },
    "hr-HR": {"tag": "hr-HR", "name": "克罗地亚语", "nativeName": "Hrvatski (Hrvatska)", "primary": false },
    "ca-ES": {"tag": "ca-ES", "name": "加泰罗尼亚语", "nativeName": "Català (Catalunya)", "primary": false },
    "lt-LT": {"tag": "lt-LT", "name": "立陶宛语", "nativeName": "Lietuvių (Lietuva)", "primary": false },
    "lv-LV": {"tag": "lv-LV", "name": "拉脱维亚语", "nativeName": "Latviešu (Latvija)", "primary": false },
    "et-EE": {"tag": "et-EE", "name": "爱沙尼亚语", "nativeName": "Eesti (Eesti)", "primary": false },
    "sq-AL": {"tag": "sq-AL", "name": "阿尔巴尼亚语", "nativeName": "Shqip (Shqipëri)", "primary": false },
    "mk-MK": {"tag": "mk-MK", "name": "马其顿语", "nativeName": "Македонски (Македонија)", "primary": false },
    "be-BY": {"tag": "be-BY", "name": "白俄罗斯语", "nativeName": "Беларуская (Беларусь)", "primary": false },
    "is-IS": {"tag": "is-IS", "name": "冰岛语", "nativeName": "Íslenska (Ísland)", "primary": false },
    "gl-ES": {"tag": "gl-ES", "name": "加利西亚语", "nativeName": "Galego (Galicia)", "primary": false },
    "eu-ES": {"tag": "eu-ES", "name": "巴斯克语", "nativeName": "Euskara (Euskal Herria)", "primary": false },
    "af-ZA": {"tag": "af-ZA", "name": "南非荷兰语", "nativeName": "Afrikaans (Suid-Afrika)", "primary": false },
    "sw-KE": {"tag": "sw-KE", "name": "斯瓦希里语", "nativeName": "Kiswahili (Kenya)", "primary": false },
    "ta-IN": {"tag": "ta-IN", "name": "泰米尔语", "nativeName": "தமிழ் (இந்தியா)", "primary": false },
    "te-IN": {"tag": "te-IN", "name": "泰卢固语", "nativeName": "తెలుగు (భారతదేశం)", "primary": false },
    "kn-IN": {"tag": "kn-IN", "name": "卡纳达语", "nativeName": "ಕನ್ನಡ (ಭಾರತ)", "primary": false },
    "mr-IN": {"tag": "mr-IN", "name": "马拉地语", "nativeName": "मराठी (भारत)", "primary": false },
    "gu-IN": {"tag": "gu-IN", "name": "古吉拉特语", "nativeName": "ગુજરાતી (ભારત)", "primary": false },
    "pa-IN": {"tag": "pa-IN", "name": "旁遮普语", "nativeName": "ਪੰਜਾਬੀ (ਭਾਰਤ)", "primary": false },
    "kok-IN": {"tag": "kok-IN", "name": "孔卡尼语", "nativeName": "कोंकणी (भारत)", "primary": false },
    "sa-IN": {"tag": "sa-IN", "name": "梵语", "nativeName": "संस्कृत (भारत)", "primary": false },
    "ur-PK": {"tag": "ur-PK", "name": "乌尔都语", "nativeName": "اردو (پاکستان)", "primary": false },
    "fa-IR": {"tag": "fa-IR", "name": "波斯语", "nativeName": "فارسی (ایران)", "primary": false },
    "syr-SY": {"tag": "syr-SY", "name": "叙利亚语", "nativeName": "ܣܘܪܝܝܐ (ܣܘܪܝܐ)", "primary": false },
    "div-MV": {"tag": "div-MV", "name": "迪维希语", "nativeName": "ދިވެހި (މޯލްޑިވްސް)", "primary": false },
    "ka-GE": {"tag": "ka-GE", "name": "格鲁吉亚语", "nativeName": "ქართული (საქართველო)", "primary": false }
}
  

const { getTag, getTags, getPrimaryTags } = createTagUtils(tags)
export {
    getTag, getTags,getPrimaryTags
}
export * from './types'    